--
-- ACTIVITY_REPORT_DATE_FILTER_PART1  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.ACTIVITY_REPORT_DATE_FILTER_PART1
(MSISDN, LU_PRODUCT_KEY, LU_MOC_DATE_KEY, LU_MOC_ACTUAL_DURATION, LU_MTC_DATE_KEY, 
 LU_MTC_ACTUAL_DURATION, LU_MOSMS_DATE_KEY, LU_GPRS_DATE_KEY, LU_GPRS_DATA_SIZE, LR_DATE_KEY, 
 LR_PRODUCT_KEY, RE9_ORIGINAL_AMT)
BEQUEATH DEFINER
AS 
(SELECT MSISDN,LU_PRODUCT_KEY,LU_MOC_DATE_KEY,LU_MOC_ACTUAL_DURATION,LU_MTC_DATE_KEY,LU_MTC_ACTUAL_DURATION,
      LU_MOSMS_DATE_KEY,LU_GPRS_DATE_KEY,LU_GPRS_DATA_SIZE,LR_DATE_KEY,LR_PRODUCT_KEY,RE9_ORIGINAL_AMT

 FROM 
(
SELECT /*+PARALLEL(P,15)*/ MSISDN,LU_PRODUCT_KEY,
        LU_MOC_DATE_KEY,LU_MOC_ACTUAL_DURATION,
        LU_MTC_DATE_KEY,LU_MTC_ACTUAL_DURATION,
        LU_MOSMS_DATE_KEY,
        LU_GPRS_DATE_KEY,LU_GPRS_DATA_SIZE,
        LR_DATE_KEY,
        LR_PRODUCT_KEY
        
FROM LAST_ACTIVITY_FCT_LD P
WHERE LU_DATE_KEY <(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
AND LU_DATE_KEY >=(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
)A

LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,15)*/  RE6_PRI_IDENTITY,RE30_ENTRY_DATE_KEY,RE9_ORIGINAL_AMT


 FROM L3_RECHARGE P
WHERE (RE30_ENTRY_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
                          AND (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-8,'DD/MM/RRRR')))
                          AND EXISTS (SELECT * FROM
                          (SELECT /*+PARALLEL(P,15)*/  RE6_PRI_IDENTITY,MAX(TO_NUMBER(CONCAT (RE30_ENTRY_DATE_KEY,RE30_ENTRY_HOUR))) DATE_HOUR

FROM L3_RECHARGE P
WHERE (RE30_ENTRY_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
                          AND (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-8,'DD/MM/RRRR')))
GROUP BY RE6_PRI_IDENTITY)R WHERE P.RE6_PRI_IDENTITY=R.RE6_PRI_IDENTITY AND TO_NUMBER(CONCAT (RE30_ENTRY_DATE_KEY,RE30_ENTRY_HOUR))=R.DATE_HOUR
)
)B ON MSISDN=RE6_PRI_IDENTITY

);


