--
-- ACTIVITY_REPORT_DATE_FILTER_PART2  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.ACTIVITY_REPORT_DATE_FILTER_PART2
(SAF_MSISDN, SAF_RETAILERMOBILE, SAF_ENTRYDATE)
BEQUEATH DEFINER
AS 
(select /*+PARALLEL(P,15)*/  SAF_MSISDN,SAF_RETAILERMOBILE,TO_DATE(substr(SAF_ENTRYDATE,1,9))SAF_ENTRYDATE 
from bi_saf@DWH05TOETSAF P
where SAF_VERIFIED=4
AND SAF_REG_TYPE_DESC IN ('NEW_PREPAID','PREPAID_CAMPAIGN','NEW_POSTPAID','RE-REGISTRATION','POSTPAID','PREPAID')

);


