--
-- BIN12DATAVOICE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN12DATAVOICE
(X, VOLUME3G, VOLUME2G, VOLUME4G, P, 
 VOICE_REVENUE)
BEQUEATH DEFINER
AS 
select "X","VOLUME3G","VOLUME2G","VOLUME4G","P","VOICE_REVENUE" from
  BIN12TOTALDATAVOLUME
  full join  
  BIN12TOTALVOICEREVENUE
  on X=P;


