--
-- BIN16_VOICE_DATA  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN16_VOICE_DATA
(X, VOLUME3G, VOLUME2G, VOLUME4G, P, 
 MO_DURATION, MT_DURATION)
BEQUEATH DEFINER
AS 
SELECT X,
          VOLUME3G,
          VOLUME2G,
          VOLUME4G,
          P,
          MO_DURATION,
          MT_DURATION
          
     FROM BIN16_TOTAL_DATA_VOLUME
          FULL JOIN BIN16_TOTAL_VOICE_DURATION ON X = P;


