--
-- BIN16_TOTAL_VOICE_DURATION  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN16_TOTAL_VOICE_DURATION
(P, MO_DURATION, MT_DURATION)
BEQUEATH DEFINER
AS 
SELECT "P", "MO_DURATION", "MT_DURATION"
     FROM (SELECT P, MO_DURATION, MT_DURATION FROM BIN16_VOICE_DURATION
           UNION
           SELECT Q, MO_DURATION, MT_DURATION FROM BIN16_VOICE_DURATION)
    WHERE P IS NOT NULL;


