--
-- BIN16_TOTAL_VOICE_DATA  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN16_TOTAL_VOICE_DATA
(X, VOLUME3G, VOLUME2G, VOLUME4G, MO_DURATION, 
 MT_DURATION)
BEQUEATH DEFINER
AS 
select "X","VOLUME3G","VOLUME2G","VOLUME4G","MO_DURATION","MT_DURATION" from
((select X, VOLUME3G, VOLUME2G, VOLUME4G, MO_DURATION, MT_DURATION
from BIN16_VOICE_DATA)
union
(select P, VOLUME3G, VOLUME2G, VOLUME4G, MO_DURATION, MT_DURATION
from BIN16_VOICE_DATA))

where X is not null;


