--
-- BIN16_TOTAL_SMS_COUNT  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN16_TOTAL_SMS_COUNT
(U, SMS_COUNT)
BEQUEATH DEFINER
AS 
SELECT S395_MAINOFFERINGID U, COUNT (S22_PRI_IDENTITY) SMS_Count
       FROM L3_SMS
      WHERE S387_CHARGINGTIME_KEY =
               (SELECT DATE_KEY
                  FROM DATE_DIM
                 WHERE DATE_VALUE = TO_DATE (SYSDATE - 1, 'DD/MM/RRRR'))
   --AND S395_MAINOFFERINGID IS NOT NULL
   GROUP BY S395_MAINOFFERINGID;


