--
-- BIN3UNIONJOINVOICEDATA  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN3UNIONJOINVOICEDATA
(DATA_ETL_DATE_KEY, G401_MAINOFFERINGID, VOICEDATACOUNT)
BEQUEATH DEFINER
AS 
select "DATA_ETL_DATE_KEY","G401_MAINOFFERINGID","VOICEDATACOUNT" from
(select DATA_ETL_DATE_KEY, G401_MAINOFFERINGID, VOICEDATACOUNT
from BIN3JOINVOICEDATA
union
select  VOICE_ETL_DATE_KEY, V397_MAINOFFERINGID, VOICEDATACOUNT
from BIN3JOINVOICEDATA)
where DATA_ETL_DATE_KEY is not null and G401_MAINOFFERINGID is not null;


