--
-- BIN3713UNIONDURATION  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN3713UNIONDURATION
(Y, DURATION)
BEQUEATH DEFINER
AS 
select "Y","DURATION" from
(
select Y,  DURATION
from BIN3713DURATION
union
select X, DURATION
from BIN3713DURATION
)
where Y is not null;


