--
-- BIN6JOINDATAVOICE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN6JOINDATAVOICE
(G372_CALLINGPARTYNUMBER, G401_MAINOFFERINGID, V372_CALLINGPARTYNUMBER, V397_MAINOFFERINGID, DATAVOICE_REV)
BEQUEATH DEFINER
AS 
SELECT G372_CALLINGPARTYNUMBER,
          G401_MAINOFFERINGID,
          V372_CALLINGPARTYNUMBER,
          V397_MAINOFFERINGID,
          COALESCE (DATA_REV, 0) + COALESCE (VOICE_REV, 0) DATAVOICE_REV
     FROM (  SELECT G372_CALLINGPARTYNUMBER,
                    G401_MAINOFFERINGID,
                    SUM (G41_DEBIT_AMOUNT) DATA_REV
               FROM L3_DATA
              WHERE G383_CHARGINGTIME_KEY =
                       (SELECT A.DATE_KEY
                          FROM DATE_DIM A
                         WHERE A.DATE_VALUE =
                                  TO_DATE (SYSDATE - 6, 'DD/MM/RRRR'))
           GROUP BY G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER)
          FULL JOIN
          (  SELECT V372_CALLINGPARTYNUMBER,
                    V397_MAINOFFERINGID,
                    SUM (V41_DEBIT_AMOUNT) VOICE_REV
               FROM L3_VOICE
              WHERE     V403_ROAMSTATE != 3
                    AND V387_CHARGINGTIME_KEY =
                           (SELECT A.DATE_KEY
                              FROM DATE_DIM A
                             WHERE A.DATE_VALUE =
                                      TO_DATE (SYSDATE - 6, 'DD/MM/RRRR'))
           GROUP BY V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER)
             ON     G372_CALLINGPARTYNUMBER = V372_CALLINGPARTYNUMBER
                AND G401_MAINOFFERINGID = V397_MAINOFFERINGID;


