--
-- BIN6JOINSMSRECURRING  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN6JOINSMSRECURRING
(S22_PRI_IDENTITY, S395_MAINOFFERINGID, R375_CHARGINGPARTYNUMBER, R373_MAINOFFERINGID, SMSRECURRING_REV)
BEQUEATH DEFINER
AS 
SELECT S22_PRI_IDENTITY,
          S395_MAINOFFERINGID,
          R375_CHARGINGPARTYNUMBER,
          R373_MAINOFFERINGID,
          COALESCE (SMS_REV, 0) + COALESCE (RECURRING_REV, 0)
             SMSRECURRING_REV
     FROM (  SELECT S22_PRI_IDENTITY,
                    S395_MAINOFFERINGID,
                    SUM (S41_DEBIT_AMOUNT) SMS_REV
               FROM L3_SMS
              WHERE S387_CHARGINGTIME_KEY =
                       (SELECT A.DATE_KEY
                          FROM DATE_DIM A
                         WHERE A.DATE_VALUE =
                                  TO_DATE (SYSDATE - 6, 'DD/MM/RRRR'))
           GROUP BY S22_PRI_IDENTITY, S395_MAINOFFERINGID)
          FULL JOIN
          (  SELECT R375_CHARGINGPARTYNUMBER,
                    R373_MAINOFFERINGID,
                    SUM (R41_DEBIT_AMOUNT) RECURRING_REV
               FROM L3_RECURRING
              WHERE R377_CYCLEBEGINTIME_KEY =
                       (SELECT A.DATE_KEY
                          FROM DATE_DIM A
                         WHERE A.DATE_VALUE =
                                  TO_DATE (SYSDATE - 6, 'DD/MM/RRRR'))
           GROUP BY R375_CHARGINGPARTYNUMBER, R373_MAINOFFERINGID)
             ON     R375_CHARGINGPARTYNUMBER = S22_PRI_IDENTITY
                AND S395_MAINOFFERINGID = R373_MAINOFFERINGID;


