--
-- BIN6UNIONJOINDATAVOICE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN6UNIONJOINDATAVOICE
(G372_CALLINGPARTYNUMBER, G401_MAINOFFERINGID, DATAVOICE_REV)
BEQUEATH DEFINER
AS 
select "G372_CALLINGPARTYNUMBER","G401_MAINOFFERINGID","DATAVOICE_REV" from
 (select G372_CALLINGPARTYNUMBER, G401_MAINOFFERINGID, DATAVOICE_REV
 from BIN6JOINDATAVOICE
 UNION
 select V372_CALLINGPARTYNUMBER, V397_MAINOFFERINGID, DATAVOICE_REV
 from BIN6JOINDATAVOICE)
 where G372_CALLINGPARTYNUMBER is not null and G401_MAINOFFERINGID is not null;


