--
-- BIN7UNIONJOINVOICEDATA  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIN7UNIONJOINVOICEDATA
(V_CELLID, TOTAL_COUNT)
BEQUEATH DEFINER
AS 
select "V_CELLID","TOTAL_COUNT" from 
   (SELECT V_CELLID, TOTAL_COUNT FROM BIN7JOINVOICEDATA
    UNION
    SELECT G_CELLID, TOTAL_COUNT FROM BIN7JOINVOICEDATA)
    where V_CELLID is not null;


