--
-- BIO7TOTALVOICEREVENUE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BIO7TOTALVOICEREVENUE
(VOICE_PACKAGE1, TYPE1, X, VOICE_REVENUE)
BEQUEATH DEFINER
AS 
select "VOICE_PACKAGE1","TYPE1","X","VOICE_REVENUE" from
(select VOICE_PACKAGE1,  TYPE1, X, VOICE_REVENUE
from BIO7JOINVOICEREVENUE
union
select VOICE_PACKAGE2, TYPE2, Y, VOICE_REVENUE
from BIO7JOINVOICEREVENUE
) where VOICE_PACKAGE1 is not null and   TYPE1 is not null and X is not null;


