--
-- BRAND_PORTFOLIO_JOINVOICESMSDATARECURRING  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BRAND_PORTFOLIO_JOINVOICESMSDATARECURRING
(X, Y, TOTAL_REVENUE)
BEQUEATH DEFINER
AS 
select X,Y,COALESCE (VOICE_SMS_REVENUE, 0) + COALESCE (DATA_RECURRING_REVENUE, 0) TOTAL_REVENUE from 
    (  select * from 
    (select V397_MAINOFFERINGID X, VOICE_SMS_REVENUE
    from BRAND_PORTFOLIO_JOINVOICESMS
    union
    select S395_MAINOFFERINGID, VOICE_SMS_REVENUE
    from BRAND_PORTFOLIO_JOINVOICESMS)
    where X is not null)
    full join
    (select * from 
    (select G401_MAINOFFERINGID Y, DATA_RECURRING_REVENUE
    from BRAND_PORTFOLIO_JOINDATARECURRING
    union
    select R373_MAINOFFERINGID, DATA_RECURRING_REVENUE
    from BRAND_PORTFOLIO_JOINDATARECURRING)
    where Y is not null) on X=Y;


