--
-- BTS  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.BTS
(SITE_ID, CGI, LAC, CI, CELL_NAME, 
 SITE_NAME, LONGITUDE, LATITUDE, TECHNOLOGY, FULL_ADDRESS, 
 UPAZILA, DISTRICT, DIVISION)
BEQUEATH DEFINER
AS 
SELECT
A.SITE_ID,
A.CGI,
A.LAC,
A.CI,
A.CELL_NAME,
B.SITE_NAME,
B.LONGITUDE,
B.LATITUDE,
B.TECHNOLOGY,
B.FULL_ADDRESS,
B.UPAZILA,
B.DISTRICT,
B.DIVISION
FROM
COMMON_CELL_DATA A INNER JOIN SITE_DATA B
ON A.SITE_ID = B.SITE_ID;


