--
-- CHURN_DATA_EXP  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.CHURN_DATA_EXP
(CUSTOMER_ID, MONTHLY_DATA_PACK_BY_COUNT, MONTHLY_DATA_VOLUME_USED, MONTHLY_PACK_BY_COUNT, MONTHLY_RECHARGE_COUNT, 
 MONTHLY_RECHARGE_AMOUNT, MONTHLY_MO_CALL, MONTHLY_MT_CALL, MONTHLY_VAS_REVENUE, MONTHLY_SMS_SEND_COUNT, 
 MONTHLY_AVG_REVENUE, MONTHLY_VOICE_PACK_BUY_CNT_MT, MONTHLY_VOICE_PACK_BUY_CNT_MO)
BEQUEATH DEFINER
AS 
SELECT CUSTOMER_ID, MONTHLY_DATA_PACK_BY_COUNT, MONTHLY_DATA_VOLUME_USED / 1048576 MONTHLY_DATA_VOLUME_USED, MONTHLY_PACK_BY_COUNT, 
MONTHLY_RECHARGE_COUNT, MONTHLY_RECHARGE_AMOUNT, MONTHLY_MO_CALL, MONTHLY_MT_CALL, MONTHLY_VAS_REVENUE, 
MONTHLY_SMS_SEND_COUNT, MONTHLY_AVG_REVENUE, MONTHLY_VOICE_PACK_BUY_CNT_MT, MONTHLY_VOICE_PACK_BUY_CNT_MO
FROM L3_MONTHLY_CHURN_NEW;


