--
-- CLM_A_17  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.CLM_A_17
(DISTRICT, MSISDN, DURATION)
BEQUEATH DEFINER
AS 
SELECT "DISTRICT","MSISDN","DURATION" FROM 
(SELECT INITCAP(DISTRICT) DISTRICT,MSISDN,DURATION FROM ZONE_DIM,
(SELECT V381_CALLINGCELLID ,
            V372_CALLINGPARTYNUMBER MSISDN,
            SUM (V35_RATE_USAGE) / 60 DURATION
       FROM L3_VOICE
      WHERE V387_CHARGINGTIME_KEY IN (SELECT DATE_KEY
                                        FROM DATE_DIM
                                       WHERE DATE_VALUE >=
                                                TO_DATE (SYSDATE - 20,
                                                         'DD/MM/RRRR'))
   GROUP BY V372_CALLINGPARTYNUMBER, V381_CALLINGCELLID
)
WHERE CGI=V381_CALLINGCELLID
);


