--
-- CORONA_16263  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.CORONA_16263
(MSISDN, TIMESTAMP, LATITUDE, LONGITUDE, UPAZILA, 
 DISTRICT, NAME)
BEQUEATH DEFINER
AS 
SELECT F.MSISDN,F.TIMESTAMP,F.LATITUDE, F.LONGITUDE, F.UPAZILA,F.DISTRICT, F.NAME
FROM
(SELECT Z.V372_CALLINGPARTYNUMBER AS MSISDN, TO_CHAR(TO_DATE(Z.CALL_DATE,'YYYY-MM-DD HH24:MI:SS'),'YYYY-MM-DD HH24:MI:SS') AS TIMESTAMP ,Z.LATITUDE, Z.LONGITUDE, Z.UPAZILA,Z.DISTRICT, A.NAME
FROM SAF_DATA@DWH05TODWH01 A,
(SELECT K.V372_CALLINGPARTYNUMBER,K.DATE_VALUE||K.V387_CHARGINGTIME_HOUR AS CALL_DATE, M.LATITUDE, M.LONGITUDE, M.UPAZILA,M.DISTRICT
    FROM ZONE_DIM@DWH05TODWH01 M,
        (SELECT V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER, TO_CHAR(B.DATE_VALUE,'RRRRMMDD') AS DATE_VALUE,V387_CHARGINGTIME_HOUR
        --FROM L3_VOICE A, DATE_DIM B
        FROM L2_VOICE_333@DWH05TODWH01 A, DATE_DIM B
        WHERE V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'DD/MM/RRRR'))
        --AND V373_CALLEDPARTYNUMBER ='333'
        AND V373_CALLEDPARTYNUMBER ='16263'
        AND V387_CHARGINGTIME_KEY=B.DATE_KEY
        GROUP BY V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER,B.DATE_VALUE,V387_CHARGINGTIME_HOUR)K
WHERE CGI=V381_CALLINGCELLID
GROUP BY  K.V372_CALLINGPARTYNUMBER,K.DATE_VALUE||K.V387_CHARGINGTIME_HOUR, M.LATITUDE, M.LONGITUDE, M.UPAZILA,M.DISTRICT
ORDER BY K.V372_CALLINGPARTYNUMBER,M.DISTRICT)Z
WHERE Z.V372_CALLINGPARTYNUMBER=A.MSISDN(+))F
union all
SELECT F.MSISDN,F.TIMESTAMP,F.LATITUDE, F.LONGITUDE, F.UPAZILA,F.DISTRICT, F.NAME
FROM
(SELECT Z.V372_CALLINGPARTYNUMBER AS MSISDN, TO_CHAR(TO_DATE(Z.CALL_DATE,'YYYY-MM-DD HH24:MI:SS'),'YYYY-MM-DD HH24:MI:SS') AS TIMESTAMP ,Z.LATITUDE, Z.LONGITUDE, Z.UPAZILA,Z.DISTRICT, A.NAME
FROM SAF_DATA@DWH05TODWH01 A,
(SELECT K.V372_CALLINGPARTYNUMBER,K.DATE_VALUE||K.V387_CHARGINGTIME_HOUR AS CALL_DATE, M.LATITUDE, M.LONGITUDE, M.UPAZILA,M.DISTRICT
    FROM ZONE_DIM@DWH05TODWH01 M,
        (SELECT V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER, TO_CHAR(B.DATE_VALUE,'RRRRMMDD') AS DATE_VALUE,V387_CHARGINGTIME_HOUR
        FROM L3_VOICE A, DATE_DIM B
        --FROM L2_VOICE_333@DWH05TODWH01 A, DATE_DIM B
        WHERE V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'DD/MM/RRRR'))
        --AND V373_CALLEDPARTYNUMBER ='333'
        AND V373_CALLEDPARTYNUMBER ='16263'
        AND V387_CHARGINGTIME_KEY=B.DATE_KEY
        GROUP BY V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER,B.DATE_VALUE,V387_CHARGINGTIME_HOUR)K
WHERE CGI=V381_CALLINGCELLID
GROUP BY  K.V372_CALLINGPARTYNUMBER,K.DATE_VALUE||K.V387_CHARGINGTIME_HOUR, M.LATITUDE, M.LONGITUDE, M.UPAZILA,M.DISTRICT
ORDER BY K.V372_CALLINGPARTYNUMBER,M.DISTRICT)Z
WHERE Z.V372_CALLINGPARTYNUMBER=A.MSISDN(+))F;


