--
-- COVID_19_16263  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.COVID_19_16263
(MSISDN, TIMESTAMP, LATITUDE, LONGITUDE, UPAZILA, 
 DISTRICT, NAME, DURATION, LAST3_DAY)
BEQUEATH DEFINER
AS 
SELECT Z.V372_CALLINGPARTYNUMBER AS MSISDN, TO_CHAR(TO_DATE(Z.CALL_DATE,'YYYY-MM-DD HH24:MI:SS'),'YYYY-MM-DD HH24:MI:SS') AS TIMESTAMP,Z.LATITUDE, Z.LONGITUDE, Z.UPAZILA,Z.DISTRICT, A.NAME,round(V35_RATE_USAGE) AS DURATION, nvl(acount,0) as last3_day
FROM SAF_DATA@DWH05TODWH01 A,
(select MSISDN, count(acount) as acount
from(
select MSISDN, count(LU_DATE_KEY) as acount
from LAST_ACTIVITY_FCT 
where LU_DATE_KEY IN (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE BETWEEN TO_DATE (SYSDATE-5,'DD/MM/RRRR') AND TO_DATE (SYSDATE-2,'DD/MM/RRRR'))
group by MSISDN)
group by MSISDN)b,
(SELECT K.V372_CALLINGPARTYNUMBER,K.DATE_VALUE||K.V387_CHARGINGTIME_HOUR AS CALL_DATE,K.V35_RATE_USAGE, M.LATITUDE, M.LONGITUDE, M.UPAZILA,M.DISTRICT
    FROM ZONE_DIM@DWH05TODWH01 M,
        (SELECT V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER, TO_CHAR(B.DATE_VALUE,'RRRRMMDD') AS DATE_VALUE,V387_CHARGINGTIME_HOUR,V35_RATE_USAGE
        FROM L3_VOICE A, DATE_DIM B
        --FROM L2_VOICE_333@DWH05TODWH01 A, DATE_DIM B
        WHERE V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'DD/MM/RRRR'))
        --AND V373_CALLEDPARTYNUMBER ='333'
        AND V373_CALLEDPARTYNUMBER ='16263'
        AND V387_CHARGINGTIME_KEY=B.DATE_KEY
        GROUP BY V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER,B.DATE_VALUE,V387_CHARGINGTIME_HOUR,V35_RATE_USAGE)K
WHERE CGI=V381_CALLINGCELLID
GROUP BY  K.V372_CALLINGPARTYNUMBER,K.DATE_VALUE||K.V387_CHARGINGTIME_HOUR,K.V35_RATE_USAGE, M.LATITUDE, M.LONGITUDE, M.UPAZILA,M.DISTRICT
ORDER BY K.V372_CALLINGPARTYNUMBER,M.DISTRICT)Z
WHERE Z.V372_CALLINGPARTYNUMBER=A.MSISDN(+)
and Z.V372_CALLINGPARTYNUMBER=b.MSISDN(+)
union all
SELECT Z.V372_CALLINGPARTYNUMBER AS MSISDN, TO_CHAR(TO_DATE(Z.CALL_DATE,'YYYY-MM-DD HH24:MI:SS'),'YYYY-MM-DD HH24:MI:SS') AS TIMESTAMP,Z.LATITUDE, Z.LONGITUDE, Z.UPAZILA,Z.DISTRICT, A.NAME,round(V35_RATE_USAGE) AS DURATION, nvl(acount,0) as last3_day
FROM SAF_DATA@DWH05TODWH01 A,
(select MSISDN, count(acount) as acount
from(
select MSISDN, count(LU_DATE_KEY) as acount
from LAST_ACTIVITY_FCT 
where LU_DATE_KEY IN (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE BETWEEN TO_DATE (SYSDATE-5,'DD/MM/RRRR') AND TO_DATE (SYSDATE-2,'DD/MM/RRRR'))
group by MSISDN)
group by MSISDN)b,
(SELECT K.V372_CALLINGPARTYNUMBER,K.DATE_VALUE||K.V387_CHARGINGTIME_HOUR AS CALL_DATE,K.V35_RATE_USAGE, M.LATITUDE, M.LONGITUDE, M.UPAZILA,M.DISTRICT
    FROM ZONE_DIM@DWH05TODWH01 M,
        (SELECT V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER, TO_CHAR(B.DATE_VALUE,'RRRRMMDD') AS DATE_VALUE,V387_CHARGINGTIME_HOUR,V35_RATE_USAGE
        --FROM L3_VOICE A, DATE_DIM B
        FROM L2_VOICE_333@DWH05TODWH01 A, DATE_DIM B
        WHERE V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'DD/MM/RRRR'))
        --AND V373_CALLEDPARTYNUMBER ='333'
        AND V373_CALLEDPARTYNUMBER ='16263'
        AND V387_CHARGINGTIME_KEY=B.DATE_KEY
        GROUP BY V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER,B.DATE_VALUE,V387_CHARGINGTIME_HOUR,V35_RATE_USAGE)K
WHERE CGI=V381_CALLINGCELLID
GROUP BY  K.V372_CALLINGPARTYNUMBER,K.DATE_VALUE||K.V387_CHARGINGTIME_HOUR,K.V35_RATE_USAGE, M.LATITUDE, M.LONGITUDE, M.UPAZILA,M.DISTRICT
ORDER BY K.V372_CALLINGPARTYNUMBER,M.DISTRICT)Z
WHERE Z.V372_CALLINGPARTYNUMBER=A.MSISDN(+)
and Z.V372_CALLINGPARTYNUMBER=b.MSISDN(+);


