--
-- DATEDIFFERENCE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.DATEDIFFERENCE
(MSISDIN_NO, LAST_ACTIVITY_DATE_KEY, DATE_DIFF)
BEQUEATH DEFINER
AS 
SELECT A.MSISDIN_NO,
          A.LAST_ACTIVITY_DATE_KEY,
          LAST_ACTIVITY_DATE_KEY - FIRST_ACTIVE_DATE Date_Diff
     FROM ( (SELECT LAST_ACTIVITY_DATE_KEY, MSISDIN_NO
               FROM ACTIVEBASE
             ) A
           INNER JOIN
           (SELECT FIRST_ACTIVE_DATE, MSISDIN_NO
              FROM AGEONNETWROK
             ) B
              ON B.MSISDIN_NO = A.MSISDIN_NO);


