--
-- L3_LAST_CHURN_EXP  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.L3_LAST_CHURN_EXP
(CUSTOMER_ID, PREPAID, POSTPAID, FIRST_DATE_IN_NETWORK, LAST_ACTIVITY_DATE, 
 LAST_REVENUE_GENERATING_DATE, LAST_DATA_ACTIVE_DATE, LAST_VOICE_ACTIVE_DATE, LAST_VAS_ACTIVE_DATE, LAST_SMS_DATE)
BEQUEATH DEFINER
AS 
SELECT CUSTOMER_ID,PREPAID, POSTPAID, FIRST_DATE_IN_NETWORK, LAST_ACTIVITY_DATE, LAST_REVENUE_GENERATING_DATE, LAST_DATA_ACTIVE_DATE, LAST_VOICE_ACTIVE_DATE, LAST_VAS_ACTIVE_DATE, LAST_SMS_DATE
FROM L3_LAST_CHURN
WHERE  SUBSTR(MSISDN,3,3) IN ('015')
order by CUSTOMER_ID;


