--
-- LAST_REVENUE_GENERATING_DATE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.LAST_REVENUE_GENERATING_DATE
(MSISDN, DATE_VALUE)
BEQUEATH DEFINER
AS 
SELECT V. MSISDN , V.DATE_VALUE 
    FROM 
    (SELECT K.G372_CALLINGPARTYNUMBER  AS MSISDN ,K.G383_CHARGINGTIME_KEY AS CHARGINGTIME_KEY,K.G383_CHARGINGTIME_HOUR AS CHARGINGTIME_HOUR, Z.DATE_VALUE
        FROM DATE_DIM Z,
        (SELECT A.G372_CALLINGPARTYNUMBER,A.G383_CHARGINGTIME_KEY, A.G383_CHARGINGTIME_HOUR, RANK() OVER (PARTITION BY A.G372_CALLINGPARTYNUMBER ORDER BY A.G383_CHARGINGTIME_KEY DESC,A.G383_CHARGINGTIME_HOUR DESC) AS LAST_KEY
           FROM
            (SELECT   V.G372_CALLINGPARTYNUMBER,V.G383_CHARGINGTIME_KEY, v.G383_CHARGINGTIME_HOUR
            FROM L3_DATA V--, DATE_DIM D
            WHERE V.G41_DEBIT_AMOUNT <0
            --AND V.G383_CHARGINGTIME_KEY=D.DATE_KEY
            --AND D.DATE_VALUE BETWEEN SYSDATE-27 AND SYSDATE-26   
            GROUP BY G372_CALLINGPARTYNUMBER,G383_CHARGINGTIME_KEY,G383_CHARGINGTIME_HOUR
            )A
        )K 
    WHERE LAST_KEY=1
    AND K.G383_CHARGINGTIME_KEY=Z.DATE_KEY
    )V;


