--
-- LAST_ACTIVITY_DAT_VAS  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.LAST_ACTIVITY_DAT_VAS
(MSISDN, DATE_VALUE)
BEQUEATH DEFINER
AS 
SELECT KK.R375_CHARGINGPARTYNUMBER AS MSISDN, KK.DATE_VALUE
    FROM
    (SELECT V.R375_CHARGINGPARTYNUMBER,V.R377_CYCLEBEGINTIME_KEY,V.R377_CYCLEBEGINTIME_HOUR, Z.DATE_VALUE
    FROM DATE_DIM Z,
    (SELECT A.R375_CHARGINGPARTYNUMBER,A.R377_CYCLEBEGINTIME_KEY,A.R377_CYCLEBEGINTIME_HOUR,
    RANK() OVER (PARTITION BY A.R375_CHARGINGPARTYNUMBER ORDER BY A.R377_CYCLEBEGINTIME_KEY DESC,A.R377_CYCLEBEGINTIME_HOUR DESC) AS LAST_KEY
     FROM
    (SELECT R375_CHARGINGPARTYNUMBER,R377_CYCLEBEGINTIME_KEY,R377_CYCLEBEGINTIME_HOUR
    FROM L3_RECURRING A--, DATE_DIM B
    --WHERE A.R377_CYCLEBEGINTIME_KEY=B.DATE_KEY
    --AND B.DATE_VALUE BETWEEN SYSDATE-40 AND SYSDATE-26 
    GROUP BY R375_CHARGINGPARTYNUMBER,R377_CYCLEBEGINTIME_KEY,R377_CYCLEBEGINTIME_HOUR) A
    )V
    WHERE LAST_KEY=1
    AND V.R377_CYCLEBEGINTIME_KEY=Z.DATE_KEY)KK;


