--
-- LAST_SMS_DATE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.LAST_SMS_DATE
(MSISDN, DATE_VALUE)
BEQUEATH DEFINER
AS 
SELECT V.MSISDN , V.DATE_VALUE
FROM
(SELECT K.S372_CALLINGPARTYNUMBER  AS MSISDN ,K.S387_CHARGINGTIME_KEY AS CHARGINGTIME_KEY,K.S387_CHARGINGTIME_HOUR AS CHARGINGTIME_HOUR, Z.DATE_VALUE
            FROM DATE_DIM Z,
            (SELECT A.S372_CALLINGPARTYNUMBER,A.S387_CHARGINGTIME_KEY, A.S387_CHARGINGTIME_HOUR, RANK() OVER (PARTITION BY A.S372_CALLINGPARTYNUMBER ORDER BY A.S387_CHARGINGTIME_KEY DESC,A.S387_CHARGINGTIME_HOUR DESC) AS LAST_KEY
                   FROM
                    (SELECT   V.S372_CALLINGPARTYNUMBER,V.S387_CHARGINGTIME_KEY, S387_CHARGINGTIME_HOUR
                        FROM L3_SMS V--, DATE_DIM D
                        WHERE S378_SERVICEFLOW =1
                        --AND V.S387_CHARGINGTIME_KEY=D.DATE_KEY
                        --AND D.DATE_VALUE BETWEEN SYSDATE-27 AND SYSDATE-26   
                        GROUP BY S372_CALLINGPARTYNUMBER,S387_CHARGINGTIME_KEY,S387_CHARGINGTIME_HOUR)A
                        ) K 
    WHERE LAST_KEY=1
    AND K.S387_CHARGINGTIME_KEY=Z.DATE_KEY)V;


