--
-- LAST_VOICE_ACTIVE_DATE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.LAST_VOICE_ACTIVE_DATE
(MSISDN, DATE_VALUE)
BEQUEATH DEFINER
AS 
SELECT V. MSISDN , V.DATE_VALUE 
FROM
(SELECT K.V372_CALLINGPARTYNUMBER  AS MSISDN ,K.V387_CHARGINGTIME_KEY AS CHARGINGTIME_KEY,K.V387_CHARGINGTIME_HOUR AS CHARGINGTIME_HOUR, Z.DATE_VALUE
            FROM DATE_DIM Z,
            (SELECT A.V372_CALLINGPARTYNUMBER,A.V387_CHARGINGTIME_KEY, A.V387_CHARGINGTIME_HOUR, RANK() OVER (PARTITION BY A.V372_CALLINGPARTYNUMBER ORDER BY A.V387_CHARGINGTIME_KEY DESC,A.V387_CHARGINGTIME_HOUR DESC) AS LAST_KEY
                   FROM
                    (SELECT   V.V372_CALLINGPARTYNUMBER,V.V387_CHARGINGTIME_KEY, V387_CHARGINGTIME_HOUR
                        FROM L3_VOICE V--, DATE_DIM D
                        WHERE V378_SERVICEFLOW =1
                        --AND V.V387_CHARGINGTIME_KEY=D.DATE_KEY
                        --AND D.DATE_VALUE BETWEEN SYSDATE-27 AND SYSDATE-26   
                        GROUP BY V372_CALLINGPARTYNUMBER,V387_CHARGINGTIME_KEY,V387_CHARGINGTIME_HOUR)A
                        ) K 
    WHERE LAST_KEY=1
    AND K.V387_CHARGINGTIME_KEY=Z.DATE_KEY
    )V;


