--
-- LOST_SUBSCRIBERS  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.LOST_SUBSCRIBERS
(V397_MAINOFFERINGID, LOST_SUBSCRIBER_COUNT)
BEQUEATH DEFINER
AS 
select  B.V397_MAINOFFERINGID , count(A.MSISDIN_NO) LOST_SUBSCRIBER_COUNT from 
(select MSISDIN_NO, LAST_ACTIVITY_DATE_KEY from
Activebase
where LAST_ACTIVITY_DATE_KEY In  (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE < TO_DATE(SYSDATE-7,'DD/MM/RRRR')))A

INNER join

(select V372_CALLINGPARTYNUMBER, V397_MAINOFFERINGID from L3_voice 
where V387_CHARGINGTIME_KEY In  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
union

select G372_CALLINGPARTYNUMBER, G401_MAINOFFERINGID from L3_DATA
where G383_CHARGINGTIME_KEY In  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
union

select S22_PRI_IDENTITY, S395_MAINOFFERINGID from L3_SMS
where S387_CHARGINGTIME_KEY In  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
union

select R375_CHARGINGPARTYNUMBER, R373_MAINOFFERINGID from L3_Recurring
where R377_CYCLEBEGINTIME_KEY In  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
union

select RE6_PRI_IDENTITY, RE489_MAINOFFERINGID from L3_Recharge
where RE30_ENTRY_DATE_KEY In  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
)B on B.V372_CALLINGPARTYNUMBER=A.MSISDIN_NO
group by B.V397_MAINOFFERINGID;


