--
-- F_CALLER_COUNT  (Function) 
--
CREATE OR REPLACE FUNCTION DWH_USER.F_CALLER_COUNT RETURN VARCHAR2 IS
    CALLER_COUNT VARCHAR2(100);
BEGIN
    --Function created by Tareq-10/06/2020 fro mail daily caller count ---
    SELECT 'Daily_Active_MSISDN'||'_'||TO_CHAR(SYSDATE-2, 'DD_FMMonthYYYY' )||': '||CALLER_COUNT into  CALLER_COUNT
    FROM
    (SELECT COUNT(DISTINCT MSISDN) AS  CALLER_COUNT
    FROM LAST_ACTIVITY_FCT
    WHERE ETL_DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-2))
    AND LU_DATE_KEY=(SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-2))
    );
   
        
    RETURN CALLER_COUNT;
   
END;
/

