--
-- P_ALL_MSISDN_INSERT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_ALL_MSISDN_INSERT IS
BEGIN
    INSERT INTO MSISDN_TYPE
    SELECT * FROM MSISDN_TYPE@DWH05TODWH01;
    COMMIT;

    --================UPDATE PAYTYPE = 0 ==
    INSERT INTO MSISDN_TYPE
    SELECT /*+ PARALLEL(A,16) */ A.A5_PRI_IDENTITY, B.PAY_TYPE_ID, B.PAY_TYPE_NAME
    FROM L3_ADJUSTMENT A, PAYTYPE_DIM B
    WHERE A.A463_PAYTYPE = B.PAY_TYPE_ID
    AND A.A5_PRI_IDENTITY NOT IN (SELECT RE6_PRI_IDENTITY FROM MSISDN_TYPE)
    GROUP BY A.A5_PRI_IDENTITY, B.PAY_TYPE_ID, B.PAY_TYPE_NAME ;
    COMMIT;

    INSERT INTO MSISDN_TYPE
    SELECT /*+ PARALLEL(A,16) */ A.CO22_PRI_IDENTITY, B.PAY_TYPE_ID, B.PAY_TYPE_NAME
    FROM L3_CONTENT A, PAYTYPE_DIM B
    WHERE A.CO410_PAYTYPE = B.PAY_TYPE_ID
    AND A.CO22_PRI_IDENTITY NOT IN (SELECT RE6_PRI_IDENTITY FROM MSISDN_TYPE)
    GROUP BY A.CO22_PRI_IDENTITY, B.PAY_TYPE_ID, B.PAY_TYPE_NAME;
    COMMIT;

    INSERT INTO MSISDN_TYPE
    SELECT /*+ PARALLEL(A,16) */ A.M372_CALLINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME
    FROM L3_MANAGEMENT A, PAYTYPE_DIM B
    WHERE A.M377_PAYTYPE = B.PAY_TYPE_ID
    AND A.M372_CALLINGPARTYNUMBER NOT IN (SELECT RE6_PRI_IDENTITY FROM MSISDN_TYPE)
    GROUP BY A.M372_CALLINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME;
    COMMIT;

    INSERT INTO MSISDN_TYPE
    SELECT /*+ PARALLEL(A,16) */ A.R375_CHARGINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME
    FROM L3_RECURRING A, PAYTYPE_DIM B
    WHERE A.R374_PAYTYPE = B.PAY_TYPE_ID
    AND A.R375_CHARGINGPARTYNUMBER NOT IN (SELECT  RE6_PRI_IDENTITY FROM MSISDN_TYPE)
    GROUP BY A.R375_CHARGINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME;
    COMMIT;

    INSERT INTO MSISDN_TYPE
    SELECT /*+ PARALLEL(A,16) */ A.S372_CALLINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME
    FROM L3_SMS A, PAYTYPE_DIM B
    WHERE A.S398_PAYTYPE = B.PAY_TYPE_ID
    AND A.S378_SERVICEFLOW = 1
    AND A.S372_CALLINGPARTYNUMBER NOT IN (SELECT RE6_PRI_IDENTITY FROM MSISDN_TYPE)
    GROUP BY A.S372_CALLINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME;
    COMMIT;

    INSERT INTO MSISDN_TYPE
    SELECT /*+ PARALLEL(A,16) */ A.T6_PRI_IDENTITY, B.PAY_TYPE_ID, B.PAY_TYPE_NAME
    FROM L3_TRANSFER A, PAYTYPE_DIM B
    WHERE A.T459_PAYTYPE = B.PAY_TYPE_ID
    AND A.T6_PRI_IDENTITY NOT IN (SELECT RE6_PRI_IDENTITY FROM MSISDN_TYPE)
    GROUP BY A.T6_PRI_IDENTITY, B.PAY_TYPE_ID, B.PAY_TYPE_NAME;
    COMMIT;

    INSERT INTO MSISDN_TYPE
    SELECT /*+ PARALLEL(A,16) */ A.V372_CALLINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME
    FROM L3_VOICE A, PAYTYPE_DIM B
    WHERE A.V400_PAYTYPE = B.PAY_TYPE_ID
    AND A.V378_SERVICEFLOW = 1
    AND A.V372_CALLINGPARTYNUMBER NOT IN (SELECT RE6_PRI_IDENTITY FROM MSISDN_TYPE)
    GROUP BY A.V372_CALLINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME;
    COMMIT;
END;
/

