--
-- P_LAST_ACTIVITY_FCT_LD_PART2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_LAST_ACTIVITY_FCT_LD_PART2 IS
    VDATE_KEY               NUMBER;
    VDATE DATE :=TO_DATE(TO_DATE( SYSDATE-1),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    

--=================================LU_DATE_KEY,LU_TIME_KEY===============--

    MERGE INTO LAST_ACTIVITY_FCT_LD A
    USING (SELECT X.MSISDN AS MSISDN, X.DATE_KEY AS DATE_KEY, X.TIME_KEY AS TIME_KEY 
    FROM
    (SELECT Z.MSISDN, Z.DATE_KEY,Z.TIME_KEY,RANK() OVER (PARTITION BY Z.MSISDN ORDER BY Z.DATE_KEY DESC,Z.TIME_KEY DESC) LAST_KEY
    FROM
    (SELECT A.MSISDN, A.DATE_KEY,A.TIME_KEY
    FROM
    (SELECT MSISDN,
    NVL(LU_MOC_DATE_KEY,0) AS DATE_KEY ,
    NVL(LU_MOC_TIME_KEY,0) AS TIME_KEY
    FROM 
    LAST_ACTIVITY_FCT_LD
    UNION ALL
    SELECT MSISDN,
    NVL(LU_ON_NET_MOC_DATE_KEY,0) AS DATE_KEY ,
    NVL(LU_ON_NET_MOC_TIME_KEY,0) AS TIME_KEY
    FROM 
    LAST_ACTIVITY_FCT_LD
    UNION ALL
    SELECT MSISDN,
    NVL(LU_OFF_NET_MOC_DATE_KEY,0) AS DATE_KEY ,
    NVL(LU_OFF_NET_MOC_TIME_KEY,0) AS TIME_KEY
    FROM 
    LAST_ACTIVITY_FCT_LD
    UNION ALL
    SELECT MSISDN,
    NVL(LU_MOSMS_DATE_KEY,0) AS DATE_KEY ,
    NVL(LU_MOSMS_TIME_KEY,0) AS TIME_KEY
    FROM 
    LAST_ACTIVITY_FCT_LD
    UNION ALL
    SELECT MSISDN,
    NVL(LU_GPRS_DATE_KEY,0) AS DATE_KEY ,
    NVL(LU_GPRS_TIME_KEY,0) AS TIME_KEY
    FROM 
    LAST_ACTIVITY_FCT_LD
    UNION ALL
    SELECT MSISDN,
    NVL(LR_DATE_KEY,0) AS DATE_KEY ,
    NVL(LR_TIME_KEY,0) AS TIME_KEY
    FROM 
    LAST_ACTIVITY_FCT_LD)A
    GROUP BY A.MSISDN, A.DATE_KEY,A.TIME_KEY
    ORDER BY A.MSISDN DESC, A.DATE_KEY DESC, A.TIME_KEY DESC)Z
    )X
    WHERE X.LAST_KEY=1)T
    ON (A.MSISDN = T.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LU_DATE_KEY=T.DATE_KEY,
           A.LU_TIME_KEY =T.TIME_KEY;
COMMIT;
END;
/

