--
-- P_LAST_ACTIVITY_FCT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_LAST_ACTIVITY_FCT IS
VDATE_KEY               NUMBER;
BEGIN
SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE TO_CHAR(DATE_VALUE, 'DD/MM/YYYY') = TO_CHAR(SYSDATE-1, 'DD/MM/RRRR');
    
    INSERT INTO LAST_ACTIVITY_FCT
    SELECT/*+ PARALLEL(LAST_ACTIVITY_FCT,16) */ 
    MSISDN, 
    VDATE_KEY,
    SNAPSHOT_DATE_KEY,
    BILLING_ACCOUNT_KEY, 
    CUSTOMER_ACCOUNT_KEY, 
    SUBSCRIPTION_KEY, 
    LU_DATE_KEY, 
    LU_TIME_KEY, 
    LU_PRODUCT_KEY, 
    LU_USAGE_TYPE_KEY, 
    LU_LOCATION_KEY, 
    LU_CALL_CATEGORY_KEY, 
    LU_GEOGRAPHY_KEY, 
    LU_ACTUAL_DURATION, 
    LU_AIR_CHARGE, 
    LU_MOC_DATE_KEY, 
    LU_MOC_TIME_KEY, 
    LU_MOC_PRODUCT_KEY, 
    LU_MOC_GEOGRAPHY_KEY, 
    LU_MOC_ACTUAL_DURATION, 
    LU_MOC_AIR_CHARGE, 
    LU_MTC_DATE_KEY, 
    LU_MTC_TIME_KEY, 
    LU_MTC_PRODUCT_KEY, 
    LU_MTC_GEOGRAPHY_KEY, 
    LU_MTC_ACTUAL_DURATION, 
    LU_ON_NET_MOC_DATE_KEY, 
    LU_ON_NET_MOC_TIME_KEY, 
    LU_ON_NET_MOC_PRODUCT_KEY, 
    LU_ON_NET_MOC_ACTUAL_DURATION, 
    LU_ON_NET_MOC_AIR_CHARGE, 
    LU_OFF_NET_MOC_DATE_KEY, 
    LU_OFF_NET_MOC_TIME_KEY, 
    LU_OFF_NET_MOC_PRODUCT_KEY, 
    LU_OFF_NET_MOC_LOCATION_KEY, 
    LU_OFF_NET_MOC_ACTUAL_DURATION, 
    LU_OFF_NET_MOC_AIR_CHARGE, 
    LU_MOSMS_DATE_KEY, 
    LU_MOSMS_TIME_KEY, 
    LU_MOSMS_PRODUCT_KEY, 
    LU_MOSMS_GEOGRAPHY_KEY, 
    LU_MOSMS_LOCATION_KEY, 
    LU_MOSMS_AIR_CHARGE, 
    LU_MTSMS_DATE_KEY, 
    LU_MTSMS_TIME_KEY, 
    LU_MTSMS_GEOGRAPHY_KEY, 
    LU_MTSMS_LOCATION_KEY, 
    LU_GPRS_DATE_KEY, 
    LU_GPRS_TIME_KEY,
    LU_GPRS_PRODUCT_KEY, 
    LU_GPRS_GEOGRAPHY_KEY, 
    LU_GPRS_DATA_SIZE, 
    LR_DATE_KEY, 
    LR_TIME_KEY, 
    LR_PRODUCT_KEY, 
    LR_RECHARGE_TYPE_KEY, 
    LR_MAIN_ACCOUNT_AMOUNT, 
    LR_MAIN_ACCOUNT_BALANCE, 
    LR_VOUCHER_DATE_KEY, 
    LR_VOUCHER_TIME_KEY, 
    LR_VOUCHER_PRODUCT_KEY, 
    LR_VOUCHER_MAIN_ACCOUNT_AMOUNT, 
    LR_EV_DATE_KEY, LR_EV_TIME_KEY, 
    LR_EV_PRODUCT_KEY, 
    LR_EV_MAIN_ACCOUNT_AMOUNT, 
    LB_DATE_KEY, 
    LB_PRODUCT_KEY, 
    LB_IN_KEY, 
    LB_EXPIRY_DATE_KEY, 
    LB_CLOSING_BALANCE, 
    LB_OPENING_BALANCE, 
    LI_CALL_DURATION, 
    LU_MTSMS_PRODUCT_KEY
    FROM LAST_ACTIVITY_FCT_LD
    COMMIT;
END;
/

