--
-- P_SUBSCRIPTION_DIM_BKP  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_SUBSCRIPTION_DIM_bkp IS

BEGIN

/*
      INSERT INTO SUBSCRIPTION_DIM_LD(SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT 
    MASKING_ID.NEXTVAL,
    RE6_PRI_IDENTITY,
    TO_DATE(SYSDATE-1,'DD/MM/RRRR'), 
    PAY_TYPE_NAME,
    TO_DATE(SYSDATE-1,'DD/MM/RRRR'),
    TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM MSISDN_TYPE 
    WHERE RE6_PRI_IDENTITY NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD);
    COMMIT;
*/
    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(A,16) */ MASKING_ID.NEXTVAL, A.A5_PRI_IDENTITY, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), A.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM (SELECT A.A5_PRI_IDENTITY,  B.PAY_TYPE_NAME
    FROM L3_ADJUSTMENT A, PAYTYPE_DIM B
    WHERE A.A463_PAYTYPE = B.PAY_TYPE_ID
    AND A.A5_PRI_IDENTITY NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.A5_PRI_IDENTITY, B.PAY_TYPE_NAME) A;
    COMMIT;

    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(AB,16) */ MASKING_ID.NEXTVAL, AB.CO22_PRI_IDENTITY, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), AB.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM(SELECT A.CO22_PRI_IDENTITY, B.PAY_TYPE_NAME
    FROM L3_CONTENT A, PAYTYPE_DIM B
    WHERE A.CO410_PAYTYPE = B.PAY_TYPE_ID
    AND A.CO22_PRI_IDENTITY NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.CO22_PRI_IDENTITY, B.PAY_TYPE_NAME)AB;
    COMMIT;

    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(AC,16) */ MASKING_ID.NEXTVAL, AC.M372_CALLINGPARTYNUMBER, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), AC.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM(SELECT A.M372_CALLINGPARTYNUMBER, B.PAY_TYPE_NAME
    FROM L3_MANAGEMENT A, PAYTYPE_DIM B
    WHERE A.M377_PAYTYPE = B.PAY_TYPE_ID
    AND A.M372_CALLINGPARTYNUMBER NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.M372_CALLINGPARTYNUMBER, B.PAY_TYPE_NAME)AC;
    COMMIT;

    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(AD,16) */ MASKING_ID.NEXTVAL, AD.R375_CHARGINGPARTYNUMBER, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), AD.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM(SELECT A.R375_CHARGINGPARTYNUMBER, B.PAY_TYPE_NAME
    FROM L3_RECURRING A, PAYTYPE_DIM B
    WHERE A.R374_PAYTYPE = B.PAY_TYPE_ID
    AND A.R375_CHARGINGPARTYNUMBER NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.R375_CHARGINGPARTYNUMBER, B.PAY_TYPE_NAME)AD;
    COMMIT;
    
    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(AE,16) */ MASKING_ID.NEXTVAL, AE.S372_CALLINGPARTYNUMBER, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), AE.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM( SELECT A.S372_CALLINGPARTYNUMBER, B.PAY_TYPE_NAME
    FROM L3_SMS A, PAYTYPE_DIM B
    WHERE A.S398_PAYTYPE = B.PAY_TYPE_ID
    AND A.S378_SERVICEFLOW = 1
    AND A.S372_CALLINGPARTYNUMBER NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.S372_CALLINGPARTYNUMBER, B.PAY_TYPE_NAME)AE;
    COMMIT;
    
    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(AF,16) */ MASKING_ID.NEXTVAL, AF.T6_PRI_IDENTITY, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), AF.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM(SELECT A.T6_PRI_IDENTITY, B.PAY_TYPE_NAME
    FROM L3_TRANSFER A, PAYTYPE_DIM B
    WHERE A.T459_PAYTYPE = B.PAY_TYPE_ID
    AND A.T6_PRI_IDENTITY NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.T6_PRI_IDENTITY,  B.PAY_TYPE_NAME)AF;
    COMMIT;
    
    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(AG,16) */ MASKING_ID.NEXTVAL, AG.V372_CALLINGPARTYNUMBER, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), AG.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM(SELECT A.V372_CALLINGPARTYNUMBER,  B.PAY_TYPE_NAME
    FROM L3_VOICE A, PAYTYPE_DIM B
    WHERE A.V400_PAYTYPE = B.PAY_TYPE_ID
    AND A.V378_SERVICEFLOW = 1
    AND A.V372_CALLINGPARTYNUMBER NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.V372_CALLINGPARTYNUMBER,  B.PAY_TYPE_NAME)AG;
    COMMIT;
    
    
    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(AH,16) */ MASKING_ID.NEXTVAL, AH.RE6_PRI_IDENTITY, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), AH.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM(SELECT A.RE6_PRI_IDENTITY,  B.PAY_TYPE_NAME
    FROM L3_RECHARGE A, PAYTYPE_DIM B
    WHERE A.RE490_PAYTYPE = B.PAY_TYPE_ID
    AND A.RE6_PRI_IDENTITY NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.RE6_PRI_IDENTITY,  B.PAY_TYPE_NAME)AH;
    COMMIT;
    
    INSERT INTO SUBSCRIPTION_DIM_LD (SUBSCRIPTION_KEY, SERVICE_NUMBER, START_DATE, SERVICE_TYPE, FIRST_CALL_DATE, SCD_START_DATE)
    SELECT /*+ PARALLEL(AI,16) */ MASKING_ID.NEXTVAL, AI.G372_CALLINGPARTYNUMBER, TO_DATE(SYSDATE-1,'DD/MM/RRRR'), AI.PAY_TYPE_NAME,TO_DATE(SYSDATE-1,'DD/MM/RRRR'),TO_DATE(SYSDATE-1,'DD/MM/RRRR')
    FROM( SELECT A.G372_CALLINGPARTYNUMBER, B.PAY_TYPE_NAME
    FROM L3_DATA A, PAYTYPE_DIM B
    WHERE A.G403_PAYTYPE = B.PAY_TYPE_ID
    AND A.G372_CALLINGPARTYNUMBER NOT IN (SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM_LD)
    GROUP BY A.G372_CALLINGPARTYNUMBER, B.PAY_TYPE_ID, B.PAY_TYPE_NAME)AI ;
    COMMIT;
    
    
  ---------------------  SUBSCRIPTION_DIM Table insertscript-----------------
    INSERT INTO SUBSCRIPTION_DIM 
    SELECT /*+ PARALLEL(SUBSCRIPTION_DIM_LD,16) */ 
    SUBSCRIPTION_KEY, 
    SERVICE_NUMBER, 
    START_DATE, 
    END_DATE, 
    SERVICE_TYPE, 
    SUBSCRIPTION_PRICE, 
    CREDIT_LIMIT_THRESHOLD, 
    FIRST_CALL_DATE, 
    SCD_START_DATE, 
    SCD_END_DATE, 
    ETL_BILLING_AC_KEY, 
    NAME_BY_SERVICE_NUMBER, 
    REUSED_FLAG, 
    BASE_TYPE
    FROM SUBSCRIPTION_DIM_LD
    WHERE SERVICE_NUMBER NOT IN ( SELECT SERVICE_NUMBER FROM SUBSCRIPTION_DIM);
    COMMIT;

END;
/

