--
-- P_UPSELL_LD_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_UPSELL_LD_MANUAL (P_DATE VARCHAR2) IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TRUNC(DATE_VALUE) = TRUNC(TO_DATE(P_DATE,'RRRRMMDD'));


    
DELETE UPSELL_LD WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO UPSELL_LD


SELECT A.R375_CHARGINGPARTYNUMBER MSISDN,COALESCE (VOICE_OFFER_COUNT, 0) VOICE_OFFER_COUNT,COALESCE (VOICE_OFFER_REVNUE, 0) VOICE_OFFER_REVNUE,
       COALESCE (DATA_OFFER_COUNT, 0) DATA_OFFER_COUNT, COALESCE (DATA_OFFER_REVENUE, 0) DATA_OFFER_REVENUE,
       COALESCE (SMS_OFFER_COUNT, 0) SMS_OFFER_COUNT,COALESCE (SMS_OFFER_REVENUE, 0) SMS_OFFER_REVENUE, COALESCE (RECHARGE_COUNT,0) RECHARGE_COUNT, COALESCE (RECHARGE_AMOUNT,0) RECHARGE_AMOUNT, VDATE_KEY
FROM 
(SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY = VDATE_KEY
GROUP BY R375_CHARGINGPARTYNUMBER
)A
LEFT OUTER JOIN



(SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER,COUNT(*) VOICE_OFFER_COUNT,SUM (R41_DEBIT_AMOUNT) VOICE_OFFER_REVNUE
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY = VDATE_KEY
                                                  
      AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Voice')

GROUP BY R375_CHARGINGPARTYNUMBER
)B ON A.R375_CHARGINGPARTYNUMBER=B.R375_CHARGINGPARTYNUMBER
LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER,COUNT(*) DATA_OFFER_COUNT , SUM (R41_DEBIT_AMOUNT) DATA_OFFER_REVENUE
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY = VDATE_KEY
                                                  
      AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Data')

GROUP BY R375_CHARGINGPARTYNUMBER
)C ON A.R375_CHARGINGPARTYNUMBER=C.R375_CHARGINGPARTYNUMBER
LEFT OUTER JOIN



(SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER,COUNT(*) SMS_OFFER_COUNT, SUM (R41_DEBIT_AMOUNT) SMS_OFFER_REVENUE
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY = VDATE_KEY
                                                  
      AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='SMS')

GROUP BY R375_CHARGINGPARTYNUMBER
)D ON A.R375_CHARGINGPARTYNUMBER=D.R375_CHARGINGPARTYNUMBER
LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,15)*/ RE6_PRI_IDENTITY,COUNT(*) RECHARGE_COUNT, SUM (RE3_RECHARGE_AMT) RECHARGE_AMOUNT
FROM L3_RECHARGE P
WHERE RE30_ENTRY_DATE_KEY = VDATE_KEY

GROUP BY RE6_PRI_IDENTITY
)E ON A.R375_CHARGINGPARTYNUMBER=E.RE6_PRI_IDENTITY
;
    COMMIT;
END;
/

