--
-- PRO_NEW_MGMT_DBOARD9_ARPU  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.PRO_NEW_MGMT_DBOARD9_ARPU IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE NEW_MGMT_DBOARD9_ARPU WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO NEW_MGMT_DBOARD9_ARPU


SELECT U.TOTAL_REVENUE/ACTIVE_SUBSCRIBER_COUNT ARPU, VDATE_KEY
FROM

(SELECT  COALESCE (A.VOICE_REVENUE, 0)
        + COALESCE (B.DATA_REVENUE, 0)
        + COALESCE (C.VAS_REVENUE, 0)
        + COALESCE (D.SMS_REVENUE, 0)
        + COALESCE (E.CONTENT_REVENUE, 0)
        + COALESCE (F.ADJUSTMENT_REVENUE, 0)
        TOTAL_REVENUE 
        FROM
        (SELECT /*+PARALLEL(P,8)*/ SUM(V41_DEBIT_AMOUNT) VOICE_REVENUE FROM L3_VOICE P
        WHERE V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) ) A,
        (SELECT /*+PARALLEL(Q,8)*/ SUM(G41_DEBIT_AMOUNT) DATA_REVENUE FROM L3_DATA Q
        WHERE G383_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) )B,
        (SELECT /*+PARALLEL(R,8)*/ SUM(R41_DEBIT_AMOUNT) VAS_REVENUE FROM L3_RECURRING R
        WHERE R377_CYCLEBEGINTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) )C,
        (SELECT /*+PARALLEL(S,8)*/ SUM(S41_DEBIT_AMOUNT) SMS_REVENUE FROM L3_SMS S
        WHERE S387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) )D,
        (SELECT /*+PARALLEL(T,8)*/ SUM(CO41_DEBIT_AMOUNT) CONTENT_REVENUE FROM L3_CONTENT T
        WHERE CO402_STARTTIMEOFBILLCYL_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) )E,
        (SELECT /*+PARALLEL(W,8)*/ SUM(A30_DEBIT_AMOUNT) ADJUSTMENT_REVENUE FROM L3_ADJUSTMENT W
         WHERE A22_ENTRY_DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))  )F
)U,
(
SELECT  COUNT(MSISDN)ACTIVE_SUBSCRIBER_COUNT
FROM
(SELECT /*+PARALLEL(P,8)*/  MSISDN FROM LAST_ACTIVITY_FCT P
WHERE LU_DATE_KEY  = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
GROUP BY MSISDN
)
)V;

    COMMIT;
END;
/

