--
-- PRO_DITRICT_WISE_VOICE_REVENUE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.PRO_DITRICT_WISE_VOICE_REVENUE IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE DITRICT_WISE_VOICE_REVENUE WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO DITRICT_WISE_VOICE_REVENUE


select AA.DISTRICT,VOICE_REVENUE,VOICE_USAGE,VOICE_ACTIVE_SUBSCRIBERS,VOICE_REVENUE/VOICE_USAGE AVG_CALL_RATES,INCOMING_CALL_COUNTing,
        OUTGOING_CALL_COUNTING,INCOMING_CALL_REVENUE,OUTGOING_CALL_REVENUE,YOUTH_VOICE_REVENUE,AGAMI_VOICE_REVENUE,BORNOMALA_VOICE_REVENUE,
        SAGOTOM_VOICE_REVENUE,OPORAJITA_VOICE_REVENUE,MAYER_HASI_VOICE_REVENUE,CORPORATE_VOICE_REVENUE,OTHER_PACKAGES_VOICE_REVENUE,VDATE_KEY


from 
(select INITCAP(DISTRICT) DISTRICT, sum(VOICE_REVENUE) VOICE_REVENUE ,sum(VOICE_USAGE) VOICE_USAGE ,sum(INCOMING_CALL_COUNTing) INCOMING_CALL_COUNTing ,
       sum(OUTGOING_CALL_COUNTING) OUTGOING_CALL_COUNTING ,sum(INCOMING_CALL_REVENUE) INCOMING_CALL_REVENUE, sum(OUTGOING_CALL_REVENUE) OUTGOING_CALL_REVENUE,
       sum(YOUTH_VOICE_REVENUE) YOUTH_VOICE_REVENUE, sum(AGAMI_VOICE_REVENUE) AGAMI_VOICE_REVENUE, sum(BORNOMALA_VOICE_REVENUE) BORNOMALA_VOICE_REVENUE,
       sum(SAGOTOM_VOICE_REVENUE) SAGOTOM_VOICE_REVENUE, sum(OPORAJITA_VOICE_REVENUE) OPORAJITA_VOICE_REVENUE, sum(MAYER_HASI_VOICE_REVENUE) MAYER_HASI_VOICE_REVENUE,
       sum(CORPORATE_VOICE_REVENUE) CORPORATE_VOICE_REVENUE, sum(OTHER_PACKAGES_VOICE_REVENUE) OTHER_PACKAGES_VOICE_REVENUE

from zone_dim,

(select A.V381_CALLINGCELLID,B.VOICE_REVENUE,COALESCE (C.MO_USAGE_MINUTES, 0)+ COALESCE (D.MT_USAGE_MINUTES, 0) VOICE_USAGE, F.INCOMING_CALL_COUNTing,
       G.OUTGOING_CALL_COUNTING,H.INCOMING_CALL_REVENUE,I.OUTGOING_CALL_REVENUE,J.YOUTH_VOICE_REVENUE,K.AGAMI_VOICE_REVENUE,L.BORNOMALA_VOICE_REVENUE,
       M.SAGOTOM_VOICE_REVENUE,N.OPORAJITA_VOICE_REVENUE,O.MAYER_HASI_VOICE_REVENUE,A1.CORPORATE_VOICE_REVENUE,B1.OTHER_PACKAGES_VOICE_REVENUE

  from 
((SELECT /*+PARALLEL(P,8)*/ V381_CALLINGCELLID FROM L3_VOICE P
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V381_CALLINGCELLID 
)

union

(SELECT /*+PARALLEL(Q,8)*/ V383_CALLEDCELLID FROM L3_VOICE Q
 WHERE V378_SERVICEFLOW=2 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V383_CALLEDCELLID     
))A

left outer join

(SELECT /*+PARALLEL(R,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) VOICE_REVENUE FROM L3_VOICE R
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V381_CALLINGCELLID     
)B on A.V381_CALLINGCELLID=B.V381_CALLINGCELLID

LEFT OUTER JOIN

(SELECT /*+PARALLEL(S,8)*/ V381_CALLINGCELLID ,sum(V35_RATE_USAGE)/60 MO_USAGE_MINUTES FROM L3_VOICE S
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V381_CALLINGCELLID 
) C on A.V381_CALLINGCELLID=C.V381_CALLINGCELLID

left outer join

(SELECT /*+PARALLEL(T,8)*/ V383_CALLEDCELLID ,sum(V35_RATE_USAGE)/60 MT_USAGE_MINUTES FROM L3_VOICE T
 WHERE V378_SERVICEFLOW=2 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V383_CALLEDCELLID     
)D on A.V381_CALLINGCELLID=D.V383_CALLEDCELLID




left outer join

(SELECT /*+PARALLEL(W,8)*/ V383_CALLEDCELLID ,count(V373_CALLEDPARTYNUMBER) INCOMING_CALL_COUNTing FROM L3_VOICE W
 WHERE V378_SERVICEFLOW=2 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V383_CALLEDCELLID  
) F on A.V381_CALLINGCELLID=F.V383_CALLEDCELLID

left outer join

(SELECT /*+PARALLEL(X,8)*/ V381_CALLINGCELLID ,count(V372_CALLINGPARTYNUMBER) OUTGOING_CALL_COUNTING FROM L3_VOICE X
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V381_CALLINGCELLID  
) G on A.V381_CALLINGCELLID=G.V381_CALLINGCELLID

Left outer join 

(SELECT /*+PARALLEL(Y,8)*/ V383_CALLEDCELLID,SUM(V41_DEBIT_AMOUNT) INCOMING_CALL_REVENUE FROM L3_VOICE Y
 WHERE V378_SERVICEFLOW=2 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V383_CALLEDCELLID     
) H on A.V381_CALLINGCELLID=H.V383_CALLEDCELLID

left outer join


(SELECT /*+PARALLEL(Z,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) OUTGOING_CALL_REVENUE FROM L3_VOICE Z
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V381_CALLINGCELLID     
)I on A.V381_CALLINGCELLID=I.V381_CALLINGCELLID

left outer join

(SELECT /*+PARALLEL(P1,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) YOUTH_VOICE_REVENUE FROM L3_VOICE P1
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 and V397_MAINOFFERINGID in ( 400014,400016,400017,300050)
 GROUP BY V381_CALLINGCELLID     
)J on A.V381_CALLINGCELLID=J.V381_CALLINGCELLID

left outer join

(SELECT /*+PARALLEL(Q1,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) AGAMI_VOICE_REVENUE FROM L3_VOICE Q1
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 and V397_MAINOFFERINGID in (300033,400012)
 GROUP BY V381_CALLINGCELLID     
)K on A.V381_CALLINGCELLID=K.V381_CALLINGCELLID

left outer join


(SELECT /*+PARALLEL(R1,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) BORNOMALA_VOICE_REVENUE FROM L3_VOICE R1
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 and V397_MAINOFFERINGID in (300034,400015)
 GROUP BY V381_CALLINGCELLID     
)L on A.V381_CALLINGCELLID=L.V381_CALLINGCELLID

left outer join


(SELECT /*+PARALLEL(S1,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) SAGOTOM_VOICE_REVENUE FROM L3_VOICE S1
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 and V397_MAINOFFERINGID =479662
 GROUP BY V381_CALLINGCELLID     
)M on A.V381_CALLINGCELLID=M.V381_CALLINGCELLID

left outer join

(SELECT /*+PARALLEL(T1,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) OPORAJITA_VOICE_REVENUE FROM L3_VOICE T1
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 and V397_MAINOFFERINGID =400019
 GROUP BY V381_CALLINGCELLID     
)N on A.V381_CALLINGCELLID=N.V381_CALLINGCELLID

left outer join

(SELECT /*+PARALLEL(U1,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) MAYER_HASI_VOICE_REVENUE FROM L3_VOICE U1
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 AND V397_MAINOFFERINGID =400018
 GROUP BY V381_CALLINGCELLID     
)O on A.V381_CALLINGCELLID=O.V381_CALLINGCELLID


left outer join

(SELECT /*+PARALLEL(V1,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) CORPORATE_VOICE_REVENUE FROM L3_VOICE V1 
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 and V397_MAINOFFERINGID in ( 200002,300022,300042,449066,449073,410010,410008,410009,449103,200001)
 GROUP BY V381_CALLINGCELLID     
)A1 on A.V381_CALLINGCELLID=A1.V381_CALLINGCELLID

left outer join

(SELECT /*+PARALLEL(W1,8)*/ V381_CALLINGCELLID,SUM(V41_DEBIT_AMOUNT) OTHER_PACKAGES_VOICE_REVENUE FROM L3_VOICE W1
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 and V397_MAINOFFERINGID NOT in ( 400014,400016,400017,300050,300033,400012,300034,400015,479662,400019,400018,200002,300022,300042,449066,449073,410010,410008,410009,449103,200001)
 GROUP BY V381_CALLINGCELLID     
)B1 on A.V381_CALLINGCELLID=B1.V381_CALLINGCELLID
)
where CGI=V381_CALLINGCELLID

Group by INITCAP(DISTRICT)
) AA


left outer join

(select DISTRICT ,count(V372_CALLINGPARTYNUMBER) VOICE_ACTIVE_SUBSCRIBERS
from
(select INITCAP(DISTRICT) DISTRICT  ,V372_CALLINGPARTYNUMBER from zone_dim,

(SELECT V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER 
FROM
((SELECT /*+PARALLEL(U,8)*/ V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER FROM L3_VOICE U
 WHERE V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER
)

UNION

(SELECT /*+PARALLEL(V,8)*/ V383_CALLEDCELLID ,V373_CALLEDPARTYNUMBER FROM L3_VOICE V
 WHERE V378_SERVICEFLOW=2 AND
 V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
 GROUP BY V383_CALLEDCELLID,V373_CALLEDPARTYNUMBER     
))
)
where CGI=V381_CALLINGCELLID
Group by INITCAP(DISTRICT) ,V372_CALLINGPARTYNUMBER
)
group by DISTRICT

)BB on AA.DISTRICT=BB.DISTRICT;

    COMMIT;
END;
/

