--
-- PRO_NEW_MGMT_DBOARD6_DIFF_REVS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.PRO_NEW_MGMT_DBOARD6_DIFF_REVS IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE NEW_MGMT_DBOARD6_DIFF_REVS WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO NEW_MGMT_DBOARD6_DIFF_REVS


SELECT A.VOICE_REVENUE,
        B.DATA_REVENUE,
        C.VAS_REVENUE,
        D.SMS_REVENUE,
        E.CONTENT_REVENUE,
        F.ADJUSTMENT_REVENUE,
        VDATE_KEY
        
        FROM
        (SELECT /*+PARALLEL(P,8)*/ SUM(V41_DEBIT_AMOUNT)/1000 VOICE_REVENUE FROM L3_VOICE P
        WHERE V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) ) A,
        (SELECT /*+PARALLEL(Q,8)*/ SUM(G41_DEBIT_AMOUNT)/1000 DATA_REVENUE FROM L3_DATA Q
        WHERE G383_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) )B,
        (SELECT /*+PARALLEL(R,8)*/ SUM(R41_DEBIT_AMOUNT)/1000 VAS_REVENUE FROM L3_RECURRING R
        WHERE R377_CYCLEBEGINTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) )C,
        (SELECT /*+PARALLEL(S,8)*/ SUM(S41_DEBIT_AMOUNT)/1000 SMS_REVENUE FROM L3_SMS S
        WHERE S387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) )D,
           (SELECT /*+PARALLEL(T,8)*/ SUM(CO41_DEBIT_AMOUNT)/1000 CONTENT_REVENUE FROM L3_CONTENT T
        WHERE CO402_STARTTIMEOFBILLCYL_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) )E,
        (SELECT /*+PARALLEL(U,8)*/ SUM(A30_DEBIT_AMOUNT)/1000 ADJUSTMENT_REVENUE FROM L3_ADJUSTMENT U
         WHERE A22_ENTRY_DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))  )F;

    COMMIT;
END;
/

