--
-- PRO_NEW_MGMT_DBOARD3_NEW_SUB_CT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.PRO_NEW_MGMT_DBOARD3_NEW_SUB_CT IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE NEW_MGMT_DBOARD3_NEW_SUB_CT WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO NEW_MGMT_DBOARD3_NEW_SUB_CT


SELECT COUNT(SERVICE_NUMBER) NEW_SUBSCRIBER_COUNT,VDATE_KEY
FROM
(SELECT /*+PARALLEL(P,8)*/ SERVICE_NUMBER FROM SUBSCRIPTION_DIM P
WHERE START_DATE = (SELECT DATE_VALUE  FROM DATE_DIM WHERE DATE_VALUE = TO_DATE (SYSDATE - 1, 'DD/MM/RRRR'))
GROUP BY SERVICE_NUMBER
);

    COMMIT;
END;
/

