--
-- PRO_NEW_MGMT_DBOARD4_ACT_SUB_CT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.PRO_NEW_MGMT_DBOARD4_ACT_SUB_CT IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE NEW_MGMT_DBOARD4_ACT_SUB_CT WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO NEW_MGMT_DBOARD4_ACT_SUB_CT


SELECT /*+PARALLEL(Q,8)*/  COUNT(MSISDN)ACTIVE_SUBSCRIBER_COUNT,VDATE_KEY
FROM
(SELECT /*+PARALLEL(P,8)*/ MSISDN FROM LAST_ACTIVITY_FCT P
WHERE LU_DATE_KEY  = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
GROUP BY MSISDN
)Q;

    COMMIT;
END;
/

