--
-- R22_REPEAT_ONLY_SMS_USERS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R22_REPEAT_ONLY_SMS_USERS IS

    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
INSERT INTO REPEAT_ONLY_SMS_USERS

SELECT /*+parallel(P,16)*/MSISDN,VDATE_KEY FROM 
(SELECT MSISDN FROM 
(SELECT /*+parallel(P,16)*/ DISTINCT S372_CALLINGPARTYNUMBER MSISDN
FROM L3_SMS P
WHERE (S387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE=TO_DATE(SYSDATE-31,'dd/mm/rrrr'))
                             AND  (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE=TO_DATE(SYSDATE-2,'dd/mm/rrrr')))
AND S378_SERVICEFLOW=1
GROUP BY S372_CALLINGPARTYNUMBER) A
WHERE 
NOT EXISTS
(SELECT MSISDN1 
FROM
((
SELECT /*+parallel(P,16)*/ DISTINCT G372_CALLINGPARTYNUMBER MSISDN1
FROM L3_DATA P
WHERE (G383_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE=TO_DATE(SYSDATE-31,'dd/mm/rrrr'))
                             AND  (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE=TO_DATE(SYSDATE-2,'dd/mm/rrrr')))
GROUP BY G372_CALLINGPARTYNUMBER)


UNION

(SELECT /*+parallel(P,16)*/ DISTINCT V372_CALLINGPARTYNUMBER  MSISDN
FROM L3_VOICE P
WHERE (V387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE=TO_DATE(SYSDATE-31,'dd/mm/rrrr'))
                             AND  (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE=TO_DATE(SYSDATE-2,'dd/mm/rrrr')))
AND V378_SERVICEFLOW=1
GROUP BY V372_CALLINGPARTYNUMBER)
)
WHERE MSISDN=MSISDN1
)

)P
WHERE 
EXISTS
(
SELECT S372_CALLINGPARTYNUMBER1 FROM
(SELECT S372_CALLINGPARTYNUMBER S372_CALLINGPARTYNUMBER1,TOTAL,DISTINCT_CALLEDPARTY FROM (
SELECT /*+parallel(P,16)*/ DISTINCT S372_CALLINGPARTYNUMBER, COUNT(S373_CALLEDPARTYNUMBER) AS TOTAL, COUNT(DISTINCT S373_CALLEDPARTYNUMBER) AS DISTINCT_CALLEDPARTY 
FROM L3_SMS P
WHERE (S387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE=TO_DATE(SYSDATE-31,'dd/mm/rrrr'))
                             AND  (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE=TO_DATE(SYSDATE-2,'dd/mm/rrrr')))
AND S378_SERVICEFLOW=1
GROUP BY S372_CALLINGPARTYNUMBER)
WHERE (TOTAL/DISTINCT_CALLEDPARTY)>1
)Q
WHERE S372_CALLINGPARTYNUMBER1=MSISDN
)






;
    COMMIT;
END;
/

