--
-- R_BIN37_7  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN37_7 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE BIN37_7 WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN37_7

SELECT /*+PARALLEL(A,8)*/ A.V372_CALLINGPARTYNUMBER,PRODUCT_NAME,MOC_DURATION,FREE_MINUTES,DATA_USAGE,BONUS_DATA ,VDATE_KEY

FROM PRODUCT_DIM,

(SELECT /*+PARALLEL(P,8)*/ V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID  FROM L3_VOICE P WHERE V378_SERVICEFLOW=1 AND V402_CALLTYPE !=3 AND  V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))  GROUP BY V372_CALLINGPARTYNUMBER,  V397_MAINOFFERINGID 
UNION
SELECT /*+PARALLEL(Q,8)*/ G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID FROM L3_DATA Q WHERE G383_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))  GROUP BY G372_CALLINGPARTYNUMBER,  G401_MAINOFFERINGID
)A



LEFT OUTER JOIN

 
(SELECT /*+PARALLEL(R,8)*/ V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID, sum(V35_RATE_USAGE)/60 MOC_DURATION,SUM(V50_PAY_FREE_UNIT_DURATION)/60 FREE_MINUTES
FROM L3_VOICE R WHERE  V378_SERVICEFLOW=1 AND V402_CALLTYPE !=3 AND V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')) 
GROUP BY V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID
)B ON  A.V372_CALLINGPARTYNUMBER=B.V372_CALLINGPARTYNUMBER AND A.V397_MAINOFFERINGID=B.V397_MAINOFFERINGID



LEFT OUTER JOIN



(SELECT /*+PARALLEL(S,8)*/ G372_CALLINGPARTYNUMBER ,G401_MAINOFFERINGID,sum(G384_TOTALFLUX)/1048576 DATA_USAGE,SUM(G51_FREE_UNIT_AMOUNT_OF_FLUX)/1048576 BONUS_DATA
FROM L3_DATA S WHERE G383_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')) 
GROUP BY  G372_CALLINGPARTYNUMBER ,G401_MAINOFFERINGID
)C ON  A.V372_CALLINGPARTYNUMBER=C.G372_CALLINGPARTYNUMBER AND A.V397_MAINOFFERINGID=C.G401_MAINOFFERINGID



WHERE A.V397_MAINOFFERINGID=PRODUCT_ID;
    COMMIT;
END;
/

