--
-- R_BIN37_2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN37_2 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE BIN37_2 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN37_2



SELECT PRODUCT_NAME,PAY_TYPE_NAME,CALL_REVENUE,SMS_REVENUE ,DATA_REVENUE,RECURRING_REVENUE,CONTENT_REVENUE,VDATE_KEY FROM PRODUCT_DIM,Paytype_dim,
(SELECT A.V397_MAINOFFERINGID,A.V400_PAYTYPE ,CALL_REVENUE,SMS_REVENUE,DATA_REVENUE,RECURRING_REVENUE,CONTENT_REVENUE FROM
(SELECT /*+PARALLEL(P,8)*/ V397_MAINOFFERINGID, V400_PAYTYPE FROM L3_VOICE P WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
UNION
SELECT /*+PARALLEL(Q,8)*/ S395_MAINOFFERINGID,S398_PAYTYPE  FROM L3_SMS Q WHERE S387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
UNION
SELECT /*+PARALLEL(R,8)*/ G401_MAINOFFERINGID,G403_PAYTYPE  FROM L3_DATA R WHERE G383_CHARGINGTIME_KEY=(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
UNION
SELECT /*+PARALLEL(S,8)*/ R373_MAINOFFERINGID, R374_PAYTYPE FROM L3_RECURRING S WHERE R377_CYCLEBEGINTIME_KEY=(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
UNION
SELECT /*+PARALLEL(T,8)*/ CO396_MAINOFFERINGID,CO410_PAYTYPE FROM L3_CONTENT T WHERE CO402_STARTTIMEOFBILLCYL_KEY=(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
)A

LEFT OUTER JOIN

(
SELECT /*+PARALLEL(U,8)*/ V397_MAINOFFERINGID ,V400_PAYTYPE, SUM(V41_DEBIT_AMOUNT) CALL_REVENUE
FROM L3_VOICE U WHERE V402_CALLTYPE !=3 AND  V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')) 
GROUP BY V397_MAINOFFERINGID,V400_PAYTYPE)B ON A.V397_MAINOFFERINGID=B.V397_MAINOFFERINGID and A.V400_PAYTYPE=B.V400_PAYTYPE

LEFT OUTER JOIN
(SELECT /*+PARALLEL(V,8)*/ S395_MAINOFFERINGID ,S398_PAYTYPE,SUM( S41_DEBIT_AMOUNT) SMS_REVENUE
FROM L3_SMS V WHERE S400_SMSTYPE !=3 AND  S387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')) 
GROUP BY S395_MAINOFFERINGID,S398_PAYTYPE)C ON A.V397_MAINOFFERINGID=C.S395_MAINOFFERINGID and A.V400_PAYTYPE=C.S398_PAYTYPE
LEFT OUTER JOIN
(
SELECT /*+PARALLEL(W,8)*/ G401_MAINOFFERINGID ,G403_PAYTYPE  ,SUM(G41_DEBIT_AMOUNT) DATA_REVENUE
FROM L3_DATA W WHERE G383_CHARGINGTIME_KEY=(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
GROUP BY G401_MAINOFFERINGID,G403_PAYTYPE

)D ON A.V397_MAINOFFERINGID=D.G401_MAINOFFERINGID  and A.V400_PAYTYPE=D.G403_PAYTYPE

LEFT OUTER JOIN

(
SELECT /*+PARALLEL(X,8)*/ R373_MAINOFFERINGID,R374_PAYTYPE , SUM(R41_DEBIT_AMOUNT) RECURRING_REVENUE
FROM L3_RECURRING X WHERE R377_CYCLEBEGINTIME_KEY=(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
GROUP BY R373_MAINOFFERINGID,R374_PAYTYPE

)E ON A.V397_MAINOFFERINGID=E.R373_MAINOFFERINGID   and A.V400_PAYTYPE=E.R374_PAYTYPE
LEFT OUTER JOIN
(
SELECT /*+PARALLEL(Y,8)*/  CO396_MAINOFFERINGID,CO410_PAYTYPE ,SUM(CO41_DEBIT_AMOUNT) CONTENT_REVENUE
FROM L3_CONTENT Y WHERE CO402_STARTTIMEOFBILLCYL_KEY=(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
GROUP BY CO396_MAINOFFERINGID,CO410_PAYTYPE
)F ON A.V397_MAINOFFERINGID=F.CO396_MAINOFFERINGID  and A.V400_PAYTYPE=F.CO410_PAYTYPE
)
WHERE PRODUCT_ID=V397_MAINOFFERINGID  and PAY_TYPE_ID=V400_PAYTYPE;
    COMMIT;
END;
/

