--
-- R_BIN7  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN7 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE BIN7 WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN7

select SITE_ID,CI, TOTAL_COUNT ,VDATE_KEY from Zone_dim,
(SELECT V381_CALLINGCELLID V_CELLID,COUNT(V372_CALLINGPARTYNUMBER)  TOTAL_COUNT
FROM
(

(SELECT V381_CALLINGCELLID ,V372_CALLINGPARTYNUMBER
FROM L3_VOICE A
WHERE V378_SERVICEFLOW=1 AND   V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE (SYSDATE - 1,'DD/MM/RRRR'))
AND V402_CALLTYPE != 3
GROUP BY V381_CALLINGCELLID, V372_CALLINGPARTYNUMBER
)

UNION


(SELECT V383_CALLEDCELLID ,V373_CALLEDPARTYNUMBER
FROM L3_VOICE A
WHERE V378_SERVICEFLOW=2 AND   V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE (SYSDATE - 1,'DD/MM/RRRR'))
AND V402_CALLTYPE != 3
GROUP BY V383_CALLEDCELLID ,V373_CALLEDPARTYNUMBER
)

UNION

(
SELECT G379_CALLINGCELLID G_CELLID,G372_CALLINGPARTYNUMBER FROM L3_DATA C
WHERE G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE (SYSDATE - 1, 'DD/MM/RRRR'))
GROUP BY G379_CALLINGCELLID, G372_CALLINGPARTYNUMBER

)
)
group by V381_CALLINGCELLID
)
where V_CELLID=CGI;

    COMMIT;
END;
/

