--
-- R_BIN37_6  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN37_6 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE BIN37_6 WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN37_6


select  PRODUCT_NAME ,TOTAL_COUNT,ONLY_VOICE,ONLY_DATA,BOTH_VOICE_DATA ,VDATE_KEY from Product_dim,

(SELECT A.G401_MAINOFFERINGID,TOTAL_COUNT,ONLY_VOICE,ONLY_DATA,BOTH_VOICE_DATA from

(SELECT /*+PARALLEL(T,8)*/ G401_MAINOFFERINGID, COUNT(G372_CALLINGPARTYNUMBER) TOTAL_COUNT
FROM
(
SELECT G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER
FROM(
(SELECT /*+PARALLEL(P,8)*/ G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
FROM  L3_DATA P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR'))) 
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER

)
UNION

(SELECT /*+PARALLEL(Q,8)*/ V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 
FROM  L3_VOICE Q
WHERE V378_SERVICEFLOW = 1 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY  V397_MAINOFFERINGID,V372_CALLINGPARTYNUMBER
)

UNION

(SELECT /*+PARALLEL(R,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE R
WHERE  V378_SERVICEFLOW = 1 AND V25_USAGE_SERVICE_TYPE=10  AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)
UNION
(SELECT /*+PARALLEL(S,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE S
WHERE V378_SERVICEFLOW = 2 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)


)
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
) T
GROUP BY G401_MAINOFFERINGID
) A






LEFT OUTER JOIN







(SELECT /*+PARALLEL(P2,8)*/ G401_MAINOFFERINGID, COUNT(G372_CALLINGPARTYNUMBER) ONLY_VOICE
FROM
(SELECT G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER FROM 
(SELECT /*+PARALLEL(P1,8)*/ G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER
FROM(
(SELECT /*+PARALLEL(U,8)*/ G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
FROM  L3_DATA U
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR'))) 
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER

)
UNION

(SELECT /*+PARALLEL(V,8)*/ V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 
FROM  L3_VOICE V
WHERE V378_SERVICEFLOW = 1 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY  V397_MAINOFFERINGID,V372_CALLINGPARTYNUMBER
)

UNION

(SELECT /*+PARALLEL(W,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE W
WHERE  V378_SERVICEFLOW = 1 AND V25_USAGE_SERVICE_TYPE=10  AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)
UNION
(SELECT /*+PARALLEL(X,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE X 
WHERE V378_SERVICEFLOW = 2 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)


)P1
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
)

MINUS
 
(SELECT /*+PARALLEL(Y,8)*/ G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER
FROM  L3_DATA Y
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR'))) 
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER)
) P2
GROUP BY G401_MAINOFFERINGID
) B   on A.G401_MAINOFFERINGID=B.G401_MAINOFFERINGID




LEFT OUTER JOIN






(select /*+PARALLEL(Q2,8)*/ G401_MAINOFFERINGID, count(G372_CALLINGPARTYNUMBER) ONLY_DATA
from
(SELECT G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER FROM 
(SELECT/*+PARALLEL(Q1,8)*/ G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER
FROM(
(SELECT /*+PARALLEL(Z,8)*/ G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
FROM  L3_DATA Z
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR'))) 
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER

)
UNION

(SELECT /*+PARALLEL(PP,8)*/  V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 
FROM  L3_VOICE PP
WHERE V378_SERVICEFLOW = 1 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY  V397_MAINOFFERINGID,V372_CALLINGPARTYNUMBER
)

UNION

(SELECT /*+PARALLEL(QQ,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE QQ
WHERE  V378_SERVICEFLOW = 1 AND V25_USAGE_SERVICE_TYPE=10  AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)
UNION
(SELECT /*+PARALLEL(RR,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE RR
WHERE V378_SERVICEFLOW = 2 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)


)Q1
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
)A

MINUS

( 
select V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 
from
(
(SELECT /*+PARALLEL(SS,8)*/  V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 
FROM  L3_VOICE SS
WHERE V378_SERVICEFLOW = 1 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY  V397_MAINOFFERINGID,V372_CALLINGPARTYNUMBER
)

UNION

(SELECT /*+PARALLEL(TT,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE TT
WHERE  V378_SERVICEFLOW = 1 AND V25_USAGE_SERVICE_TYPE=10  AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)
UNION
(SELECT /*+PARALLEL(UU,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE UU
WHERE V378_SERVICEFLOW = 2 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)
)
group by V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 

)

)Q2
group by G401_MAINOFFERINGID

) C  on A.G401_MAINOFFERINGID=C.G401_MAINOFFERINGID




left outer join






(SELECT /*+PARALLEL(R2,8)*/ V397_MAINOFFERINGID, COUNT(V372_CALLINGPARTYNUMBER) BOTH_VOICE_DATA
FROM
(SELECT V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER FROM 
(SELECT /*+PARALLEL(R1,8)*/ V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER
FROM(

(SELECT /*+PARALLEL(VV,8)*/ V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 
FROM  L3_VOICE VV
WHERE V378_SERVICEFLOW = 1 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY  V397_MAINOFFERINGID,V372_CALLINGPARTYNUMBER
)

UNION

(SELECT /*+PARALLEL(WW,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE WW
WHERE  V378_SERVICEFLOW = 1 AND V25_USAGE_SERVICE_TYPE=10  AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)
UNION
(SELECT /*+PARALLEL(XX,8)*/ V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE XX
WHERE V378_SERVICEFLOW = 2 AND V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY   V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)


)R1
GROUP BY V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 
)P
WHERE

EXISTS
 
(
SELECT G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER
FROM
(SELECT /*+PARALLEL(YY,8)*/ G401_MAINOFFERINGID, G372_CALLINGPARTYNUMBER
FROM  L3_DATA YY
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR'))) 
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER)

WHERE G401_MAINOFFERINGID=P.V397_MAINOFFERINGID AND G372_CALLINGPARTYNUMBER=P.V372_CALLINGPARTYNUMBER
)

)R2
GROUP BY V397_MAINOFFERINGID

) D  on A.G401_MAINOFFERINGID=D.V397_MAINOFFERINGID






)
where G401_MAINOFFERINGID=PRODUCT_ID;
COMMIT;
END;
/

