--
-- R_BIN37_15  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN37_15 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE BIN37_15 WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN37_15


SELECT PRODUCT_NAME,MO_DURATION,MT_DURATION,TOTAL_DATA_VOLUME,SMS_COUNT,VDATE_KEY FROM PRODUCT_DIM,
(SELECT A.V397_MAINOFFERINGID ,MO_DURATION/60 MO_DURATION,MT_DURATION/60 MT_DURATION,TOTAL_DATA_VOLUME/1048576 TOTAL_DATA_VOLUME,SMS_COUNT FROM
(SELECT /*+PARALLEL(P,8)*/ V397_MAINOFFERINGID FROM L3_VOICE P WHERE V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
UNION
SELECT /*+PARALLEL(Q,8)*/ G401_MAINOFFERINGID FROM L3_DATA Q WHERE G383_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR'))
UNION
SELECT /*+PARALLEL(R,8)*/ S395_MAINOFFERINGID FROM L3_SMS R WHERE S387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')))A

LEFT OUTER JOIN

(
SELECT /*+PARALLEL(S,8)*/ V397_MAINOFFERINGID , SUM(V35_RATE_USAGE)  MO_DURATION
FROM L3_VOICE S WHERE V402_CALLTYPE !=3 AND  V378_SERVICEFLOW=1 AND  V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
GROUP BY V397_MAINOFFERINGID
)B ON A.V397_MAINOFFERINGID=B.V397_MAINOFFERINGID
LEFT OUTER JOIN
(
SELECT /*+PARALLEL(T,8)*/ V397_MAINOFFERINGID , SUM(V35_RATE_USAGE) MT_DURATION
FROM L3_VOICE T WHERE V402_CALLTYPE !=3 AND  V378_SERVICEFLOW=2 AND  V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
GROUP BY V397_MAINOFFERINGID)C ON A.V397_MAINOFFERINGID=C.V397_MAINOFFERINGID

LEFT OUTER JOIN
(SELECT /*+PARALLEL(U,8)*/ G401_MAINOFFERINGID ,SUM(G384_TOTALFLUX) TOTAL_DATA_VOLUME
FROM L3_DATA U WHERE G383_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE - 1,'DD/MM/RRRR')) 
GROUP BY G401_MAINOFFERINGID)D ON A.V397_MAINOFFERINGID=D.G401_MAINOFFERINGID

LEFT OUTER JOIN
(SELECT /*+PARALLEL(V,8)*/ S395_MAINOFFERINGID ,COUNT( S22_PRI_IDENTITY) SMS_COUNT
FROM L3_SMS V WHERE S400_SMSTYPE !=3 AND  S387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')) 
GROUP BY S395_MAINOFFERINGID)E ON A.V397_MAINOFFERINGID=E.S395_MAINOFFERINGID)
WHERE PRODUCT_ID=V397_MAINOFFERINGID;
    COMMIT;
END;
/

