--
-- R_BIN12  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN12 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE BIN12 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN12
SELECT A.DISTRICT,A.THREEG,A.TWOG,A.FOURG ,A.VOICE_REVENUE ,A.VOICE_DURATION,A.DATAPAYG_REVENUE,B.ACTIVATION_COUNT,VDATE_KEY
 FROM
(SELECT INITCAP(DISTRICT) DISTRICT, SUM(VOLUME3G/1073741824) THREEG, SUM(VOLUME2G/1073741824) TWOG, SUM(VOLUME4G/1073741824) FOURG ,

SUM(VOICE_REVENUE) VOICE_REVENUE,SUM(DATAPAYG_REVENUE) DATAPAYG_REVENUE, SUM(VOICE_DURATION/60)  VOICE_DURATION FROM ZONE_DIM,


(SELECT X,VOICE_DURATION, DATAPAYG_REVENUE, VOLUME3G, VOLUME2G, VOLUME4G,VOICE_REVENUE
FROM UPDATED_BIN12
)
WHERE CGI=X
GROUP BY INITCAP(DISTRICT)
) A

LEFT OUTER JOIN



(SELECT  DISTRICT,COUNT(V372_CALLINGPARTYNUMBER) ACTIVATION_COUNT FROM 
(SELECT  INITCAP(DISTRICT) DISTRICT,V372_CALLINGPARTYNUMBER FROM ZONE_DIM,

(SELECT V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER 
FROM
( 
(SELECT V381_CALLINGCELLID, V372_CALLINGPARTYNUMBER
FROM L3_VOICE
WHERE V378_SERVICEFLOW = 1
AND V402_CALLTYPE != 3
AND V387_CHARGINGTIME_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE - 1,'DD/MM/RRRR'))
GROUP BY V381_CALLINGCELLID, V372_CALLINGPARTYNUMBER
)

UNION

(
SELECT V383_CALLEDCELLID, V373_CALLEDPARTYNUMBER
FROM L3_VOICE
WHERE     V378_SERVICEFLOW = 2
AND V402_CALLTYPE != 3
AND V387_CHARGINGTIME_KEY =(SELECT A.DATE_KEY  FROM DATE_DIM A  WHERE A.DATE_VALUE = TO_DATE (SYSDATE - 1,  'DD/MM/RRRR'))
GROUP BY V383_CALLEDCELLID, V373_CALLEDPARTYNUMBER

)

UNION

(
SELECT G379_CALLINGCELLID, G372_CALLINGPARTYNUMBER
FROM L3_DATA
WHERE G383_CHARGINGTIME_KEY =(SELECT A.DATE_KEY   FROM DATE_DIM A  WHERE A.DATE_VALUE = TO_DATE (SYSDATE - 1, 'DD/MM/RRRR'))
GROUP BY G379_CALLINGCELLID, G372_CALLINGPARTYNUMBER
)
)
GROUP BY V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER
)
WHERE V381_CALLINGCELLID= CGI
GROUP BY INITCAP(DISTRICT),V372_CALLINGPARTYNUMBER
)

GROUP BY DISTRICT
)B ON A.DISTRICT=B.DISTRICT;
    COMMIT;
END;
/

