--
-- R_BIN3  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN3 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE BIN3 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN3

SELECT PRODUCT_NAME,DATE_VALUE,TCOUNT,VDATE_KEY FROM PRODUCT_DIM,DATE_DIM,
(SELECT G383_CHARGINGTIME_KEY,G401_MAINOFFERINGID,COUNT(G372_CALLINGPARTYNUMBER) TCOUNT
FROM(
(SELECT G383_CHARGINGTIME_KEY,G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
FROM  L3_DATA 
WHERE G383_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-3,'DD/MM/RRRR'))) 
GROUP BY G383_CHARGINGTIME_KEY,G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER

)
UNION

(SELECT V387_CHARGINGTIME_KEY,V397_MAINOFFERINGID, V372_CALLINGPARTYNUMBER 
FROM  L3_VOICE 
WHERE V378_SERVICEFLOW = 1 AND V387_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-3,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY V387_CHARGINGTIME_KEY,  V397_MAINOFFERINGID,V372_CALLINGPARTYNUMBER
)

UNION

(SELECT V387_CHARGINGTIME_KEY,V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE 
WHERE  V378_SERVICEFLOW = 1 AND V25_USAGE_SERVICE_TYPE=10  AND V387_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-3,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY V387_CHARGINGTIME_KEY,  V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)
UNION
(SELECT V387_CHARGINGTIME_KEY,V397_MAINOFFERINGID, V373_CALLEDPARTYNUMBER 
FROM  L3_VOICE 
WHERE V378_SERVICEFLOW = 2 AND V387_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-3,'DD/MM/RRRR')))
AND V402_CALLTYPE !=3
GROUP BY V387_CHARGINGTIME_KEY,  V397_MAINOFFERINGID,V373_CALLEDPARTYNUMBER
)
UNION
(
SELECT S387_CHARGINGTIME_KEY,S395_MAINOFFERINGID , S372_CALLINGPARTYNUMBER
FROM  L3_SMS 
WHERE  S378_SERVICEFLOW =1 AND  S387_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-3,'DD/MM/RRRR'))) 
AND S400_SMSTYPE !=3
GROUP BY S387_CHARGINGTIME_KEY,  S395_MAINOFFERINGID,S372_CALLINGPARTYNUMBER

)
UNION
(
SELECT S387_CHARGINGTIME_KEY,S395_MAINOFFERINGID , S372_CALLINGPARTYNUMBER
FROM  L3_SMS 
WHERE  S378_SERVICEFLOW =1 AND S401_ONNETINDICATOR=0  AND  S387_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-3,'DD/MM/RRRR'))) 
AND S400_SMSTYPE !=3
GROUP BY S387_CHARGINGTIME_KEY,  S395_MAINOFFERINGID,S372_CALLINGPARTYNUMBER

)

UNION
(
SELECT S387_CHARGINGTIME_KEY,S395_MAINOFFERINGID , S373_CALLEDPARTYNUMBER
FROM  L3_SMS 
WHERE S378_SERVICEFLOW =2 AND S387_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-3,'DD/MM/RRRR'))) 
AND S400_SMSTYPE !=3
GROUP BY S387_CHARGINGTIME_KEY,  S395_MAINOFFERINGID,S373_CALLEDPARTYNUMBER

)

)
GROUP BY G383_CHARGINGTIME_KEY,G401_MAINOFFERINGID
)
WHERE PRODUCT_ID= G401_MAINOFFERINGID AND DATE_KEY=G383_CHARGINGTIME_KEY;
    COMMIT;
END;
/

