--
-- R_BI_SERVER_TASK  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BI_SERVER_TASK IS
    VDATE_KEY       NUMBER;
BEGIN


    
INSERT INTO BI_SERVER_TASK

SELECT /*+PARALLEL(P,15)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) SMS_REVENUE 
FROM  L3_SMS P
WHERE S387_CHARGINGTIME_KEY  BETWEEN  (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
                             AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
GROUP BY S387_CHARGINGTIME_KEY


;
    COMMIT;
END;
/

