--
-- R_BIN37_11  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN37_11 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE BIN37_11 WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN37_11


select PRODUCT_NAME ,Total_Duration,Voice_Revenue,SMS_Count,SMS_Revenue,Datapayg_Revenue,Data_Volume,VDATE_KEY 
from product_dim,
(select A.V397_MAINOFFERINGID,B.Total_Duration,B.Voice_Revenue,C.SMS_Count,C.SMS_Revenue,D.Datapayg_Revenue,D.Data_Volume 
from 
(
select /*+PARALLEL(P,8)*/  V397_MAINOFFERINGID 
from L3_VOICE P where V402_CALLTYPE !=3 and V400_PAYTYPE=1 and V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')) 
group by V397_MAINOFFERINGID
union
select /*+PARALLEL(Q,8)*/  S395_MAINOFFERINGID
from l3_sms Q where S400_SMSTYPE !=3 and S398_PAYTYPE=1 and S387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
 
union
select /*+PARALLEL(R,8)*/  G401_MAINOFFERINGID
from l3_data R where G403_PAYTYPE=1 and G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))

)A
left outer join
(
select /*+PARALLEL(S,8)*/  V397_MAINOFFERINGID , sum(V35_RATE_USAGE)/60 Total_Duration,sum(V41_DEBIT_AMOUNT) Voice_Revenue
from L3_VOICE S where V402_CALLTYPE !=3 and V400_PAYTYPE=1 and V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')) 
group by V397_MAINOFFERINGID
)B on A.V397_MAINOFFERINGID=B.V397_MAINOFFERINGID

left outer join
(
select /*+PARALLEL(T,8)*/  S395_MAINOFFERINGID ,Count(S22_PRI_IDENTITY) SMS_Count, sum(S41_DEBIT_AMOUNT) SMS_Revenue
from l3_sms T where S400_SMSTYPE !=3 and S398_PAYTYPE=1 and S387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
group by  S395_MAINOFFERINGID
)C on A.V397_MAINOFFERINGID=C.S395_MAINOFFERINGID

left outer join
(
select /*+PARALLEL(U,8)*/  G401_MAINOFFERINGID , sum(G41_DEBIT_AMOUNT) Datapayg_Revenue, sum(G384_TOTALFLUX)/1073741824 Data_Volume
from l3_data U  where G403_PAYTYPE=1 and G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
group by G401_MAINOFFERINGID
)D on A.V397_MAINOFFERINGID=D.G401_MAINOFFERINGID
)
where V397_MAINOFFERINGID = PRODUCT_ID;

    COMMIT;
END;
/

