--
-- R_BIN37_14  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BIN37_14 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE BIN37_14 WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO BIN37_14


select DATE_VALUE ,MOC_DURATION_GP,MOC_COUNT_GP,MOSMS_COUNT_GP ,MOC_DURATION_ROBI,MOC_COUNT_ROBI,MOSMS_COUNT_ROBI,
         MOC_DURATION_AIR,MOC_COUNT_AIR,MOSMS_COUNT_AIR,MOC_DURATION_BL,MOC_COUNT_BL,MOSMS_COUNT_BL,VDATE_KEY
         from date_dim,
(select A.V387_CHARGINGTIME_KEY ,MOC_DURATION_GP,MOC_COUNT_GP,MOSMS_COUNT_GP ,MOC_DURATION_ROBI,MOC_COUNT_ROBI,MOSMS_COUNT_ROBI,
         MOC_DURATION_AIR,MOC_COUNT_AIR,MOSMS_COUNT_AIR,MOC_DURATION_BL,MOC_COUNT_BL,MOSMS_COUNT_BL
from
((select /*+PARALLEL(P,8)*/   V387_CHARGINGTIME_KEY
from L3_voice P
where V387_CHARGINGTIME_KEY in (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(SYSDATE-3,'DD/MM/RRRR')))

union

(select /*+PARALLEL(Q,8)*/   S387_CHARGINGTIME_KEY
from L3_SMS Q
where S387_CHARGINGTIME_KEY in (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(SYSDATE-3,'DD/MM/RRRR')))
)A

-----------GP

left outer join

 
(select /*+PARALLEL(R,8)*/  V387_CHARGINGTIME_KEY,  sum(V35_RATE_USAGE)/60 MOC_DURATION_GP, count(V373_CALLEDPARTYNUMBER) MOC_COUNT_GP
from L3_VOICE R
where V403_ROAMSTATE !=3 and V378_SERVICEFLOW=1 
AND  substr(V373_CALLEDPARTYNUMBER,3,3) IN ('017','013')
AND  V387_CHARGINGTIME_KEY in (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(SYSDATE-3,'DD/MM/RRRR'))
group by V387_CHARGINGTIME_KEY
)B on A.V387_CHARGINGTIME_KEY=B.V387_CHARGINGTIME_KEY

left outer join

(select /*+PARALLEL(S,8)*/  S387_CHARGINGTIME_KEY, count(*) MOSMS_COUNT_GP from l3_sms S
where S378_SERVICEFLOW=1  
AND  substr(S373_CALLEDPARTYNUMBER,3,3) IN ('017','013')
and
S387_CHARGINGTIME_KEY in  (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(sysdate-3,'DD/MM/RRRR')) 
group by S387_CHARGINGTIME_KEY
) C on A.V387_CHARGINGTIME_KEY=C.S387_CHARGINGTIME_KEY

--------------- Robi

left outer join

 
(select /*+PARALLEL(T,8)*/  V387_CHARGINGTIME_KEY,  sum(V35_RATE_USAGE)/60 MOC_DURATION_ROBI, count(V373_CALLEDPARTYNUMBER) MOC_COUNT_ROBI
from L3_VOICE T
where V403_ROAMSTATE !=3 and V378_SERVICEFLOW=1 
AND  substr(V373_CALLEDPARTYNUMBER,3,3) IN ('018')
AND  V387_CHARGINGTIME_KEY in (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(SYSDATE-3,'DD/MM/RRRR'))
group by V387_CHARGINGTIME_KEY
)B on A.V387_CHARGINGTIME_KEY=B.V387_CHARGINGTIME_KEY

left outer join

(select /*+PARALLEL(U,8)*/  S387_CHARGINGTIME_KEY, count(*) MOSMS_COUNT_ROBI from l3_sms U
where S378_SERVICEFLOW=1  
AND  substr(S373_CALLEDPARTYNUMBER,3,3) IN ('018')
and
S387_CHARGINGTIME_KEY in  (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(sysdate-3,'DD/MM/RRRR')) 
group by S387_CHARGINGTIME_KEY
) C on A.V387_CHARGINGTIME_KEY=C.S387_CHARGINGTIME_KEY


---------Airtel 


left outer join

 
(select /*+PARALLEL(V,8)*/  V387_CHARGINGTIME_KEY,  sum(V35_RATE_USAGE)/60 MOC_DURATION_AIR, count(V373_CALLEDPARTYNUMBER) MOC_COUNT_AIR
from L3_VOICE V
where V403_ROAMSTATE !=3 and V378_SERVICEFLOW=1 
AND  substr(V373_CALLEDPARTYNUMBER,3,3) IN ('016')
AND  V387_CHARGINGTIME_KEY in (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(SYSDATE-3,'DD/MM/RRRR'))
group by V387_CHARGINGTIME_KEY
)B on A.V387_CHARGINGTIME_KEY=B.V387_CHARGINGTIME_KEY

left outer join

(select /*+PARALLEL(W,8)*/  S387_CHARGINGTIME_KEY, count(*) MOSMS_COUNT_AIR from l3_sms W
where S378_SERVICEFLOW=1  
AND  substr(S373_CALLEDPARTYNUMBER,3,3) IN ('016')
and
S387_CHARGINGTIME_KEY in  (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(sysdate-3,'DD/MM/RRRR')) 
group by S387_CHARGINGTIME_KEY
) C on A.V387_CHARGINGTIME_KEY=C.S387_CHARGINGTIME_KEY

-------banglalink


left outer join

 
(select  /*+PARALLEL(X,8)*/  V387_CHARGINGTIME_KEY,  sum(V35_RATE_USAGE)/60 MOC_DURATION_BL, count(V373_CALLEDPARTYNUMBER) MOC_COUNT_BL
from L3_VOICE X
where V403_ROAMSTATE !=3 and V378_SERVICEFLOW=1 
AND  substr(V373_CALLEDPARTYNUMBER,3,3) IN ('019','014')
AND  V387_CHARGINGTIME_KEY in (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(SYSDATE-3,'DD/MM/RRRR'))
group by V387_CHARGINGTIME_KEY
)B on A.V387_CHARGINGTIME_KEY=B.V387_CHARGINGTIME_KEY

left outer join

(select /*+PARALLEL(Y,8)*/  S387_CHARGINGTIME_KEY, count(*) MOSMS_COUNT_BL from l3_sms Y
where S378_SERVICEFLOW=1  
AND  substr(S373_CALLEDPARTYNUMBER,3,3) IN ('019','014')
and
S387_CHARGINGTIME_KEY in  (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE >= TO_DATE(sysdate-3,'DD/MM/RRRR')) 
group by S387_CHARGINGTIME_KEY
) C on A.V387_CHARGINGTIME_KEY=C.S387_CHARGINGTIME_KEY
)
where V387_CHARGINGTIME_KEY=DATE_KEY;
    COMMIT;
END;
/

