--
-- R_BTS_MSISDN_WISE_CALL_DROP_COUNT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_BTS_MSISDN_WISE_CALL_DROP_COUNT IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE,'RRRRMMDD');

    
INSERT INTO BTS_MSISDN_WISE_CALL_DROP_COUNT


(SELECT /*+PARALLEL(P,15)*/ M07_ANSWERTIMESTAMP_KEY DATE_KEY ,M04_MSISDNAPARTY,M09_LOCATION
       , COUNT(*) CALL_DROP_COUNT
FROM L1_MSC@DWH05TODWH03 P
WHERE PROCESSED_DATE =  TO_DATE(SYSDATE-1,'DD/MONTH/RRRR') 
AND   M07_ANSWERTIMESTAMP_KEY =( (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
                                                       
AND M01_CALLTYPE in ('MTC','MOC')
AND M11_CAUSEOFTERMINATION='stableCallAbnormalTermination'
GROUP BY M07_ANSWERTIMESTAMP_KEY,M04_MSISDNAPARTY,M09_LOCATION
) 

;
    COMMIT;
END;
/

