--
-- R_CALL_DROP_COUNT_SYS2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_CALL_DROP_COUNT_SYS2 IS

BEGIN

 
INSERT INTO CALL_DROP_COUNT



(SELECT /*+PARALLEL(P,15)*/ M07_ANSWERTIMESTAMP_KEY DATE_KEY ,M04_MSISDNAPARTY,M09_LOCATION, COUNT(*) CALL_DROP_COUNT
FROM L1_MSC@DWH05TODWH03 P
WHERE (PROCESSED_DATE BETWEEN  TO_DATE(SYSDATE-2,'DD/MONTH/RRRR') AND TO_DATE(SYSDATE-1,'DD/MONTH/RRRR')) 
AND   M07_ANSWERTIMESTAMP_KEY =( (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))
AND M01_CALLTYPE in ('MTC','MOC')
AND M11_CAUSEOFTERMINATION IN ('stableCallAbnormalTermination','Handover failure')
GROUP BY M07_ANSWERTIMESTAMP_KEY,M04_MSISDNAPARTY,M09_LOCATION
) 
;
    COMMIT;
END;
/

