--
-- R_CBS_REPORT_4_SYSDATE2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_CBS_REPORT_4_SYSDATE2 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE CBS_REPORT_4 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO CBS_REPORT_4






SELECT DATE_VALUE,CHARGED_MINUTES,FREE_MINUTES,PAID_MINUTES,DATA_USAGE_GB,VDATE_KEY FROM DATE_DIM S,
(SELECT A.DATE_KEY,CHARGED_MINUTES,FREE_MINUTES,PAID_MINUTES,DATA_USAGE_GB 
FROM
(SELECT DATE_KEY FROM DATE_DIM 
WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
                                                     
)A

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,10)*/ V387_CHARGINGTIME_KEY, SUM(V35_RATE_USAGE)/60 CHARGED_MINUTES,SUM(V50_PAY_FREE_UNIT_DURATION)/60 FREE_MINUTES
FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
                                                      
       AND V378_SERVICEFLOW=1
GROUP BY V387_CHARGINGTIME_KEY
)B ON A.DATE_KEY=B.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(Q,10)*/ V387_CHARGINGTIME_KEY, SUM(V50_PAY_FREE_UNIT_DURATION)/60 PAID_MINUTES
FROM L3_VOICE Q
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
                                          
       AND V378_SERVICEFLOW=1
       AND V436_LASTEFFECTOFFERING IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE IN ('Voice','Combo'))
GROUP BY V387_CHARGINGTIME_KEY
)C ON A.DATE_KEY=C.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(R,10)*/ G383_CHARGINGTIME_KEY, SUM(G384_TOTALFLUX)/1073741824 DATA_USAGE_GB
FROM L3_DATA R
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
                                                 
GROUP BY G383_CHARGINGTIME_KEY
)D ON A.DATE_KEY=D.G383_CHARGINGTIME_KEY
)T
WHERE S.DATE_KEY=T.DATE_KEY
;
    COMMIT;
END;
/

