--
-- R_CBS_REPORT_2_SYSDATE2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_CBS_REPORT_2_SYSDATE2 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE CBS_REPORT_2 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO CBS_REPORT_2


SELECT DATE_VALUE,AGAMI_TK,BORNOMALA_TK,CORPORATE_TK,MAYERHASHI_TK,OPORAJITA_TK,PCO_TK,PROJONMO_TK,SAGOTOM_TK,SHADHEEN_TK,YOUTH3G_TK,YOUTHDF_TK,YOUTHRC_TK,YOUTH_TK, 
       TOTAL_VOICE_TK,TOTAL_DATA_TK,TOTAL_SMS_TK,DATA_PPU_REVENUE,BUNDLE_REVENUE,TOTAL_COMBO,EXCLUSIVE_DATA_PACK,REGULAR_DATA_PACK,OTHER_DATA_PACK,TOTAL_REVNUE_TK,RECHARGE_AMOUNT,VDATE_KEY
FROM DATE_DIM AA,

(SELECT A.DATE_KEY, COALESCE (AGAMI_VOICE_REVENUE, 0)+ COALESCE (AGAMI_DATA_REVENUE, 0)+ COALESCE (AGAMI_SMS_REVENUE, 0)+ COALESCE (AGAMI_RECURRING_REVENUE, 0) AGAMI_TK,
 COALESCE (BORNOMALA_VOICE_REVENUE, 0)+ COALESCE (BORNOMALA_DATA_REVENUE, 0)+ COALESCE (BORNOMALA_SMS_REVENUE, 0)+ COALESCE (BORNOMALA_RECURRING_REVENUE, 0) BORNOMALA_TK,
 COALESCE (CORPORATE_VOICE_REVENUE, 0)+ COALESCE (CORPORATE_DATA_REVENUE, 0)+ COALESCE (CORPORATE_SMS_REVENUE, 0)+ COALESCE (CORPORATE_RECURRING_REVENUE, 0) CORPORATE_TK,
 COALESCE (MAYERHASHI_VOICE_REVENUE, 0)+ COALESCE (MAYERHASHI_DATA_REVENUE, 0)+ COALESCE (MAYERHASHI_SMS_REVENUE, 0)+ COALESCE (MAYERHASHI_RECURRING_REVENUE, 0) MAYERHASHI_TK,
 COALESCE (OPORAJITA_VOICE_REVENUE, 0)+ COALESCE (OPORAJITA_DATA_REVENUE, 0)+ COALESCE (OPORAJITA_SMS_REVENUE, 0)+ COALESCE (OPORAJITA_RECURRING_REVENUE, 0) OPORAJITA_TK,
 COALESCE (PCO_VOICE_REVENUE, 0)+ COALESCE (PCO_DATA_REVENUE, 0)+ COALESCE (PCO_SMS_REVENUE, 0)+ COALESCE (PCO_RECURRING_REVENUE, 0) PCO_TK,
 COALESCE (PROJONMO_VOICE_REVENUE, 0)+ COALESCE (PROJONMO_DATA_REVENUE, 0)+ COALESCE (PROJONMO_SMS_REVENUE, 0)+ COALESCE (PROJONMO_RECURRING_REVENUE, 0) PROJONMO_TK,
 COALESCE (SAGOTOM_VOICE_REVENUE, 0)+ COALESCE (SAGOTOM_DATA_REVENUE, 0)+ COALESCE (SAGOTOM_SMS_REVENUE, 0)+ COALESCE (SAGOTOM_RECURRING_REVENUE, 0) SAGOTOM_TK,
 COALESCE (SHADHEEN_VOICE_REVENUE, 0)+ COALESCE (SHADHEEN_DATA_REVENUE, 0)+ COALESCE (SHADHEEN_SMS_REVENUE, 0)+ COALESCE (SHADHEEN_RECURRING_REVENUE, 0) SHADHEEN_TK,
 COALESCE (YOUTH3G_VOICE_REVENUE, 0)+ COALESCE (YOUTH3G_DATA_REVENUE, 0)+ COALESCE (YOUTH3G_SMS_REVENUE, 0)+ COALESCE (YOUTH3G_RECURRING_REVENUE, 0) YOUTH3G_TK,
 COALESCE (YOUTHDF_VOICE_REVENUE, 0)+ COALESCE (YOUTHDF_DATA_REVENUE, 0)+ COALESCE (YOUTHDF_SMS_REVENUE, 0)+ COALESCE (YOUTHDF_RECURRING_REVENUE, 0) YOUTHDF_TK,
 COALESCE (YOUTHRC_VOICE_REVENUE, 0)+ COALESCE (YOUTHRC_DATA_REVENUE, 0)+ COALESCE (YOUTHRC_SMS_REVENUE, 0)+ COALESCE (YOUTHRC_RECURRING_REVENUE, 0) YOUTHRC_TK,
 COALESCE (YOUTH_VOICE_REVENUE, 0)+ COALESCE (YOUTH_DATA_REVENUE, 0)+ COALESCE (YOUTH_SMS_REVENUE, 0)+ COALESCE (YOUTH_RECURRING_REVENUE, 0) YOUTH_TK,
 COALESCE (VOICE_REVENUE, 0) TOTAL_VOICE_TK, COALESCE (DATA_PPU_REVENUE, 0)+ COALESCE (RECURRING_DATA, 0) TOTAL_DATA_TK,
 COALESCE (SMS_REVENUE, 0)+ COALESCE (RECURRING_SMS, 0) TOTAL_SMS_TK,DATA_PPU_REVENUE,BUNDLE_REVENUE,TOTAL_COMBO,EXCLUSIVE_DATA_PACK,REGULAR_DATA_PACK,OTHER_DATA_PACK,
 COALESCE (VOICE_REVENUE, 0)+ COALESCE (DATA_PPU_REVENUE, 0)+ COALESCE (SMS_REVENUE, 0)+ COALESCE (BUNDLE_REVENUE, 0) TOTAL_REVNUE_TK,RECHARGE_AMOUNT


FROM 
(SELECT DATE_KEY FROM DATE_DIM 
WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
) A


LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) AGAMI_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID IN (300033,400012)
GROUP BY V387_CHARGINGTIME_KEY
)A1 ON A.DATE_KEY=A1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) AGAMI_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID IN (300033,400012)
GROUP BY G383_CHARGINGTIME_KEY
)A2 ON A.DATE_KEY=A2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) AGAMI_SMS_REVENUE FROM L3_SMS P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID IN (300033,400012)
GROUP BY S387_CHARGINGTIME_KEY
)A3 ON A.DATE_KEY=A3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) AGAMI_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID IN (300033,400012)
GROUP BY R377_CYCLEBEGINTIME_KEY
)A4 ON A.DATE_KEY=A4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN 

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) BORNOMALA_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID IN (300034,400015)
GROUP BY V387_CHARGINGTIME_KEY
)B1 ON A.DATE_KEY=B1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) BORNOMALA_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID IN (300034,400015)
GROUP BY G383_CHARGINGTIME_KEY
)B2 ON A.DATE_KEY=B2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) BORNOMALA_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID IN (300034,400015)
GROUP BY S387_CHARGINGTIME_KEY
)B3 ON A.DATE_KEY=B3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) BORNOMALA_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID IN (300034,400015)
GROUP BY R377_CYCLEBEGINTIME_KEY
)B4 ON A.DATE_KEY=B4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) CORPORATE_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID IN (200002,300022,300042,449066,449073,410010,410008,410009,449103,200001)
GROUP BY V387_CHARGINGTIME_KEY
)C1 ON A.DATE_KEY=C1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) CORPORATE_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID IN (200002,300022,300042,449066,449073,410010,410008,410009,449103,200001)
GROUP BY G383_CHARGINGTIME_KEY
)C2 ON A.DATE_KEY=C2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) CORPORATE_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID IN (200002,300022,300042,449066,449073,410010,410008,410009,449103,200001)
GROUP BY S387_CHARGINGTIME_KEY
)C3 ON A.DATE_KEY=C3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) CORPORATE_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID IN (200002,300022,300042,449066,449073,410010,410008,410009,449103,200001)
GROUP BY R377_CYCLEBEGINTIME_KEY
)C4  ON A.DATE_KEY=C4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) MAYERHASHI_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID =400018
GROUP BY V387_CHARGINGTIME_KEY
)D1 ON A.DATE_KEY=D1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) MAYERHASHI_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID =400018
GROUP BY G383_CHARGINGTIME_KEY
)D2 ON A.DATE_KEY=D2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) MAYERHASHI_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID =400018
GROUP BY S387_CHARGINGTIME_KEY
)D3 ON A.DATE_KEY=D3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) MAYERHASHI_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID =400018
GROUP BY R377_CYCLEBEGINTIME_KEY
)D4  ON A.DATE_KEY=D4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) OPORAJITA_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID =400019
GROUP BY V387_CHARGINGTIME_KEY
)E1 ON A.DATE_KEY=E1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) OPORAJITA_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID =400019
GROUP BY G383_CHARGINGTIME_KEY
)E2 ON A.DATE_KEY=E2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) OPORAJITA_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID =400019
GROUP BY S387_CHARGINGTIME_KEY
)E3 ON A.DATE_KEY=E3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) OPORAJITA_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID =400019
GROUP BY R377_CYCLEBEGINTIME_KEY
)E4 ON A.DATE_KEY=E4.R377_CYCLEBEGINTIME_KEY
                                                      
LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) PCO_VOICE_REVENUE FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID IN (200003,300023)
GROUP BY V387_CHARGINGTIME_KEY
)F1 ON A.DATE_KEY=F1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) PCO_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID IN (200003,300023)
GROUP BY G383_CHARGINGTIME_KEY
)F2 ON A.DATE_KEY=F2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) PCO_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID IN (200003,300023)
GROUP BY S387_CHARGINGTIME_KEY
)F3 ON A.DATE_KEY=F3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) PCO_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID IN (200003,300023)
GROUP BY R377_CYCLEBEGINTIME_KEY
)F4 ON A.DATE_KEY=F4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) PROJONMO_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID IN (410004,410000,410001,410002)
GROUP BY V387_CHARGINGTIME_KEY
)G1 ON A.DATE_KEY=G1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN 

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) PROJONMO_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID IN (410004,410000,410001,410002)
GROUP BY G383_CHARGINGTIME_KEY
)G2 ON A.DATE_KEY=G2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) PROJONMO_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID IN (410004,410000,410001,410002)
GROUP BY S387_CHARGINGTIME_KEY
)G3 ON A.DATE_KEY=G3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) PROJONMO_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID IN (410004,410000,410001,410002)
GROUP BY R377_CYCLEBEGINTIME_KEY
)G4 ON A.DATE_KEY=G4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) SAGOTOM_VOICE_REVENUE FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID =479662
GROUP BY V387_CHARGINGTIME_KEY
)H1 ON A.DATE_KEY=H1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) SAGOTOM_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID =479662
GROUP BY G383_CHARGINGTIME_KEY
)H2 ON A.DATE_KEY=H2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) SAGOTOM_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID =479662
GROUP BY S387_CHARGINGTIME_KEY
)H3 ON A.DATE_KEY=H3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) SAGOTOM_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID =479662
GROUP BY R377_CYCLEBEGINTIME_KEY
)H4 ON A.DATE_KEY=H4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) SHADHEEN_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID IN (410006,300031,300041,300010,410007)
GROUP BY V387_CHARGINGTIME_KEY
)I1 ON A.DATE_KEY=I1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) SHADHEEN_DATA_REVENUE FROM L3_DATA P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID IN (410006,300031,300041,300010,410007)
GROUP BY G383_CHARGINGTIME_KEY
)I2 ON A.DATE_KEY=I2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) SHADHEEN_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID IN (410006,300031,300041,300010,410007)
GROUP BY S387_CHARGINGTIME_KEY
)I3 ON A.DATE_KEY=I3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) SHADHEEN_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID IN (410006,300031,300041,300010,410007)
GROUP BY R377_CYCLEBEGINTIME_KEY
)I4 ON A.DATE_KEY=I4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) YOUTH3G_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID =400014
GROUP BY V387_CHARGINGTIME_KEY
)J1 ON A.DATE_KEY=J1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) YOUTH3G_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID =400014
GROUP BY G383_CHARGINGTIME_KEY
)J2 ON A.DATE_KEY=J2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) YOUTH3G_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID =400014
GROUP BY S387_CHARGINGTIME_KEY
)J3 ON A.DATE_KEY=J3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) YOUTH3G_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID =400014
GROUP BY R377_CYCLEBEGINTIME_KEY
)J4 ON A.DATE_KEY=J4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) YOUTHDF_VOICE_REVENUE FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID =400017
GROUP BY V387_CHARGINGTIME_KEY
)H1 ON A.DATE_KEY=H1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) YOUTHDF_DATA_REVENUE FROM L3_DATA P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID =400017
GROUP BY G383_CHARGINGTIME_KEY
)H2 ON A.DATE_KEY=H2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) YOUTHDF_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID =400017
GROUP BY S387_CHARGINGTIME_KEY
)H3 ON A.DATE_KEY=H3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) YOUTHDF_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID =400017
GROUP BY R377_CYCLEBEGINTIME_KEY
)H4 ON A.DATE_KEY=H4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) YOUTHRC_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID =400016
GROUP BY V387_CHARGINGTIME_KEY
)I1 ON A.DATE_KEY=I1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) YOUTHRC_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID =400016
GROUP BY G383_CHARGINGTIME_KEY
)I2 ON A.DATE_KEY=I2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) YOUTHRC_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID =400016
GROUP BY S387_CHARGINGTIME_KEY
)I3 ON A.DATE_KEY=I3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) YOUTHRC_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID =400016
GROUP BY R377_CYCLEBEGINTIME_KEY
)I4 ON A.DATE_KEY=I4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) YOUTH_VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND V397_MAINOFFERINGID =300050
GROUP BY V387_CHARGINGTIME_KEY
)J1 ON A.DATE_KEY=J1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) YOUTH_DATA_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND G401_MAINOFFERINGID =300050
GROUP BY G383_CHARGINGTIME_KEY
)J2 ON A.DATE_KEY=J2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) YOUTH_SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND S395_MAINOFFERINGID =300050
GROUP BY S387_CHARGINGTIME_KEY
)J3 ON A.DATE_KEY=J3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) YOUTH_RECURRING_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R373_MAINOFFERINGID =300050
GROUP BY R377_CYCLEBEGINTIME_KEY
)J4 ON A.DATE_KEY=J4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY,SUM (V41_DEBIT_AMOUNT) VOICE_REVENUE FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
GROUP BY V387_CHARGINGTIME_KEY
)K1 ON A.DATE_KEY=K1.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY,SUM (G41_DEBIT_AMOUNT) DATA_PPU_REVENUE FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
GROUP BY G383_CHARGINGTIME_KEY
)K2 ON A.DATE_KEY=K2.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY,SUM (S41_DEBIT_AMOUNT) SMS_REVENUE FROM L3_SMS  P
WHERE S387_CHARGINGTIME_KEY  =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
GROUP BY S387_CHARGINGTIME_KEY
)K3 ON A.DATE_KEY=K3.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) RECURRING_VOICE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Voice')
GROUP BY R377_CYCLEBEGINTIME_KEY
)L1 ON A.DATE_KEY=L1.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) RECURRING_DATA FROM L3_RECURRING   P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Data')
GROUP BY R377_CYCLEBEGINTIME_KEY
)L2 ON A.DATE_KEY=L2.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) RECURRING_SMS FROM L3_RECURRING   P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='SMS')
GROUP BY R377_CYCLEBEGINTIME_KEY
)L3 ON A.DATE_KEY=L3.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) TOTAL_COMBO FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Combo')
GROUP BY R377_CYCLEBEGINTIME_KEY
)L4 ON A.DATE_KEY=L4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) EXCLUSIVE_DATA_PACK FROM L3_RECURRING    P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R385_OFFERINGID IN ( SELECT OFFER_ID FROM OFFER_CAT_DIM WHERE CAT='Exclusive')
GROUP BY R377_CYCLEBEGINTIME_KEY
)M1 ON A.DATE_KEY=M1.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) REGULAR_DATA_PACK FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R385_OFFERINGID IN ( SELECT OFFER_ID FROM OFFER_CAT_DIM WHERE CAT='Regular')
GROUP BY R377_CYCLEBEGINTIME_KEY
)M2 ON A.DATE_KEY=M2.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) OTHER_DATA_PACK FROM L3_RECURRING   P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
AND R385_OFFERINGID NOT IN ( SELECT OFFER_ID FROM OFFER_CAT_DIM )
GROUP BY R377_CYCLEBEGINTIME_KEY
)M3 ON A.DATE_KEY=M3.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY,SUM (R41_DEBIT_AMOUNT) BUNDLE_REVENUE FROM L3_RECURRING  P
WHERE R377_CYCLEBEGINTIME_KEY  = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TRUNC(TO_DATE(SYSDATE-2,'DD/MM/RRRR'))))
GROUP BY R377_CYCLEBEGINTIME_KEY
)M4 ON A.DATE_KEY=M4.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(
SELECT /*+PARALLEL(P,8)*/ RE30_ENTRY_DATE_KEY ,SUM(RE3_RECHARGE_AMT) RECHARGE_AMOUNT FROM L3_RECHARGE  P
WHERE RE30_ENTRY_DATE_KEY = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))
GROUP BY RE30_ENTRY_DATE_KEY
)N1 ON A.DATE_KEY=N1.RE30_ENTRY_DATE_KEY
)BB

WHERE AA.DATE_KEY=BB.DATE_KEY ;
    COMMIT;
END;
/

