--
-- R_CBS_REPORT_1  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_CBS_REPORT_1 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE CBS_REPORT_1 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO CBS_REPORT_1




SELECT DATE_VALUE ,DURATION,COUNT_CALL,RECHARGE_AMOUNT,VOICE_TK,DATA_TK,SMS_TK,VDATE_KEY FROM DATE_DIM K,
(SELECT A.DATE_KEY,DURATION,COUNT_CALL,RECHARGE_AMOUNT,COALESCE (VOICE_PAYG_TK, 0)+ COALESCE (VOICE_BUNDLE_REVENUE, 0) VOICE_TK,
        COALESCE (DATA_PAYG_REVENUE, 0)+ COALESCE (DATA_BUNDLE_REVENUE, 0) DATA_TK, COALESCE (SMS_PAYG_REVENUE, 0)+ COALESCE (SMS_BUNDLE_REVENUE, 0) SMS_TK
       

FROM 
(SELECT DATE_KEY FROM DATE_DIM 
WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                                     
)A

LEFT OUTER JOIN

(SELECT  /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY ,SUM(V35_RATE_USAGE)/60 DURATION, SUM(V41_DEBIT_AMOUNT) VOICE_PAYG_TK FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                                      

GROUP BY V387_CHARGINGTIME_KEY 
)B ON A.DATE_KEY=B.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT  /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY ,COUNT(*) COUNT_CALL FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                                    

GROUP BY V387_CHARGINGTIME_KEY 
)C ON A.DATE_KEY=C.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT  /*+PARALLEL(P,8)*/ RE30_ENTRY_DATE_KEY , SUM(RE3_RECHARGE_AMT) RECHARGE_AMOUNT FROM L3_RECHARGE P
WHERE RE30_ENTRY_DATE_KEY= (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                                       

GROUP BY RE30_ENTRY_DATE_KEY 
)D ON A.DATE_KEY=D.RE30_ENTRY_DATE_KEY

LEFT OUTER JOIN

(SELECT  /*+PARALLEL(P,8)*/ G383_CHARGINGTIME_KEY , SUM(G41_DEBIT_AMOUNT) DATA_PAYG_REVENUE FROM L3_DATA P
WHERE G383_CHARGINGTIME_KEY= (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                                      

GROUP BY G383_CHARGINGTIME_KEY 
)E  ON A.DATE_KEY=E.G383_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT  /*+PARALLEL(P,8)*/ S387_CHARGINGTIME_KEY , SUM(S41_DEBIT_AMOUNT) SMS_PAYG_REVENUE FROM L3_SMS P
WHERE S387_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                                    
GROUP BY S387_CHARGINGTIME_KEY 
)F  ON A.DATE_KEY=F.S387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT  /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY , SUM(R41_DEBIT_AMOUNT) VOICE_BUNDLE_REVENUE FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                         
      AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Voice')
GROUP BY R377_CYCLEBEGINTIME_KEY 
)G  ON A.DATE_KEY=G.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT  /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY , SUM(R41_DEBIT_AMOUNT) DATA_BUNDLE_REVENUE FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                              
      AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Data')
GROUP BY R377_CYCLEBEGINTIME_KEY 
)H  ON A.DATE_KEY=H.R377_CYCLEBEGINTIME_KEY

LEFT OUTER JOIN

(SELECT  /*+PARALLEL(P,8)*/ R377_CYCLEBEGINTIME_KEY , SUM(R41_DEBIT_AMOUNT) SMS_BUNDLE_REVENUE FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                                       
      AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='SMS')
GROUP BY R377_CYCLEBEGINTIME_KEY 
)I  ON A.DATE_KEY=I.R377_CYCLEBEGINTIME_KEY
)L
WHERE K.DATE_KEY=L.DATE_KEY

;
    COMMIT;
END;
/

