--
-- R_CBS_REPORT_3_SYSDATE2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_CBS_REPORT_3_SYSDATE2 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE CBS_REPORT_3 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO CBS_REPORT_3





SELECT DATE_VALUE,SUB_MADE_CALL,SUB_USAGE_DATA,VDATE_KEY FROM DATE_DIM R,

(SELECT A.DATE_KEY,SUB_MADE_CALL,SUB_USAGE_DATA FROM
(SELECT DATE_KEY FROM DATE_DIM 
WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
                                                      
                                                       
)A

LEFT OUTER JOIN

(
SELECT V387_CHARGINGTIME_KEY,COUNT(V372_CALLINGPARTYNUMBER) SUB_MADE_CALL FROM
(SELECT  /*+PARALLEL(P,8)*/ V387_CHARGINGTIME_KEY ,V372_CALLINGPARTYNUMBER FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
                                                     
      AND V378_SERVICEFLOW=1

GROUP BY V387_CHARGINGTIME_KEY ,V372_CALLINGPARTYNUMBER
)
GROUP BY V387_CHARGINGTIME_KEY
)B ON A.DATE_KEY=B.V387_CHARGINGTIME_KEY


LEFT OUTER JOIN


(

SELECT G383_CHARGINGTIME_KEY,COUNT(G372_CALLINGPARTYNUMBER) SUB_USAGE_DATA FROM
(SELECT  /*+PARALLEL(Q,8)*/ G383_CHARGINGTIME_KEY ,G372_CALLINGPARTYNUMBER FROM L3_DATA Q
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
                                                      

GROUP BY G383_CHARGINGTIME_KEY ,G372_CALLINGPARTYNUMBER
)
GROUP BY G383_CHARGINGTIME_KEY
)C ON A.DATE_KEY=C.G383_CHARGINGTIME_KEY
)S

WHERE R.DATE_KEY=S.DATE_KEY
;
    COMMIT;
END;
/

