--
-- R_DMS_RETAILER_SALES_SUMMARY  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_DMS_RETAILER_SALES_SUMMARY IS
    VDATE_KEY       VARCHAR2(64 BYTE);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE DMS_RETAILER_SALES_SUMMARY WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO DMS_RETAILER_SALES_SUMMARY

SELECT LFTPOINT_NAME,CUSTOMER_NAME DEALER_NAME,MST_SIM_NO DEALER_MST_SIM_NO,SR_NAME,RETAILER_NAME,RET_TELECHARGE_NO TELECHARGE_NO,
       TRANSACTION_COUNT,TOTAL_TAKA,VDATE_KEY
FROM 
(SELECT LFTPOINT_NO, LFTPOINT_NAME FROM DM_LIFTINGPOINT@DWH05TODWH_DMS
)A
INNER JOIN
(SELECT * FROM 
(select CUSTOMER_NO, DIST_LIFTING_POINT, MST_SIM_NO from DM_DEALER_INFO@DWH05TODWH_DMS
)A
INNER JOIN
(
SELECT CUSTOMER_NO, CUSTOMER_NAME FROM BMS.SL_CUSTOMER@DWH05TODWH_DMS
)B ON A.CUSTOMER_NO=B.CUSTOMER_NO
INNER JOIN
(SELECT * FROM
(SELECT SR_NO, DEALER_NO, SR_NAME, TELECHARGE_NO FROM DM_SR_INFO@DWH05TODWH_DMS
)A
INNER JOIN
(SELECT * FROM 
(SELECT RETAILER_NAME, SR_NO, TELECHARGE_NO RET_TELECHARGE_NO FROM DM_RETAILER_INFO@DWH05TODWH_DMS
)A
INNER JOIN
(SELECT /*+PARALLEL P,16*/ ER03_MSISDN_DEALER, COUNT(ER10_MSISDN) TRANSACTION_COUNT, SUM(ER09_PRICE) TOTAL_TAKA FROM L3_EVCREC P
WHERE ER12_RECHARGE_DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS='0'
GROUP BY ER03_MSISDN_DEALER
)B ON A.RET_TELECHARGE_NO=B.ER03_MSISDN_DEALER
)B ON A.SR_NO=B.SR_NO
)C ON A.CUSTOMER_NO=C.DEALER_NO
)B ON A.LFTPOINT_NO=B.DIST_LIFTING_POINT;
      COMMIT;
END;
/

