--
-- R_EVC_BKASH_DBBL_NOGOD  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_EVC_BKASH_DBBL_NOGOD IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE EVC_BKASH_DBBL_NOGOD WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO EVC_BKASH_DBBL_NOGOD





SELECT DATE_VALUE, BKASH_RECHARGE_AMOUNT, DBBL_RECHARGE_AMOUNT, NAGAD_RECHARGE_AMOUNT, 
      TOTAL_TELECHARGE_AMOUNT,VDATE_KEY
FROM DATE_DIM E,
(SELECT A.DATE_KEY, COALESCE (BKASH_RECHARGE_AMOUNT, 0)BKASH_RECHARGE_AMOUNT, COALESCE (DBBL_RECHARGE_AMOUNT, 0)DBBL_RECHARGE_AMOUNT,
        COALESCE (NAGAD_RECHARGE_AMOUNT, 0) NAGAD_RECHARGE_AMOUNT ,COALESCE (TOTAL_TELECHARGE_AMOUNT, 0)TOTAL_TELECHARGE_AMOUNT
FROM
(SELECT DATE_KEY FROM DATE_DIM
WHERE DATE_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-2,'DD/MM/RRRR'))
    
)A

LEFT OUTER JOIN

(SELECT ER12_RECHARGE_DATE_KEY,SUM(ER09_PRICE) NAGAD_RECHARGE_AMOUNT FROM L3_EVCREC
WHERE ER03_MSISDN_DEALER='8801513905199'
AND ER12_RECHARGE_DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-2,'DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0
      
GROUP BY ER12_RECHARGE_DATE_KEY
)B ON A.DATE_KEY=B.ER12_RECHARGE_DATE_KEY

LEFT OUTER JOIN

(SELECT ER12_RECHARGE_DATE_KEY,SUM(ER09_PRICE) BKASH_RECHARGE_AMOUNT FROM L3_EVCREC
WHERE ER03_MSISDN_DEALER IN ('8801553921700','8801553921702')
AND ER12_RECHARGE_DATE_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-2,'DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0

GROUP BY ER12_RECHARGE_DATE_KEY
)C ON A.DATE_KEY=C.ER12_RECHARGE_DATE_KEY

LEFT OUTER JOIN

(SELECT ER12_RECHARGE_DATE_KEY,SUM(ER09_PRICE) DBBL_RECHARGE_AMOUNT FROM L3_EVCREC
WHERE ER03_MSISDN_DEALER='8801553947096'
AND ER12_RECHARGE_DATE_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-2,'DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0
     
GROUP BY ER12_RECHARGE_DATE_KEY
)D ON A.DATE_KEY=D.ER12_RECHARGE_DATE_KEY

LEFT OUTER JOIN 

(SELECT ER12_RECHARGE_DATE_KEY,SUM(ER09_PRICE) TOTAL_TELECHARGE_AMOUNT FROM L3_EVCREC
WHERE  ER12_RECHARGE_DATE_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-2,'DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0
     
GROUP BY ER12_RECHARGE_DATE_KEY
)E ON A.DATE_KEY=E.ER12_RECHARGE_DATE_KEY
)F 
WHERE  E.DATE_KEY=F.DATE_KEY
ORDER BY DATE_VALUE
;
    COMMIT;
END;
/

