--
-- R_EVC_RETAILER_BASIC_SALES  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_EVC_RETAILER_BASIC_SALES IS
    VDATE_KEY       VARCHAR2(64 BYTE);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE EVC_RETAILER_BASIC_SALES WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO EVC_RETAILER_BASIC_SALES

SELECT  /*+PARALLEL(A,15)*/ RETAILER_NAME,D.RETAILER_ID,SR_NAME, COALESCE (T0TAL_SALES, 0)T0TAL_SALES, COALESCE (SURVED_SUBSCRIBERS, 0)SURVED_SUBSCRIBERS,
        COALESCE (VOICE_OFFER_AMOUNGT, 0)VOICE_OFFER_AMOUNGT, COALESCE (DATA_OFFER_AMOUNGT, 0)DATA_OFFER_AMOUNGT,
         COALESCE (NEW_SIM_ACTIVATION, 0)NEW_SIM_ACTIVATION, COALESCE (SIM_REPLACEMENT, 0)SIM_REPLACEMENT,VDATE_KEY 

FROM L3_EVCTRA A, DM_SR_INFO@DWH05TODWH_DMS B,DM_RETAILER_INFO@DWH05TODWH_DMS C,


(SELECT RETAILER_ID,T0TAL_SALES,SURVED_SUBSCRIBERS,VOICE_OFFER_AMOUNGT,DATA_OFFER_AMOUNGT,NEW_SIM_ACTIVATION,SIM_REPLACEMENT FROM

(SELECT /*+PARALLEL(Q,15)*/ ER03_MSISDN_DEALER RETAILER_ID,SUM(ER09_PRICE) T0TAL_SALES
                             
FROM L3_EVCREC Q
WHERE (ER12_RECHARGE_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-15,'DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND ER15_TRANSACTION_STATUS=0
GROUP BY ER03_MSISDN_DEALER
)A

LEFT OUTER JOIN

(select ER03_MSISDN_DEALER,count(ER10_MSISDN) SURVED_SUBSCRIBERS
from
(
(SELECT /*+PARALLEL(Q,15)*/ ER03_MSISDN_DEALER, ER10_MSISDN
                             
FROM L3_EVCREC Q
WHERE (ER12_RECHARGE_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-15,'DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND ER15_TRANSACTION_STATUS=0
GROUP BY ER03_MSISDN_DEALER,ER10_MSISDN
)
UNION
(select  /*+PARALLEL(Q,15)*/ PROCESSED_BY,MSISDN

from L3_ETSAF Q

where 
(ENTRY_DATE BETWEEN (TO_DATE(SYSDATE-15,'DD-Month-RRRR'))
                                                       AND  (TO_DATE(SYSDATE-1,'DD-Month-RRRR')))

AND TYPE iN ('SIM_REPLACEMENT','NEW_PREPAID')
group by PROCESSED_BY,MSISDN
)
)
GROUP BY ER03_MSISDN_DEALER
)B ON A.RETAILER_ID=B.ER03_MSISDN_DEALER

LEFT OUTER JOIN

(SELECT /*+PARALLEL(Q,15)*/ ER03_MSISDN_DEALER,SUM(ER09_PRICE) VOICE_OFFER_AMOUNGT
                             
FROM L3_EVCREC Q
WHERE (ER12_RECHARGE_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-15,'DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND ER15_TRANSACTION_STATUS=0
AND ER09_PRICE IN( SELECT RCG_AMOUNT FROM OFFER_AMNT
 WHERE OFFERING_ID IN (SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Voice')
 GROUP BY RCG_AMOUNT)
GROUP BY ER03_MSISDN_DEALER
)C ON A.RETAILER_ID=C.ER03_MSISDN_DEALER

LEFT OUTER JOIN

(SELECT /*+PARALLEL(Q,15)*/ ER03_MSISDN_DEALER,SUM(ER09_PRICE) DATA_OFFER_AMOUNGT
                             
FROM L3_EVCREC Q
WHERE (ER12_RECHARGE_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-15,'DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND ER15_TRANSACTION_STATUS=0
AND ER09_PRICE IN( SELECT RCG_AMOUNT FROM OFFER_AMNT
 WHERE OFFERING_ID IN (SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Data')
 GROUP BY RCG_AMOUNT)
GROUP BY ER03_MSISDN_DEALER
)D ON A.RETAILER_ID=D.ER03_MSISDN_DEALER

LEFT OUTER JOIN

(select /*+PARALLEL(Q,15)*/ PROCESSED_BY,count(*) NEW_SIM_ACTIVATION

from L3_ETSAF Q

where 
(ENTRY_DATE BETWEEN (TO_DATE(SYSDATE-15,'DD-Month-RRRR'))
                                                       AND  (TO_DATE(SYSDATE-1,'DD-Month-RRRR')))

AND TYPE='NEW_PREPAID'
group by PROCESSED_BY
)E ON A.RETAILER_ID=E.PROCESSED_BY

LEFT OUTER JOIN

(select /*+PARALLEL(Q,15)*/ PROCESSED_BY,count(*) SIM_REPLACEMENT

from L3_ETSAF Q

where 
(ENTRY_DATE BETWEEN (TO_DATE(SYSDATE-15,'DD-Month-RRRR'))
                                                       AND  (TO_DATE(SYSDATE-1,'DD-Month-RRRR')))

AND TYPE='SIM_REPLACEMENT'
group by PROCESSED_BY
)F ON A.RETAILER_ID=F.PROCESSED_BY


)D

WHERE D.RETAILER_ID=A.ET06_MSISDN_BENEFICIARY 
AND D.RETAILER_ID=C.TELECHARGE_NO 
AND B.TELECHARGE_NO=A.ET03_MSISDN_DEALER;
      COMMIT;
END;
/

