--
-- R_EVC_AMOUNT_SR_TO_RETAILER_TRAN  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_EVC_AMOUNT_SR_TO_RETAILER_TRAN IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE EVC_AMOUNT_SR_TO_RETAILER_TRAN WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO EVC_AMOUNT_SR_TO_RETAILER_TRAN



SELECT A.ET03_MSISDN_DEALER,B.ET06_MSISDN_BENEFICIARY, COALESCE (TOTAL_AMOUNT, 0)TOTAL_AMOUNT,
        COALESCE (RETAILER_BASED_AMOUNT, 0)RETAILER_BASED_AMOUNT,VDATE_KEY
FROM
(SELECT /*+PARALLEL(P,8)*/ ET03_MSISDN_DEALER,SUM(ET09_PRICE_TYPE) TOTAL_AMOUNT FROM L3_EVCTRA P
WHERE ET12_TRANSFER_DATE_KEY =(SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
    
      AND ET13_STATE=0
GROUP BY ET03_MSISDN_DEALER     
)A

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ ET03_MSISDN_DEALER,ET06_MSISDN_BENEFICIARY,SUM(ET09_PRICE_TYPE) RETAILER_BASED_AMOUNT FROM L3_EVCTRA P
WHERE ET12_TRANSFER_DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))

      AND ET13_STATE=0
GROUP BY ET03_MSISDN_DEALER ,ET06_MSISDN_BENEFICIARY
)B ON  A.ET03_MSISDN_DEALER=B.ET03_MSISDN_DEALER

ORDER BY ET03_MSISDN_DEALER
;
    COMMIT;
END;
/

