--
-- R_MKT_VOICE_AND_DATA_USAGE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_VOICE_AND_DATA_USAGE IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_VOICE_AND_DATA_USAGE WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_VOICE_AND_DATA_USAGE



SELECT DATE_VALUE ,DIVISION, DISTRICT,UPAZILA ,SITE_ID,MO_VOICE_DURATION_MINS,DATA_USAGE_MB,VDATE_KEY
 FROM
(SELECT DATE_VALUE ,DIVISION, DISTRICT,UPAZILA ,SITE_ID ,SUM(MO_VOICE_DURATION_MINS)MO_VOICE_DURATION_MINS,SUM(DATA_USAGE_MB)DATA_USAGE_MB
FROM
(SELECT /*+PARALLEL(Q,15)*/ DATE_VALUE,INITCAP(SITE_ID)SITE_ID , INITCAP(UPAZILA)UPAZILA, INITCAP(DISTRICT)DISTRICT, INITCAP(DIVISION)DIVISION
       , COALESCE (MO_VOICE_DURATION_MINS, 0) MO_VOICE_DURATION_MINS,  COALESCE (DATA_USAGE_MB, 0)DATA_USAGE_MB
FROM 
(select/*+PARALLEL(B,7)*//*+PARALLEL(C,17)*/ A.CGI,A.DATE_KEY ,MO_VOICE_DURATION_MINS,DATA_USAGE_MB from 
(SELECT CGI,DATE_KEY FROM
(SELECT CGI FROM SHAHIN_NEW_SITE_ID_DIM),
(SELECT DATE_KEY FROM DATE_DIM 
      WHERE DATE_VALUE =(TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
)
                                                    
)A

left outer join

(SELECT /*+PARALLEL(Q,15)*/V381_CALLINGCELLID,V387_CHARGINGTIME_KEY, SUM(V35_RATE_USAGE)/60 MO_VOICE_DURATION_MINS
FROM L3_VOICE  Q
WHERE (V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
      )
      AND V378_SERVICEFLOW='1'
GROUP BY V381_CALLINGCELLID,V387_CHARGINGTIME_KEY
)B ON A.CGI=B.V381_CALLINGCELLID AND A.DATE_KEY=B.V387_CHARGINGTIME_KEY

LEFT OUTER JOIN

(SELECT /*+PARALLEL(R,15)*/G379_CALLINGCELLID,G383_CHARGINGTIME_KEY, SUM(G384_TOTALFLUX)/1048576 DATA_USAGE_MB 
FROM L3_DATA  R
WHERE (G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
      )
      
GROUP BY G379_CALLINGCELLID,G383_CHARGINGTIME_KEY
)C ON A.CGI=C.G379_CALLINGCELLID AND A.DATE_KEY=C.G383_CHARGINGTIME_KEY


)
 P , AUG_ZONE_DIM_NEW@dwh05todwh01 Q ,DATE_DIM R
WHERE P.CGI=Q.CGI AND  P.DATE_KEY=R.DATE_KEY
)
GROUP BY  DATE_VALUE ,DIVISION, DISTRICT,UPAZILA ,SITE_ID
)
ORDER BY DATE_VALUE;
    COMMIT;
END;
/

