--
-- R_MKT_NEWLY_ACQUISITION_SUBSCRIBER_VOICE_USAGE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_NEWLY_ACQUISITION_SUBSCRIBER_VOICE_USAGE IS
    VDATE_KEY       VARCHAR2(64 BYTE);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_NEWLY_ACQUISITION_SUBSCRIBER_VOICE_USAGE WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_NEWLY_ACQUISITION_SUBSCRIBER_VOICE_USAGE

SELECT /*+PARALLEL(P,8)*//*+PARALLEL(Q,8)*/ V372_CALLINGPARTYNUMBER, V397_MAINOFFERINGID,SUM( V35_RATE_USAGE)/60 FIRST_MONTH_VOICE ,VDATE_KEY
FROM L3_VOICE P, MSIDN_FREE_EXP_DATE Q,L3_ETSAF R

WHERE
P.V372_CALLINGPARTYNUMBER=Q.MSISDN AND  R.MSISDN=P.V372_CALLINGPARTYNUMBER 
AND R.TYPE='NEW_PREPAID'  AND 
(R.ENTRY_DATE BETWEEN (TO_DATE(sysdate-65,'DD-Month-RRRR'))
                                                       AND  (TO_DATE(sysdate-35,'DD-Month-RRRR')))
and
(V387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE =DATE1+1)
                                                       AND  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE =DATE1+30))
GROUP BY V372_CALLINGPARTYNUMBER, V397_MAINOFFERINGID;
      COMMIT;
END;
/

