--
-- R_MKT_BUNDLE_OFFER_USAGE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_BUNDLE_OFFER_USAGE IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_BUNDLE_OFFER_USAGE WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_BUNDLE_OFFER_USAGE



SELECT A.R375_CHARGINGPARTYNUMBER,A.OFFER_TYPE, COALESCE (A.NUMBER_OF_PURCHASE, 0)NUMBER_OF_PURCHASE,
        COALESCE (B.MOC_USAGE, 0)MOC_USAGE, COALESCE (C.MOC_ONNET_USAGE, 0)MOC_ONNET_USAGE,
         COALESCE (D.MOC_0FFNET_USAGE, 0)MOC_0FFNET_USAGE, COALESCE (E.MOC_SMS_COUNT, 0) MOC_SMS_COUNT,VDATE_KEY

FROM

(SELECT R375_CHARGINGPARTYNUMBER,OFFER_TYPE, SUM(NUMBER_OF_PURCHASE) NUMBER_OF_PURCHASE 
FROM OFFER_DIM,
(SELECT  /*+PARALLEL(P,8)*/ R375_CHARGINGPARTYNUMBER,R385_OFFERINGID, COUNT(*) NUMBER_OF_PURCHASE  FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY =(SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))

GROUP BY R375_CHARGINGPARTYNUMBER,R385_OFFERINGID

)
WHERE R385_OFFERINGID=OFFERING_ID
GROUP BY R375_CHARGINGPARTYNUMBER,OFFER_TYPE
)A


LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V372_CALLINGPARTYNUMBER,OFFER_TYPE ,SUM(MOC_USAGE) MOC_USAGE FROM OFFER_DIM,

(SELECT /*+PARALLEL(P,8)*/  V372_CALLINGPARTYNUMBER,V436_LASTEFFECTOFFERING, SUM( V35_RATE_USAGE)/60 MOC_USAGE
FROM 
L3_VOICE   P
WHERE  V378_SERVICEFLOW=1 AND
 V387_CHARGINGTIME_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))

   AND V436_LASTEFFECTOFFERING IN  ( SELECT OFFERING_ID FROM OFFER_DIM )
GROUP BY V372_CALLINGPARTYNUMBER,V436_LASTEFFECTOFFERING
)P
WHERE V436_LASTEFFECTOFFERING=OFFERING_ID
GROUP BY V372_CALLINGPARTYNUMBER,OFFER_TYPE
)B ON A.R375_CHARGINGPARTYNUMBER=B.V372_CALLINGPARTYNUMBER AND A.OFFER_TYPE=B.OFFER_TYPE

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/V372_CALLINGPARTYNUMBER,OFFER_TYPE ,SUM(MOC_ONNET_USAGE) MOC_ONNET_USAGE FROM OFFER_DIM,

(SELECT /*+PARALLEL(P,8)*/  V372_CALLINGPARTYNUMBER,V436_LASTEFFECTOFFERING, SUM( V35_RATE_USAGE)/60 MOC_ONNET_USAGE 
FROM 
L3_VOICE   P
WHERE  V378_SERVICEFLOW=1 AND V25_USAGE_SERVICE_TYPE=10 AND
V387_CHARGINGTIME_KEY =(SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))

   AND V436_LASTEFFECTOFFERING IN  ( SELECT OFFERING_ID FROM OFFER_DIM )
GROUP BY V372_CALLINGPARTYNUMBER,V436_LASTEFFECTOFFERING
)P
WHERE V436_LASTEFFECTOFFERING=OFFERING_ID
GROUP BY V372_CALLINGPARTYNUMBER,OFFER_TYPE
)C  ON A.R375_CHARGINGPARTYNUMBER=C.V372_CALLINGPARTYNUMBER AND A.OFFER_TYPE=C.OFFER_TYPE

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/ V372_CALLINGPARTYNUMBER,OFFER_TYPE ,SUM(MOC_0FFNET_USAGE) MOC_0FFNET_USAGE FROM OFFER_DIM,

(SELECT /*+PARALLEL(P,8)*/  V372_CALLINGPARTYNUMBER,V436_LASTEFFECTOFFERING, SUM( V35_RATE_USAGE)/60 MOC_0FFNET_USAGE
FROM 
L3_VOICE  P
WHERE  V378_SERVICEFLOW=1 AND V25_USAGE_SERVICE_TYPE=11 AND
V387_CHARGINGTIME_KEY =(SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))

   AND V436_LASTEFFECTOFFERING IN  ( SELECT OFFERING_ID FROM OFFER_DIM)
GROUP BY V372_CALLINGPARTYNUMBER,V436_LASTEFFECTOFFERING
)P
WHERE V436_LASTEFFECTOFFERING=OFFERING_ID
GROUP BY V372_CALLINGPARTYNUMBER,OFFER_TYPE
)D  ON A.R375_CHARGINGPARTYNUMBER=D.V372_CALLINGPARTYNUMBER AND A.OFFER_TYPE=D.OFFER_TYPE

LEFT OUTER JOIN

(SELECT/*+PARALLEL(P,8)*/S22_PRI_IDENTITY,OFFER_TYPE ,SUM(MOC_SMS_COUNT) MOC_SMS_COUNT FROM OFFER_DIM,

(SELECT /*+PARALLEL(P,8)*/  S22_PRI_IDENTITY,S434_LASTEFFECTOFFERING, COUNT(*) MOC_SMS_COUNT
FROM 
L3_SMS P
WHERE  S378_SERVICEFLOW=1 AND
S387_CHARGINGTIME_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))

   AND S434_LASTEFFECTOFFERING IN  ( SELECT OFFERING_ID FROM OFFER_DIM )
GROUP BY S22_PRI_IDENTITY,S434_LASTEFFECTOFFERING
)P
WHERE S434_LASTEFFECTOFFERING=OFFERING_ID
GROUP BY S22_PRI_IDENTITY,OFFER_TYPE
)E  ON A.R375_CHARGINGPARTYNUMBER=E.S22_PRI_IDENTITY AND A.OFFER_TYPE=E.OFFER_TYPE



;
    COMMIT;
END;
/

