--
-- R_MKT_DATA_REVENUE_SYSDATE2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_DATA_REVENUE_SYSDATE2 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_DATA_REVENUE WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_DATA_REVENUE


SELECT PRODUCT_NAME,G372_CALLINGPARTYNUMBER,DATA_PACKAGE_PREPAID,DATA_PACKAGE_POSTPAID,DATA_PAYUSE_REVENUE,DONGLE_ROUTER_DATA_REVENUE,TOTAL_DATA_REVENUE,VDATE_KEY
FROM PRODUCT_DIM,
(SELECT  A.G401_MAINOFFERINGID,A.G372_CALLINGPARTYNUMBER,COALESCE(DATA_PACKAGE_PREPAID,0) DATA_PACKAGE_PREPAID ,COALESCE(DATA_PACKAGE_POSTPAID,0)DATA_PACKAGE_POSTPAID
        ,COALESCE(DATA_PAYUSE_REVENUE,0) DATA_PAYUSE_REVENUE,COALESCE (E.DONGLE_DATATBL_REVENUE, 0)+ COALESCE (F.DONGLE_RECURRINGTBL_REVENUE, 0) DONGLE_ROUTER_DATA_REVENUE ,
        COALESCE (B.DATA_PACKAGE_PREPAID, 0)+ COALESCE (C.DATA_PACKAGE_POSTPAID, 0)+ COALESCE (D.DATA_PAYUSE_REVENUE, 0) TOTAL_DATA_REVENUE
        
        
FROM
(
(SELECT /*+PARALLEL(P,10)*/ G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
FROM L3_DATA P
WHERE G383_CHARGINGTIME_KEY= TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))
       
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
)
UNION
(SELECT /*+PARALLEL(Q,10)*/ R373_MAINOFFERINGID, R375_CHARGINGPARTYNUMBER
FROM L3_RECURRING Q
WHERE R377_CYCLEBEGINTIME_KEY = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))
     
GROUP BY R373_MAINOFFERINGID, R375_CHARGINGPARTYNUMBER
)
)A

LEFT OUTER JOIN

(SELECT /*+PARALLEL(R,10)*/ R373_MAINOFFERINGID,R375_CHARGINGPARTYNUMBER, SUM(R41_DEBIT_AMOUNT) DATA_PACKAGE_PREPAID
FROM L3_RECURRING R
WHERE R377_CYCLEBEGINTIME_KEY = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))

      AND R374_PAYTYPE=0
      AND 
      EXISTS
      ( SELECT * FROM
       (SELECT OFFERING_ID FROM OFFER_DIM
      
        WHERE OFFER_TYPE='Data'
        ) A1
        WHERE A1.OFFERING_ID=R.R385_OFFERINGID
       )
      
      
GROUP BY R373_MAINOFFERINGID,R375_CHARGINGPARTYNUMBER
) B ON A.G401_MAINOFFERINGID=B.R373_MAINOFFERINGID AND A.G372_CALLINGPARTYNUMBER=B.R375_CHARGINGPARTYNUMBER

LEFT OUTER JOIN

(SELECT /*+PARALLEL(S,10)*/ R373_MAINOFFERINGID,R375_CHARGINGPARTYNUMBER, SUM(R41_DEBIT_AMOUNT) DATA_PACKAGE_POSTPAID
FROM L3_RECURRING S
WHERE R377_CYCLEBEGINTIME_KEY = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))

      AND R374_PAYTYPE=1
      AND 
      EXISTS
      ( SELECT * FROM
       (SELECT OFFERING_ID FROM OFFER_DIM
      
        WHERE OFFER_TYPE='Data'
        ) B1
        WHERE B1.OFFERING_ID=S.R385_OFFERINGID
       )
      
      
GROUP BY R373_MAINOFFERINGID,R375_CHARGINGPARTYNUMBER
) C ON A.G401_MAINOFFERINGID=C.R373_MAINOFFERINGID AND A.G372_CALLINGPARTYNUMBER=C.R375_CHARGINGPARTYNUMBER

LEFT OUTER JOIN

(SELECT /*+PARALLEL(T,10)*/ G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER,SUM(G41_DEBIT_AMOUNT) DATA_PAYUSE_REVENUE
FROM L3_DATA T
WHERE G383_CHARGINGTIME_KEY = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))

GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
) D ON A.G401_MAINOFFERINGID=D.G401_MAINOFFERINGID AND A.G372_CALLINGPARTYNUMBER=D.G372_CALLINGPARTYNUMBER

LEFT OUTER JOIN 

(SELECT /*+PARALLEL(U,10)*/ G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER,SUM(G41_DEBIT_AMOUNT) DONGLE_DATATBL_REVENUE
FROM L3_DATA U
WHERE G383_CHARGINGTIME_KEY =TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))

      AND G401_MAINOFFERINGID IN ('449066','449073','410013','449662','449103','400022','400021')
GROUP BY G401_MAINOFFERINGID,G372_CALLINGPARTYNUMBER
)E ON A.G401_MAINOFFERINGID=E.G401_MAINOFFERINGID AND A.G372_CALLINGPARTYNUMBER=E.G372_CALLINGPARTYNUMBER

LEFT OUTER JOIN

(SELECT /*+PARALLEL(R,10)*/ R373_MAINOFFERINGID,R375_CHARGINGPARTYNUMBER, SUM(R41_DEBIT_AMOUNT) DONGLE_RECURRINGTBL_REVENUE
FROM L3_RECURRING R
WHERE R377_CYCLEBEGINTIME_KEY = TO_CHAR((SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR')))

      AND R373_MAINOFFERINGID IN ('449066','449073','410013','449662','449103','400022','400021')
      AND 
      EXISTS
      ( SELECT * FROM
       (SELECT OFFERING_ID FROM OFFER_DIM
      
        WHERE OFFER_TYPE='Data'
        ) A1
        WHERE A1.OFFERING_ID=R.R385_OFFERINGID
       )
      
      
GROUP BY R373_MAINOFFERINGID,R375_CHARGINGPARTYNUMBER
) F ON A.G401_MAINOFFERINGID=F.R373_MAINOFFERINGID AND A.G372_CALLINGPARTYNUMBER=F.R375_CHARGINGPARTYNUMBER
) 

WHERE PRODUCT_ID=G401_MAINOFFERINGID


;
    COMMIT;
END;
/

