--
-- R_MKT_RECHARGE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_RECHARGE IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_RECHARGE WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_RECHARGE

SELECT A.ER10_MSISDN,COALESCE (RECHARGE_AMOUNT, 0)RECHARGE_AMOUNT ,COALESCE (TBL_RECHARGE_AMOUNT, 0)TBL_RECHARGE_AMOUNT,
       COALESCE (OTHER_RECHARGE_AMOUNT, 0)OTHER_RECHARGE_AMOUNT,  COALESCE (BKASH_RECHARGE_AMOUNT, 0)BKASH_RECHARGE_AMOUNT,
         COALESCE (ROCKET_RECHARGE_AMOUNT, 0)ROCKET_RECHARGE_AMOUNT,  COALESCE (NAGAD_RECHARGE_AMOUNT, 0)NAGAD_RECHARGE_AMOUNT, VDATE_KEY
FROM 
(SELECT /*+PARALLEL(P,10)*/ ER10_MSISDN,SUM(ER09_PRICE) RECHARGE_AMOUNT
FROM L3_EVCREC P
WHERE ER12_RECHARGE_DATE_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('31/08/2020','DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0
       
GROUP BY ER10_MSISDN
) A

LEFT OUTER JOIN

(SELECT /*+PARALLEL(Q,10)*/ ER10_MSISDN,SUM(ER09_PRICE) TBL_RECHARGE_AMOUNT
FROM L3_EVCREC Q
WHERE ER12_RECHARGE_DATE_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('31/08/2020','DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0
AND  ER40_UPSTREAM_MSISDN NOT IN ('8801553921699','8801553947095','8801513905196')
       
        AND 
     EXISTS
    
      (SELECT RESELLER_MSISDN FROM DSR_DIM
       WHERE RESELLER_MSISDN=Q.ER03_MSISDN_DEALER
      )
GROUP BY ER10_MSISDN
) B ON A.ER10_MSISDN=B.ER10_MSISDN

LEFT OUTER JOIN

(SELECT /*+PARALLEL(R,10)*/ ER10_MSISDN,SUM(ER09_PRICE) OTHER_RECHARGE_AMOUNT
FROM L3_EVCREC R
WHERE ER12_RECHARGE_DATE_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('31/08/2020','DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0
        
        AND 
     NOT EXISTS
    
      (SELECT RESELLER_MSISDN FROM DSR_DIM
       WHERE RESELLER_MSISDN=R.ER03_MSISDN_DEALER
      )
GROUP BY ER10_MSISDN
) C ON A.ER10_MSISDN=C.ER10_MSISDN

LEFT OUTER JOIN

(SELECT ER10_MSISDN,SUM(ER09_PRICE) BKASH_RECHARGE_AMOUNT FROM L3_EVCREC
WHERE ER40_UPSTREAM_MSISDN='8801553921699'
AND ER12_RECHARGE_DATE_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('31/08/2020','DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0

GROUP BY ER10_MSISDN
)D ON A.ER10_MSISDN=D.ER10_MSISDN

LEFT OUTER JOIN

(SELECT ER10_MSISDN,SUM(ER09_PRICE) ROCKET_RECHARGE_AMOUNT FROM L3_EVCREC
WHERE ER40_UPSTREAM_MSISDN='8801553947095'
AND ER12_RECHARGE_DATE_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('31/08/2020','DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0
     
GROUP BY ER10_MSISDN
)E ON A.ER10_MSISDN=E.ER10_MSISDN

LEFT OUTER JOIN


(SELECT ER10_MSISDN,SUM(ER09_PRICE) NAGAD_RECHARGE_AMOUNT FROM L3_EVCREC
WHERE ER40_UPSTREAM_MSISDN='8801513905196'
AND ER12_RECHARGE_DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('31/08/2020','DD/MM/RRRR'))
AND ER15_TRANSACTION_STATUS=0
      
GROUP BY ER10_MSISDN
)F ON A.ER10_MSISDN=F.ER10_MSISDN


;
    COMMIT;
END;
/

