--
-- R_MKT_BUNDLE_OFFER_USAGE_DATA  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_BUNDLE_OFFER_USAGE_DATA IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_BUNDLE_OFFER_USAGE_DATA WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_BUNDLE_OFFER_USAGE_DATA






SELECT R375_CHARGINGPARTYNUMBER,OFFER_TYPE,NUMBER_OF_PURCHASE,FREE_USAGE_MB,VDATE_KEY FROM 
(SELECT /*+PARALLEL(P,8)*/ R375_CHARGINGPARTYNUMBER,OFFER_TYPE, SUM(NUMBER_OF_PURCHASE) NUMBER_OF_PURCHASE 
FROM OFFER_DIM,
(SELECT  /*+PARALLEL(P,8)*/ R375_CHARGINGPARTYNUMBER,R385_OFFERINGID, COUNT(*) NUMBER_OF_PURCHASE  FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
                                                       
GROUP BY R375_CHARGINGPARTYNUMBER,R385_OFFERINGID

)P
WHERE R385_OFFERINGID=OFFERING_ID
AND OFFER_TYPE='Data'
GROUP BY R375_CHARGINGPARTYNUMBER,OFFER_TYPE
)A

LEFT OUTER JOIN

(SELECT /*+PARALLEL(P,8)*/  G372_CALLINGPARTYNUMBER, sum(G51_FREE_UNIT_AMOUNT_OF_FLUX)/1048576 FREE_USAGE_MB
FROM   L3_DATA  P
WHERE
G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
     
   
GROUP BY G372_CALLINGPARTYNUMBER
)B ON A.R375_CHARGINGPARTYNUMBER=B.G372_CALLINGPARTYNUMBER


;
    COMMIT;
END;
/

