--
-- R_MKT_NEWLY_ACQUISITION_SUBSCRIBER_2ND_MONTH_VOICE_USAGE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_NEWLY_ACQUISITION_SUBSCRIBER_2ND_MONTH_VOICE_USAGE IS
    VDATE_KEY       VARCHAR2(64 BYTE);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_NEWLY_ACQUISITION_SUBSCRIBER_2ND_MONTH_VOICE_USAGE WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_NEWLY_ACQUISITION_SUBSCRIBER_2ND_MONTH_VOICE_USAGE

SELECT /*+PARALLEL(P,14)*/ V372_CALLINGPARTYNUMBER, V397_MAINOFFERINGID,SUM( V35_RATE_USAGE)/60 SECOND_MONTH_VOICE ,VDATE_KEY
FROM L3_VOICE P
WHERE (V387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-60,'DD/MM/RRRR'))
                                                       AND  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-31,'DD/MM/RRRR')))
      AND V378_SERVICEFLOW='1'
      
      
GROUP BY V372_CALLINGPARTYNUMBER, V397_MAINOFFERINGID;
      COMMIT;
END;
/

