--
-- R_MKT_RECHARGE_PART02  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_RECHARGE_PART02 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-2,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_RECHARGE_PART02 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_RECHARGE_PART02

SELECT A.ER10_MSISDN,COALESCE (RECHARGE_AMOUNT, 0)RECHARGE_AMOUNT ,COALESCE (TBL_RECHARGE_AMOUNT, 0)TBL_RECHARGE_AMOUNT,
       COALESCE (OTHER_RECHARGE_AMOUNT, 0)OTHER_RECHARGE_AMOUNT,VDATE_KEY
FROM 
(SELECT /*+PARALLEL(P,10)*/ ER10_MSISDN,SUM(ER09_PRICE) RECHARGE_AMOUNT
FROM L3_EVCREC P
WHERE ER12_RECHARGE_DATE_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
       
GROUP BY ER10_MSISDN
) A

LEFT OUTER JOIN

(SELECT /*+PARALLEL(Q,10)*/ ER10_MSISDN,SUM(ER09_PRICE) TBL_RECHARGE_AMOUNT
FROM L3_EVCREC Q
WHERE ER12_RECHARGE_DATE_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
       
        AND 
     EXISTS
    
      (SELECT RESELLER_MSISDN FROM DSR_DIM
       WHERE RESELLER_MSISDN=Q.ER03_MSISDN_DEALER
      )
GROUP BY ER10_MSISDN
) B ON A.ER10_MSISDN=B.ER10_MSISDN

LEFT OUTER JOIN

(SELECT /*+PARALLEL(R,10)*/ ER10_MSISDN,SUM(ER09_PRICE) OTHER_RECHARGE_AMOUNT
FROM L3_EVCREC R
WHERE ER12_RECHARGE_DATE_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-2,'DD/MM/RRRR'))
        
        AND 
     NOT EXISTS
    
      (SELECT RESELLER_MSISDN FROM DSR_DIM
       WHERE RESELLER_MSISDN=R.ER03_MSISDN_DEALER
      )
GROUP BY ER10_MSISDN
) C ON A.ER10_MSISDN=C.ER10_MSISDN




;
    COMMIT;
END;
/

