--
-- R_MKT_NEWLY_ACQUISITION_SUBSCRIBER_DATA_USAGE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_NEWLY_ACQUISITION_SUBSCRIBER_DATA_USAGE IS
    VDATE_KEY       VARCHAR2(64 BYTE);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_NEWLY_ACQUISITION_SUBSCRIBER_DATA_USAGE WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_NEWLY_ACQUISITION_SUBSCRIBER_DATA_USAGE


(SELECT /*+PARALLEL(P,16)*//*+PARALLEL(Q,16)*/ G372_CALLINGPARTYNUMBER, G401_MAINOFFERINGID,SUM(G384_TOTALFLUX)/1048576 FIRST_MONTH_DATA_MB ,VDATE_KEY
FROM L3_dATA P, MSIDN_FREE_EXP_DATE Q,L3_ETSAF R

WHERE
P.G372_CALLINGPARTYNUMBER=Q.MSISDN AND  R.MSISDN=P.G372_CALLINGPARTYNUMBER
AND R.TYPE='NEW_PREPAID'  AND 
(R.ENTRY_DATE BETWEEN (TO_DATE(SYSDATE-65,'DD-Month-RRRR'))
                                                       AND  (TO_DATE(SYSDATE-35,'DD-Month-RRRR')))
 and 
(G383_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE =Q.DATE1+1)
                                                       AND  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE =Q.DATE1+30))
GROUP BY G372_CALLINGPARTYNUMBER, G401_MAINOFFERINGID

);
      COMMIT;
END;
/

