--
-- R_MKT_CHANNEL_PRO_PURCHASE_PART02  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_CHANNEL_PRO_PURCHASE_PART02 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE MKT_CHANNEL_PRO_PURCHASE_PART02 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MKT_CHANNEL_PRO_PURCHASE_PART02


SELECT A.MSISDN,A.PRODUCT_NAME, COALESCE (ALL_COUNT_AVAIL_SERVICE, 0)- COALESCE (RECHARGE_COUNT_AVAIL_SERVICE, 0) WITHOUT_RECHARGE_AVAIL_SERVICE,
        COALESCE (RECHARGE_COUNT_AVAIL_SERVICE, 0) RECHARGE_COUNT_AVAIL_SERVICE,VDATE_KEY


FROM
(SELECT MSISDN,PRODUCT_NAME,SUM(COUNT_AVAIL_SERVICE ) ALL_COUNT_AVAIL_SERVICE
FROM PRODUCT_DIM,
(SELECT /*+PARALLEL(P,10)*/ R373_MAINOFFERINGID, R375_CHARGINGPARTYNUMBER MSISDN, 
                             COUNT(*) COUNT_AVAIL_SERVICE
FROM 
 L3_RECURRING P 

WHERE R377_CYCLEBEGINTIME_KEY = (SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))

GROUP BY R373_MAINOFFERINGID, R375_CHARGINGPARTYNUMBER
)
WHERE R373_MAINOFFERINGID=PRODUCT_ID 
GROUP BY MSISDN,PRODUCT_NAME
)A 

LEFT OUTER JOIN


(SELECT MSISDN,PRODUCT_NAME,SUM(COUNT_AVAIL_SERVICE ) RECHARGE_COUNT_AVAIL_SERVICE
FROM PRODUCT_DIM,
(SELECT /*+PARALLEL(Q,10)*/ RE489_MAINOFFERINGID, RE6_PRI_IDENTITY MSISDN, 
                             COUNT(*) COUNT_AVAIL_SERVICE
FROM 
 L3_RECHARGE Q
WHERE RE30_ENTRY_DATE_KEY =(SELECT TO_CHAR(DATE_KEY) FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR'))

AND RE3_RECHARGE_AMT IN( SELECT RCG_AMOUNT FROM OFFER_AMNT)
GROUP BY RE489_MAINOFFERINGID, RE6_PRI_IDENTITY
)
WHERE RE489_MAINOFFERINGID=PRODUCT_ID 
GROUP BY MSISDN,PRODUCT_NAME
)B ON A.MSISDN=B.MSISDN AND  A.PRODUCT_NAME=B.PRODUCT_NAME


;
    COMMIT;
END;
/

