--
-- R_MKT_ZONE_WISE_VOICE_DATA_USAGE_NEW  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MKT_ZONE_WISE_VOICE_DATA_USAGE_NEW IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
--DELETE MKT_ZONE_WISE_VOICE_DATA_USAGE WHERE PDR_DATE_KEY=VDATE_KEY;
--COMMIT;
    
INSERT INTO MKT_ZONE_WISE_VOICE_DATA_USAGE_NEW

SELECT/*+PARALLEL(P,15)*/ MSISDN, PRODUCT_NAME, DATE_VALUE, CGI, SITE_ID, UPAZILA, DISTRICT, DIVISION,
 DATA_VOLUME_MB, MOC_DURATION, CHARGING_HOUR, CHARGING_MINUTE,PDR_DATE_KEY
FROM MKT_ZONE_WISE_VOICE_DATA_USAGE P
 
;
    COMMIT;
END;
/

