--
-- R_MSISDN_PRODUCT_VOICE_DATA_REVENUE_RECAHRGE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_MSISDN_PRODUCT_VOICE_DATA_REVENUE_RECAHRGE IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');

    
DELETE MSISDN_PRODUCT_VOICE_DATA_REVENUE_RECAHRGE WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO MSISDN_PRODUCT_VOICE_DATA_REVENUE_RECAHRGE



SELECT /*+PARALLEL(P,15)*/ MSISDN,PRODUCT_ID,DATE_KEY,COALESCE (VOICE_PAYG_REVENUE, 0)VOICE_REVENUE,COALESCE (MO_DURATION_MINS, 0)MO_DURATION_MINS,COALESCE (DATA_PAYG_REVENUE, 0)DATA_REVENUE,
       COALESCE (DATA_USAGE_MB, 0)DATA_USAGE_MB,COALESCE (RECHARGE_AMOUNT, 0)RECHARGE_AMOUNT,VDATE_KEY
FROM
(SELECT  V372_CALLINGPARTYNUMBER MSISDN,V397_MAINOFFERINGID PRODUCT_ID,V387_CHARGINGTIME_KEY DATE_KEY, SUM(VOICE_PAYG_REVENUE) VOICE_PAYG_REVENUE,SUM(MO_DURATION_MINS) MO_DURATION_MINS, SUM(DATA_PAYG_REVENUE) DATA_PAYG_REVENUE,SUM(DATA_USAGE_MB) DATA_USAGE_MB  ,SUM(RECHARGE_AMOUNT) RECHARGE_AMOUNT
FROM
(
(SELECT  /*+PARALLEL(P,15)*/ V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID,V387_CHARGINGTIME_KEY, SUM(V41_DEBIT_AMOUNT) VOICE_PAYG_REVENUE, SUM(V35_RATE_USAGE)/60 MO_DURATION_MINS ,NULL AS DATA_PAYG_REVENUE, NULL AS DATA_USAGE_MB, NULL AS RECHARGE_AMOUNT
FROM L3_VOICE P
WHERE ( V387_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE >= TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
AND V387_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE,'DD/MM/RRRR'))  )
and V378_SERVICEFLOW=1                                                   

GROUP BY V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID,V387_CHARGINGTIME_KEY
)
UNION ALL 
(SELECT  /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER,R373_MAINOFFERINGID,R377_CYCLEBEGINTIME_KEY,SUM(R41_DEBIT_AMOUNT) VOICE_RECURRING_REVENUE ,NULL AS MO_DURATION_MINS, NULL AS DATA_PAYG_REVENUE, NULL AS DATA_USAGE_MB, NULL AS RECHARGE_AMOUNT
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY IN  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE >= TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
      AND R377_CYCLEBEGINTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE,'DD/MM/RRRR')) 
                                         
      AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Voice')
GROUP BY R375_CHARGINGPARTYNUMBER,R373_MAINOFFERINGID,R377_CYCLEBEGINTIME_KEY
)
UNION ALL
(SELECT  /*+PARALLEL(P,8)*/ G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID,G383_CHARGINGTIME_KEY,NULL AS VOICE_PAYG_REVENUE ,NULL AS MO_DURATION_MINS, SUM(G41_DEBIT_AMOUNT) DATA_PAYG_REVENUE,SUM(G384_TOTALFLUX)/1048576 DATA_USAGE_MB , NULL AS RECHARGE_AMOUNT
FROM L3_DATA P
WHERE G383_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE >= TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
        AND G383_CHARGINGTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE,'DD/MM/RRRR'))                                                     

GROUP BY G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID,G383_CHARGINGTIME_KEY
)
UNION ALL
(SELECT  /*+PARALLEL(P,8)*/ R375_CHARGINGPARTYNUMBER,R373_MAINOFFERINGID,R377_CYCLEBEGINTIME_KEY,NULL AS VOICE_PAYG_REVENUE,NULL AS MO_DURATION_MINS,SUM(R41_DEBIT_AMOUNT) DATA_BUNDLE_REVENUE ,NULL AS DATA_USAGE_MB, NULL AS RECHARGE_AMOUNT
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE >= TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
           AND R377_CYCLEBEGINTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE,'DD/MM/RRRR'))                                          
      AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Data')
GROUP BY R375_CHARGINGPARTYNUMBER,R373_MAINOFFERINGID,R377_CYCLEBEGINTIME_KEY
)
UNION ALL 
(SELECT  /*+PARALLEL(P,15)*/ RE6_PRI_IDENTITY,RE489_MAINOFFERINGID,RE30_ENTRY_DATE_KEY,NULL AS VOICE_PAYG_REVENUE,NULL AS MO_DURATION_MINS, NULL AS DATA_BUNDLE_REVENUE, NULL AS DATA_USAGE_MB  ,SUM(RE3_RECHARGE_AMT) RECHARGE_AMOUNT 
FROM L3_RECHARGE P
WHERE RE30_ENTRY_DATE_KEY IN  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE >= TO_DATE(SYSDATE-1,'DD/MM/RRRR'))
          AND RE30_ENTRY_DATE_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE < TO_DATE(SYSDATE,'DD/MM/RRRR'))                                                    

GROUP BY RE6_PRI_IDENTITY,RE489_MAINOFFERINGID,RE30_ENTRY_DATE_KEY
)
)
GROUP BY  V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID,V387_CHARGINGTIME_KEY
)P

;
    COMMIT;
END;
/

