--
-- R_PACKAGE_WISE_DATA_PROFIT_SYS2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_PACKAGE_WISE_DATA_PROFIT_SYS2 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE,'RRRRMMDD');
   

    
INSERT INTO PACKAGE_WISE_DATA_PROFIT



SELECT A.DATE_KEY,
       A.DATE_VALUE,
       A.PRODUCT_ID,
       A.PRODUCT_NAME,
       ROUND (A.DATA_USAGE_MB, 2) DATA_USAGE_MB,
       ROUND (A.PPU_DATA_USAGE_MB, 2) PPU_DATA_USAGE_MB,
       ROUND (A.FREE_DATA_USAGE_MB, 2) FREE_DATA_USAGE_MB,
       ROUND(( (A.FREE_DATA_USAGE_MB * 0.01103515625) - ( (A.FREE_DATA_USAGE_MB * 0.01103515625) * 0.185)),2)
          FREE_DATA_PROFIT,
       ROUND(( (A.PPU_DATA_USAGE_MB * 0.683) - ( (A.PPU_DATA_USAGE_MB * 0.683) * 0.185)),2)
          PPU_DATA_PROFIT
  FROM (  SELECT /*+PARALLEL(L,16)*/
                D.DATE_KEY,
                D.DATE_VALUE,
                 P.PRODUCT_ID,
                 P.PRODUCT_NAME,
                 SUM (L.G384_TOTALFLUX) / 1024 / 1024  DATA_USAGE_MB,
                   SUM (L.G384_TOTALFLUX - L.G51_FREE_UNIT_AMOUNT_OF_FLUX)
                 / 1024
                 / 1024
                    PPU_DATA_USAGE_MB,
                 SUM (L.G51_FREE_UNIT_AMOUNT_OF_FLUX) / 1024 / 1024
                    FREE_DATA_USAGE_MB
            FROM L3_DATA L
                 INNER JOIN DATE_DIM D ON D.DATE_KEY = L.G383_CHARGINGTIME_KEY
                 INNER JOIN PRODUCT_DIM P
                    ON P.PRODUCT_ID = L.G401_MAINOFFERINGID
           WHERE DATE_VALUE = TO_DATE (SYSDATE-2, 'DD/MM/RRRR')
        GROUP BY D.DATE_KEY, D.DATE_VALUE, P.PRODUCT_ID, P.PRODUCT_NAME) A
        ;
             
             
             
      COMMIT;
END;
/

