--
-- R_S_AND_D_REPORT_4  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_S_AND_D_REPORT_4 IS
    VDATE_KEY       VARCHAR2(64 BYTE);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE S_AND_D_REPORT_4 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO S_AND_D_REPORT_4

SELECT N.RETAILER_NAME,N.TELECHARGE_NO, M.PROPITER_NAME, COALESCE (N.TOTAL_TELECHARGE_SALES, 0) TOTAL_TELECHARGE_SALES ,
       COALESCE (N.TBPS_SALES, 0) TBPS_SALES,COALESCE (N.SIM_ACTIVATION, 0) SIM_ACTIVATION,
       COALESCE (N.CARD_SALES, 0) CARD_SALES,COALESCE (N.VOICE_OFFER_AMOUNGT, 0) VOICE_OFFER_AMOUNGT,
       COALESCE (N.DATA_OFFER_AMOUNGT, 0) DATA_OFFER_AMOUNGT ,VDATE_KEY
       
FROM DM_DEALER_INFO@DWH05TODWH_DMS M,

(SELECT P.RETAILER_NAME, P.TELECHARGE_NO, P.DEALER_NO, A.TOTAL_TELECHARGE_SALES ,D.TBPS_SALES,E.SIM_ACTIVATION,F.CARD_SALES,
       B.VOICE_OFFER_AMOUNGT,C.DATA_OFFER_AMOUNGT

FROM DM_RETAILER_INFO@DWH05TODWH_DMS P

LEFT OUTER JOIN

(select /*+PARALLEL(P,8)*/ ER03_MSISDN_DEALER, SUM(ER09_PRICE ) TOTAL_TELECHARGE_SALES
from L3_EVCREC P
where (ER12_RECHARGE_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
                                                       AND  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
 AND ER15_TRANSACTION_STATUS=0
 GROUP BY    ER03_MSISDN_DEALER                                                   
                                                       
)A ON P.TELECHARGE_NO=A.ER03_MSISDN_DEALER


LEFT OUTER JOIN


(SELECT /*+PARALLEL(Q,10)*/ ER03_MSISDN_DEALER,SUM(ER09_PRICE) VOICE_OFFER_AMOUNGT
                             
FROM L3_EVCREC Q
WHERE (ER12_RECHARGE_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND ER15_TRANSACTION_STATUS=0
AND ER09_PRICE IN( SELECT RCG_AMOUNT FROM OFFER_AMNT
 WHERE OFFERING_ID IN (SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Voice')
 GROUP BY RCG_AMOUNT)
GROUP BY ER03_MSISDN_DEALER
)B ON P.TELECHARGE_NO=B.ER03_MSISDN_DEALER


LEFT OUTER JOIN


(SELECT /*+PARALLEL(Q,10)*/ ER03_MSISDN_DEALER,SUM(ER09_PRICE) DATA_OFFER_AMOUNGT
                             
FROM L3_EVCREC Q
WHERE (ER12_RECHARGE_DATE_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND ER15_TRANSACTION_STATUS=0
AND ER09_PRICE IN( SELECT RCG_AMOUNT FROM OFFER_AMNT
 WHERE OFFERING_ID IN (SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Data')
 GROUP BY RCG_AMOUNT)
GROUP BY ER03_MSISDN_DEALER
)C ON  P.TELECHARGE_NO=C.ER03_MSISDN_DEALER

LEFT OUTER JOIN


(select  TELECHARGE_NO ,TBPS_SALES from DM_RETAILER_INFO@DWH05TODWH_DMS A,
(select RET_NO, sum(TBS_ISS) TBPS_SALES from DM_TBS_RET_BALANCE@DWH05TODWH_DMS
where (BALANCE_DATE BETWEEN (TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
                                                       AND  ( TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
group by RET_NO
)B
WHERE A.RETAILER_NO=B.RET_NO
)D ON P.TELECHARGE_NO=D.TELECHARGE_NO


LEFT OUTER JOIN


(select  TELECHARGE_NO ,SIM_ACTIVATION from DM_RETAILER_INFO@DWH05TODWH_DMS A,
(SELECT  /*+PARALLEL(P,8)*/ /*+PARALLEL(Q,8)*/ ISS_2_RETAILER_NO,COUNT(P.ERP_ITEM_NO) SIM_ACTIVATION FROM DM_SR_ITEMISSUEDTL@DWH05TODWH_DMS P,DM_ITEM_MAP@DWH05TODWH_DMS Q 
where (ACTIVATE_DTTM BETWEEN (TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
                                                       AND  ( TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND ACTIVATE_IND='Y'
AND ITEM_GROUP_CODE='S'
AND P.ERP_ITEM_NO=Q.ERP_ITEM_NO
GROUP BY ISS_2_RETAILER_NO
)B
WHERE A.RETAILER_NO=B.ISS_2_RETAILER_NO
)E ON P.TELECHARGE_NO=E.TELECHARGE_NO


LEFT OUTER JOIN



(select  TELECHARGE_NO ,CARD_SALES from DM_RETAILER_INFO@DWH05TODWH_DMS A,
(SELECT  /*+PARALLEL(P,8)*/ /*+PARALLEL(Q,8)*/ ISS_2_RETAILER_NO,SUM(RATE_FOR_TARGET) CARD_SALES FROM DM_SR_ITEMISSUEDTL@DWH05TODWH_DMS P,DM_ITEM_MAP@DWH05TODWH_DMS Q 
where (ISS_2_RETAILER_DTTM BETWEEN (TO_DATE(SYSDATE-30,'DD/MM/RRRR'))
                                                       AND  ( TO_DATE(SYSDATE-1,'DD/MM/RRRR')))
AND ITEM_GROUP_CODE='SC'
AND P.ERP_ITEM_NO=Q.ERP_ITEM_NO
GROUP BY ISS_2_RETAILER_NO
)B
WHERE A.RETAILER_NO=B.ISS_2_RETAILER_NO
)F ON P.TELECHARGE_NO=F.TELECHARGE_NO
)N
WHERE  N.DEALER_NO=M.CUSTOMER_NO;
      COMMIT;
END;
/

