--
-- R_S_AND_D_REPORT_2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_S_AND_D_REPORT_2 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE S_AND_D_REPORT_2 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO S_AND_D_REPORT_2




SELECT SITE_NAME ,FULL_ADDRESS,UPAZILA,DISTRICT,COALESCE (VOICE_REVENUE, 0)+ COALESCE (DATA_REVENUE, 0) TOTAL_REVENUE,
       COALESCE (VOICE_REVENUE, 0)VOICE_REVENUE,COALESCE (DATA_REVENUE, 0)DATA_REVENUE,
       COALESCE (YOUTH_VOICE_REVENUE, 0)+ COALESCE (YOUTH_DATA_REVENUE, 0) YOUTH,COALESCE (AGAMI_VOICE_REVENUE, 0)+ COALESCE (AGAMI_DATA_REVENUE, 0) AGAMI,
       COALESCE (BORNOMALA_VOICE_REVENUE, 0)+ COALESCE (BORNOMALA_DATA_REVENUE, 0) BORNOMALA,COALESCE (SAGOTOM_VOICE_REVENUE, 0)+ COALESCE (SAGOTOM_DATA_REVENUE, 0) SAGOTOM,
       COALESCE (APARAJITA_VOICE_REVENUE, 0)+ COALESCE (APARAJITA_DATA_REVENUE, 0) APARAJITA,COALESCE (MAYERHASHI_VOICE_REVENUE, 0)+ COALESCE (MAYERHASHI_DATA_REVENUE, 0) MAYERHASHI,
       COALESCE (CORPORATE_VOICE_REVENUE, 0)+ COALESCE (CORPORATE_DATA_REVENUE, 0) CORPORATE,COALESCE (MODEM_VOICE_REVENUE, 0)+ COALESCE (MODEM_DATA_REVENUE, 0) MODEM,
       COALESCE (OTHERS_VOICE_REVENUE, 0)+ COALESCE (OTHERS_DATA_REVENUE, 0) OTHER,COALESCE (VOICE_REVENUE_18_26, 0)+ COALESCE (DATA_REVENUE_18_26, 0) AGE18_26,
       COALESCE (VOICE_REVENUE_27_35, 0)+ COALESCE (DATA_REVENUE_27_35, 0) AGE27_35,COALESCE (VOICE_REVENUE_35_45, 0)+ COALESCE (DATA_REVENUE_35_45, 0) AGE35_45,
       COALESCE (VOICE_REVENUE_ABOVE_45, 0)+ COALESCE (DATA_REVENUE_ABOVE_45, 0) AGE_OVER_45,VDATE_KEY


FROM



(SELECT CGI,INITCAP(SITE_NAME) SITE_NAME, INITCAP(FULL_ADDRESS) FULL_ADDRESS,INITCAP(UPAZILA) UPAZILA,INITCAP(DISTRICT) DISTRICT
FROM ZONE_DIM

)A


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) VOICE_REVENUE 
FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                
GROUP BY V381_CALLINGCELLID
)A1 ON A.CGI=A1.V381_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) DATA_REVENUE
FROM L3_DATA P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                     
GROUP BY G379_CALLINGCELLID
)A2 ON A.CGI=A2.G379_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) YOUTH_VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                
AND V397_MAINOFFERINGID in (400014,400017,400016,300050)
GROUP BY V381_CALLINGCELLID
)B1 ON A.CGI=B1.V381_CALLINGCELLID


LEFT OUTER JOIN



(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) YOUTH_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                       
AND G401_MAINOFFERINGID in (400014,400017,400016,300050)
GROUP BY G379_CALLINGCELLID
)B2 ON A.CGI=B2.G379_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) AGAMI_VOICE_REVENUE 
FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                  
AND V397_MAINOFFERINGID IN (300033,400012)
GROUP BY V381_CALLINGCELLID
)C1 ON A.CGI=C1.V381_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) AGAMI_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                    
AND G401_MAINOFFERINGID IN (300033,400012)
GROUP BY G379_CALLINGCELLID
)C2 ON A.CGI=C2.G379_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) BORNOMALA_VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                   
AND V397_MAINOFFERINGID IN (300034,400015)
GROUP BY V381_CALLINGCELLID
)D1 ON A.CGI=D1.V381_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) BORNOMALA_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                 
AND G401_MAINOFFERINGID IN (300034,400015)
GROUP BY G379_CALLINGCELLID
)D2 ON A.CGI=D2.G379_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) SAGOTOM_VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                     
and V397_MAINOFFERINGID =479662
GROUP BY V381_CALLINGCELLID
)E1 ON A.CGI=E1.V381_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) SAGOTOM_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                  
and G401_MAINOFFERINGID =479662
GROUP BY G379_CALLINGCELLID
)E2 ON A.CGI=E2.G379_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) APARAJITA_VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY= (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                
and V397_MAINOFFERINGID =400019
GROUP BY V381_CALLINGCELLID
)F1 ON A.CGI=F1.V381_CALLINGCELLID


LEFT OUTER JOIN



(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) APARAJITA_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                    
and G401_MAINOFFERINGID =400019
GROUP BY G379_CALLINGCELLID
)F2 ON A.CGI=F2.G379_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) MAYERHASHI_VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                    
and V397_MAINOFFERINGID =400018
GROUP BY V381_CALLINGCELLID
)G1  ON A.CGI=G1.V381_CALLINGCELLID


LEFT OUTER JOIN



(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) MAYERHASHI_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                            
and G401_MAINOFFERINGID =400018
GROUP BY G379_CALLINGCELLID
)G2 ON A.CGI=G2.G379_CALLINGCELLID


LEFT OUTER JOIN



(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) CORPORATE_VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY= (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                   
and V397_MAINOFFERINGID in (200002,300022,300042,449066,449073,410010,410008,410009,449103,200001)
GROUP BY V381_CALLINGCELLID
)H1 ON A.CGI=H1.V381_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) CORPORATE_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                    
and G401_MAINOFFERINGID in (200002,300022,300042,449066,449073,410010,410008,410009,449103,200001)
GROUP BY G379_CALLINGCELLID
)H2 ON A.CGI=H2.G379_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) MODEM_VOICE_REVENUE 
FROM L3_VOICE P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                     
and V397_MAINOFFERINGID in (449066,449073,410013,449662,449103,400022,400021)
GROUP BY V381_CALLINGCELLID
)I1 ON A.CGI=I1.V381_CALLINGCELLID


LEFT OUTER JOIN


(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) MODEM_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                
and G401_MAINOFFERINGID in (449066,449073,410013,449662,449103,400022,400021)
GROUP BY G379_CALLINGCELLID
)I2 ON A.CGI=I2.G379_CALLINGCELLID


LEFT OUTER JOIN




(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID, sum(V41_DEBIT_AMOUNT) OTHERS_VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                  
and V397_MAINOFFERINGID NOT in (300033,400012,300034,400015,479662,400019,400018,200002,300022,300042,449066,449073,410010,410008,410009,449103,200001,400014,400017,400016,300050
,410013,449662,400022,400021)
GROUP BY V381_CALLINGCELLID
)J1 ON A.CGI=J1.V381_CALLINGCELLID


LEFT OUTER JOIN



(SELECT /*+PARALLEL(P,8)*/G379_CALLINGCELLID, SUM(G41_DEBIT_AMOUNT) OTHERS_DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                      
and G401_MAINOFFERINGID NOT in (300033,400012,300034,400015,479662,400019,400018,200002,300022,300042,449066,449073,410010,410008,410009,449103,200001,400014,400017,400016,300050
,410013,449662,400022,400021)
GROUP BY G379_CALLINGCELLID
)J2 ON A.CGI=J2.G379_CALLINGCELLID


LEFT OUTER JOIN


(SELECT V381_CALLINGCELLID,SUM(VOICE_REVENUE) VOICE_REVENUE_18_26
FROM
(select MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12 Age
from L3_ETSAF
--WHERE (ENTRY_DATE BETWEEN (SELECT DATE_vALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('17-May-2020','DD-MONTH-RRRR'))
   --   AND  (SELECT DATE_VALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('23-May-2020','DD-MONTH-RRRR')))
Group by MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12
)P

INNER JOIN

(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER, sum(V41_DEBIT_AMOUNT) VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                 
GROUP BY V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER
)Q ON P.MSISDN=Q.V372_CALLINGPARTYNUMBER

WHERE Age<27 AND Age>=18
GROUP BY V381_CALLINGCELLID
)K1 ON A.CGI=K1.V381_CALLINGCELLID


LEFT OUTER JOIN


(SELECT G379_CALLINGCELLID,SUM(DATA_REVENUE) DATA_REVENUE_18_26
FROM
(select MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12 Age
from L3_ETSAF
--WHERE (ENTRY_DATE BETWEEN (SELECT DATE_vALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('17-May-2020','DD-MONTH-RRRR'))
     -- AND  (SELECT DATE_VALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('23-May-2020','DD-MONTH-RRRR')))
Group by MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12
)P

INNER JOIN

(SELECT /*+PARALLEL(P,8)*/ G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER ,SUM(G41_DEBIT_AMOUNT) DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                    

GROUP BY G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER
)
Q ON P.MSISDN=Q.G372_CALLINGPARTYNUMBER

WHERE Age<27 AND Age>=18
GROUP BY G379_CALLINGCELLID

)K2 ON A.CGI=K2.G379_CALLINGCELLID



LEFT OUTER JOIN



(SELECT V381_CALLINGCELLID,SUM(VOICE_REVENUE) VOICE_REVENUE_27_35
FROM
(select MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12 Age
from L3_ETSAF
--WHERE (ENTRY_DATE BETWEEN (SELECT DATE_vALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('17-May-2020','DD-MONTH-RRRR'))
   --  AND  (SELECT DATE_VALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('23-May-2020','DD-MONTH-RRRR')))
Group by MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12
)P

INNER JOIN

(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER, sum(V41_DEBIT_AMOUNT) VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                             
GROUP BY V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER
)Q ON P.MSISDN=Q.V372_CALLINGPARTYNUMBER

WHERE Age<36 AND Age>=27
GROUP BY V381_CALLINGCELLID
)L1 ON A.CGI=L1.V381_CALLINGCELLID



LEFT OUTER JOIN 



(SELECT G379_CALLINGCELLID,SUM(DATA_REVENUE) DATA_REVENUE_27_35
FROM
(select MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12 Age
from L3_ETSAF
--WHERE (ENTRY_DATE BETWEEN (SELECT DATE_vALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('17-May-2020','DD-MONTH-RRRR'))
     -- AND  (SELECT DATE_VALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('23-May-2020','DD-MONTH-RRRR')))
Group by MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12
)P

INNER JOIN

(SELECT /*+PARALLEL(P,8)*/ G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER ,SUM(G41_DEBIT_AMOUNT) DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                         

GROUP BY G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER
)
Q ON P.MSISDN=Q.G372_CALLINGPARTYNUMBER

WHERE Age<36 AND Age>=27
GROUP BY G379_CALLINGCELLID

)L2 ON A.CGI=L2.G379_CALLINGCELLID



LEFT OUTER JOIN




(SELECT V381_CALLINGCELLID,SUM(VOICE_REVENUE) VOICE_REVENUE_35_45
FROM
(select MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12 Age
from L3_ETSAF
--WHERE (ENTRY_DATE BETWEEN (SELECT DATE_vALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('17-May-2020','DD-MONTH-RRRR'))
     -- AND  (SELECT DATE_VALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('23-May-2020','DD-MONTH-RRRR')))
Group by MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12
)P

INNER JOIN

(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER, sum(V41_DEBIT_AMOUNT) VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                   
GROUP BY V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER
)Q ON P.MSISDN=Q.V372_CALLINGPARTYNUMBER

WHERE Age<46 AND Age>=35
GROUP BY V381_CALLINGCELLID

)M1 ON A.CGI=M1.V381_CALLINGCELLID


LEFT OUTER JOIN



(SELECT G379_CALLINGCELLID,SUM(DATA_REVENUE) DATA_REVENUE_35_45
FROM
(select MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12 Age
from L3_ETSAF
--WHERE (ENTRY_DATE BETWEEN (SELECT DATE_vALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('17-May-2020','DD-MONTH-RRRR'))
     -- AND  (SELECT DATE_VALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('23-May-2020','DD-MONTH-RRRR')))
Group by MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12
)P

INNER JOIN

(SELECT /*+PARALLEL(P,8)*/ G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER ,SUM(G41_DEBIT_AMOUNT) DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                      

GROUP BY G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER
)
Q ON P.MSISDN=Q.G372_CALLINGPARTYNUMBER

WHERE Age<46 AND Age>=35
GROUP BY G379_CALLINGCELLID

)M2 ON A.CGI=M2.G379_CALLINGCELLID



LEFT OUTER JOIN




(SELECT V381_CALLINGCELLID, SUM(VOICE_REVENUE) VOICE_REVENUE_ABOVE_45
FROM
(select MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12 Age
from L3_ETSAF
--WHERE (ENTRY_DATE BETWEEN (SELECT DATE_vALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('17-May-2020','DD-MONTH-RRRR'))
      --AND  (SELECT DATE_VALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('23-May-2020','DD-MONTH-RRRR')))
Group by MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12
)P

INNER JOIN

(SELECT /*+PARALLEL(P,8)*/V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER, sum(V41_DEBIT_AMOUNT) VOICE_REVENUE 
FROM L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY= (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                     
GROUP BY V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER
)Q ON P.MSISDN=Q.V372_CALLINGPARTYNUMBER

WHERE Age>=46
GROUP BY V381_CALLINGCELLID
)N1 ON A.CGI=N1.V381_CALLINGCELLID


LEFT OUTER JOIN 


(SELECT G379_CALLINGCELLID,SUM(DATA_REVENUE) DATA_REVENUE_ABOVE_45
FROM
(select MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12 Age
from L3_ETSAF
--WHERE (ENTRY_DATE BETWEEN (SELECT DATE_vALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('17-May-2020','DD-MONTH-RRRR'))
     -- AND  (SELECT DATE_VALUE FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('23-May-2020','DD-MONTH-RRRR')))
Group by MSISDN ,months_between(TRUNC(sysdate),to_date(DOB))/12
)P

INNER JOIN

(SELECT /*+PARALLEL(P,8)*/ G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER ,SUM(G41_DEBIT_AMOUNT) DATA_REVENUE
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(Sysdate-1,'DD/MM/RRRR'))
                                                      

GROUP BY G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER
)
Q ON P.MSISDN=Q.G372_CALLINGPARTYNUMBER
WHERE Age>=46
GROUP BY G379_CALLINGCELLID

)N2 ON A.CGI=N2.G379_CALLINGCELLID


;
    COMMIT;
END;
/

