--
-- R_S_AND_D_REPORT_1  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_S_AND_D_REPORT_1 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE S_AND_D_REPORT_1 WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO S_AND_D_REPORT_1



SELECT P.MST_SIM_NO, R.RETAILER_ID,R.MSISDN,R.ENTRY_DATE,R.IMEI,COALESCE (R.OUTGOING_CALL_COUNT, 0)+ COALESCE (R.INCOMING_CALL_COUNT, 0) TOTAL_CALL_COUNT,
         COALESCE (R.OUTGOING_CALL_COUNT, 0) OUTGOING_CALL_COUNT, COALESCE (R.INCOMING_CALL_COUNT, 0) INCOMING_CALL_COUNT,
         COALESCE (R.OUTGOING_MINUTES, 0)+ COALESCE (R.INCOMING_MINUTES, 0) TOTAL_VOICE_USAGE,COALESCE (R.DATA_MB, 0) DATA_MB,VDATE_KEY
         FROM DM_DEALER_INFO@DWH05TODWH_DMS P,DM_RETAILER_INFO@DWH05TODWH_DMS Q,


(SELECT A.RETAILER_ID,A.MSISDN,A.ENTRY_DATE, A.IMEI,OUTGOING_CALL_COUNT,INCOMING_CALL_COUNT,OUTGOING_MINUTES,INCOMING_MINUTES,DATA_MB FROM 

(select /*+PARALLEL(P,16)*/PROCESSED_BY RETAILER_ID,MSISDN,ENTRY_DATE, IMEI

from L3_ETSAF P

where 

(ENTRY_DATE BETWEEN (TO_DATE(SYSDATE-7,'DD-Month-RRRR')) AND (TO_DATE(SYSDATE-1,'DD-Month-RRRR')) )
AND TYPE='NEW_PREPAID'
group by PROCESSED_BY,MSISDN,ENTRY_DATE, IMEI
)A 

LEFT OUTER JOIN

(SELECT /*+PARALLEL(Q,16)*/ V372_CALLINGPARTYNUMBER,COUNT(*)  OUTGOING_CALL_COUNT,SUM(V35_RATE_USAGE)/60  OUTGOING_MINUTES
FROM L3_VOICE  Q
WHERE V378_SERVICEFLOW=1
AND (V387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
                                                       AND  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))

GROUP BY V372_CALLINGPARTYNUMBER
)B ON A.MSISDN=B.V372_CALLINGPARTYNUMBER

LEFT OUTER JOIN

(SELECT /*+PARALLEL(Q,16)*/ V373_CALLEDPARTYNUMBER,COUNT(*)  INCOMING_CALL_COUNT,SUM(V35_RATE_USAGE)/60  INCOMING_MINUTES
FROM L3_VOICE  Q
WHERE V378_SERVICEFLOW=2
AND (V387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
                                                       AND  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))

GROUP BY V373_CALLEDPARTYNUMBER
)C ON A.MSISDN=C.V373_CALLEDPARTYNUMBER


LEFT OUTER JOIN

(SELECT /*+PARALLEL(Q,16)*/ G372_CALLINGPARTYNUMBER,SUM(G384_TOTALFLUX)/1048576 DATA_MB
FROM L3_DATA Q
WHERE ( G383_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-7,'DD/MM/RRRR'))
                                                       AND  (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-1,'DD/MM/RRRR')))

GROUP BY G372_CALLINGPARTYNUMBER
)F ON A.MSISDN=F.G372_CALLINGPARTYNUMBER

)R

WHERE R.RETAILER_ID=Q.TELECHARGE_NO AND Q.DEALER_NO=P.CUSTOMER_NO
    
;
    COMMIT;
END;
/

