--
-- R_SITE_ID_WISE_ACTIVE_SUBSCRIBERS_COUNT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_SITE_ID_WISE_ACTIVE_SUBSCRIBERS_COUNT IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE SITE_ID_WISE_ACTIVE_SUBSCRIBERS_COUNT WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO SITE_ID_WISE_ACTIVE_SUBSCRIBERS_COUNT

SELECT SITE_ID,DISTRICT,ACTIVE_SUBSCRIBERS_COUNT,VDATE_KEY
FROM
(SELECT/*+PARALLEL(P,14)*/ SITE_ID,DISTRICT, COUNT(UNIQUE MSISDN) ACTIVE_SUBSCRIBERS_COUNT FROM LOCATION_FCT P,ZONE_DIM Q
WHERE P.DATE_KEY IN (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE >= TO_DATE(Sysdate-30,'DD/MM/RRRR'))
AND  P.CALLINGCELLID=Q.CGI
GROUP BY SITE_ID,DISTRICT
)

;
    COMMIT;
END;
/

