--
-- R_SITE_ID_WISE_VOICE_PPU_REVENUE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_SITE_ID_WISE_VOICE_PPU_REVENUE IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE SITE_ID_WISE_VOICE_PPU_REVENUE WHERE PDR_DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO SITE_ID_WISE_VOICE_PPU_REVENUE


select /*+PARALLEL(P,15)*/DATE_VALUE,SITE_ID, DISTRICT,SUM(VOICE_PPU_REVENUE)VOICE_PPU_REVENUE,VDATE_KEY
from date_dim,zone_dim,
(SELECT /*+PARALLEL(P,15)*/V381_CALLINGCELLID,V387_CHARGINGTIME_KEY, SUM( V41_DEBIT_AMOUNT) VOICE_PPU_REVENUE 
FROM  L3_VOICE  P
WHERE (V387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('18/10/2020','DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('18/11/2020','DD/MM/RRRR')))
and V378_SERVICEFLOW=1

                                                    
GROUP BY V381_CALLINGCELLID,V387_CHARGINGTIME_KEY
) P
WHERE  V387_CHARGINGTIME_KEY=DATE_KEY AND V381_CALLINGCELLID=CGI  
GROUP BY DATE_VALUE,SITE_ID, DISTRICT


;
    COMMIT;
END;
/

