--
-- R_SMSC_MTMSC_WISE_DETAIL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_SMSC_MTMSC_WISE_DETAIL IS
    VDATE_KEY       VARCHAR2(64 BYTE);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE SMSC_MTMSC_WISE_DETAIL WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO SMSC_MTMSC_WISE_DETAIL


SELECT DATE_VALUE, SMC30_ORGACCOUNT,SMC27_MTMSCADDR,TOTAL_SUCCESS,TOTAL_FAIL ,VDATE_KEY
FROM DATE_DIM P,
(SELECT A.SMC1_TIME_SERIAL_NUMBER_KEY,A.SMC30_ORGACCOUNT ,A.SMC27_MTMSCADDR,TOTAL_SUCCESS,TOTAL_FAIL FROM 
(select /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC30_ORGACCOUNT ,SMC27_MTMSCADDR
from L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE  SMC1_TIME_SERIAL_NUMBER_KEY  IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC30_ORGACCOUNT,SMC27_MTMSCADDR
)A 

LEFT OUTER JOIN


(
select /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC30_ORGACCOUNT ,SMC27_MTMSCADDR , COUNT(*)
 TOTAL_SUCCESS
from L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE  SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC15_SMSTATUS =1
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC30_ORGACCOUNT ,SMC27_MTMSCADDR

)B ON A.SMC30_ORGACCOUNT=B.SMC30_ORGACCOUNT AND A.SMC27_MTMSCADDR=B.SMC27_MTMSCADDR AND A.SMC1_TIME_SERIAL_NUMBER_KEY=B.SMC1_TIME_SERIAL_NUMBER_KEY


LEFT OUTER JOIN



(
select /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC30_ORGACCOUNT ,SMC27_MTMSCADDR , COUNT(*)
 TOTAL_FAIL
from L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE  SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC15_SMSTATUS !=1
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC30_ORGACCOUNT ,SMC27_MTMSCADDR

)C ON A.SMC30_ORGACCOUNT=C.SMC30_ORGACCOUNT AND A.SMC27_MTMSCADDR=C.SMC27_MTMSCADDR AND A.SMC1_TIME_SERIAL_NUMBER_KEY=C.SMC1_TIME_SERIAL_NUMBER_KEY

)Q
WHERE P.DATE_KEY=Q.SMC1_TIME_SERIAL_NUMBER_KEY;
      COMMIT;
END;
/

