--
-- R_SMSC_ERROR_CODE_WISE_DETAILS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_SMSC_ERROR_CODE_WISE_DETAILS IS
    VDATE_KEY       VARCHAR2(64 BYTE);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE SMSC_ERROR_CODE_WISE_DETAILS WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO SMSC_ERROR_CODE_WISE_DETAILS



SELECT DATE_VALUE,SMC16_ERROR_CODE,ONNET_SUCCESS,OFFNET_SUCCESS,ONNNET_FAIL,OFFNET_FAIL,INT_SUCCESS,INT_FAILED,
       TOTAL_SUCCESS,TOTAL_FAIL,VDATE_KEY
FROM DATE_DIM Q,
(SELECT A.SMC1_TIME_SERIAL_NUMBER_KEY,A.SMC16_ERROR_CODE,   COALESCE (ONNET_SUCCESS_1, 0)+ COALESCE (ONNET_SUCCESS_2, 0) ONNET_SUCCESS,COALESCE (OFFNET_SUCCESS_1, 0)+ COALESCE (OFFNET_SUCCESS_2, 0) OFFNET_SUCCESS,
         COALESCE (ONNET_FAILED_1, 0)+ COALESCE (ONNET_FAILED_2, 0) ONNNET_FAIL, COALESCE (OFFNET_FAILED_1, 0)+ COALESCE (OFFNET_FAILED_2, 0) OFFNET_FAIL,
         COALESCE (INT_SUCCESS,0)INT_SUCCESS,COALESCE( INT_FAILED,0)INT_FAILED ,COALESCE( TOTAL_SUCCESS,0)TOTAL_SUCCESS,COALESCE(TOTAL_FAIL,0)TOTAL_FAIL
FROM
(SELECT /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE 
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE
)A

LEFT OUTER JOIN

(
SELECT /*+PARALLEL(P,8)*/  SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE , COUNT(*)

 ONNET_SUCCESS_1
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NOT NULL
AND SMC15_SMSTATUS=1
AND SUBSTR(SMC27_MTMSCADDR,1,5) LIKE ('88015%')
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE

)B  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=B.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=B.SMC16_ERROR_CODE

LEFT OUTER JOIN

(
SELECT /*+PARALLEL(P,8)*/SMC1_TIME_SERIAL_NUMBER_KEY,  SMC16_ERROR_CODE , COUNT(*)

 ONNET_SUCCESS_2
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NULL
AND SMC15_SMSTATUS=1
AND (SUBSTR(SMC6_DESTINATION_DELIVERY_A,1,5) LIKE ('88015%') OR LENGTH(SMC6_DESTINATION_DELIVERY_A)<=6)
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE

)C  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=C.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=C.SMC16_ERROR_CODE


LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE , COUNT(*)

 ONNET_FAILED_1
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NOT NULL
AND SMC15_SMSTATUS !=1
AND SUBSTR(SMC27_MTMSCADDR,1,5) LIKE ('88015%')
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE

)D  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=D.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=D.SMC16_ERROR_CODE


LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE , COUNT(*)

 ONNET_FAILED_2
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NULL
AND SMC15_SMSTATUS !=1
AND (SUBSTR(SMC6_DESTINATION_DELIVERY_A,1,5) LIKE ('88015%') OR LENGTH(SMC6_DESTINATION_DELIVERY_A)<=6)
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE

)E  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=E.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=E.SMC16_ERROR_CODE


LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/  SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE , COUNT(*)

 OFFNET_SUCCESS_1
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NOT NULL
AND SMC15_SMSTATUS=1
AND SUBSTR(SMC27_MTMSCADDR,1,5) NOT LIKE ('88015%') 
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE

)F  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=F.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=F.SMC16_ERROR_CODE


LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/  SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE , COUNT(*)

 OFFNET_SUCCESS_2
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NULL
AND SMC15_SMSTATUS=1
AND (SUBSTR(SMC6_DESTINATION_DELIVERY_A,1,5) NOT LIKE ('88015%') AND   LENGTH(SMC6_DESTINATION_DELIVERY_A) NOT IN(1,2,3,4,5,6))
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE

)G  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=G.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=G.SMC16_ERROR_CODE


LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/  SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE , COUNT(*)

 OFFNET_FAILED_1
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NOT NULL
AND SMC15_SMSTATUS !=1
AND SUBSTR(SMC27_MTMSCADDR,1,5) NOT LIKE ('88015%') 
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE

)H  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=H.SMC1_TIME_SERIAL_NUMBER_KEY AND  A.SMC16_ERROR_CODE=H.SMC16_ERROR_CODE


LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE , COUNT(*)

 OFFNET_FAILED_2
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NULL
AND SMC15_SMSTATUS !=1
AND (SUBSTR(SMC6_DESTINATION_DELIVERY_A,1,5) NOT LIKE ('88015%') AND   LENGTH(SMC6_DESTINATION_DELIVERY_A) NOT IN(1,2,3,4,5,6))
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE
)I  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=I.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=I.SMC16_ERROR_CODE


LEFT OUTER JOIN 


(
SELECT /*+PARALLEL(P,8)*/SMC1_TIME_SERIAL_NUMBER_KEY,  SMC16_ERROR_CODE , COUNT(*)

 INT_SUCCESS
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NOT NULL
AND SMC15_SMSTATUS=1
AND SUBSTR(SMC27_MTMSCADDR,1,5) NOT LIKE ('880%') 
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE

)J  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=J.SMC1_TIME_SERIAL_NUMBER_KEY AND  A.SMC16_ERROR_CODE=J.SMC16_ERROR_CODE


LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE , COUNT(*)

 INT_FAILED
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC27_MTMSCADDR IS NOT NULL
AND SMC15_SMSTATUS !=1
AND SUBSTR(SMC27_MTMSCADDR,1,5) NOT LIKE ('880%') 
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY,SMC16_ERROR_CODE

)K  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=K.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=K.SMC16_ERROR_CODE

LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/ SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE , COUNT(*)

 TOTAL_SUCCESS
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC15_SMSTATUS =1
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE

)L  ON A.SMC1_TIME_SERIAL_NUMBER_KEY=L.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=L.SMC16_ERROR_CODE

LEFT OUTER JOIN


(
SELECT /*+PARALLEL(P,8)*/SMC1_TIME_SERIAL_NUMBER_KEY,  SMC16_ERROR_CODE , COUNT(*)

 TOTAL_FAIL
FROM L3_SMSC P
--where SMC1_TIME_SERIAL_NUMBER
WHERE SMC1_TIME_SERIAL_NUMBER_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE >= TRUNC(TO_DATE(SYSDATE-7,'DD/MM/RRRR')))
AND SMC15_SMSTATUS !=1
GROUP BY SMC1_TIME_SERIAL_NUMBER_KEY, SMC16_ERROR_CODE

)M  ON  A.SMC1_TIME_SERIAL_NUMBER_KEY=M.SMC1_TIME_SERIAL_NUMBER_KEY AND A.SMC16_ERROR_CODE=M.SMC16_ERROR_CODE
)P
WHERE Q.DATE_KEY=P.SMC1_TIME_SERIAL_NUMBER_KEY;
      COMMIT;
END;
/

