--
-- R_SUBSCRIBER_QLOYALTY_SCORE_EXTRA  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_SUBSCRIBER_QLOYALTY_SCORE_EXTRA IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE,'RRRRMMDD');
   

    
INSERT INTO SUBSCRIBER_QLOYALTY_SCORE



SELECT LOYALTY_QUARTER, MSISDN, PRODUCT_ID, PRODUCT_NAME, OFFERING_ID, OFFERING_NAME, LAST_PURCHASE_DATE,  QUARTERLY_PURCHASE_COUNT, LOYALTY_SCORE
FROM
(SELECT 
CASE
WHEN (SUBSTR(MONTH_KEY,5,2)) IN('01','02','03')
THEN CONCAT('Q1_',(SUBSTR(MONTH_KEY,1,4))) 
WHEN (SUBSTR(MONTH_KEY,5,2)) IN('04','05','06')
THEN CONCAT('Q2_',(SUBSTR(MONTH_KEY,1,4))) 
WHEN (SUBSTR(MONTH_KEY,5,2)) IN('07','08','09')
THEN CONCAT('Q3_',(SUBSTR(MONTH_KEY,1,4))) 
WHEN (SUBSTR(MONTH_KEY,5,2)) IN('10','11','12')
THEN CONCAT('Q4_',(SUBSTR(MONTH_KEY,1,4))) 
END LOYALTY_QUARTER, MSISDN, PRODUCT_ID, PRODUCT_NAME, OFFERING_ID, OFFERING_NAME, DATE_VALUE LAST_PURCHASE_DATE, LQC QUARTERLY_PURCHASE_COUNT, ROUND(LQC/3,2) LOYALTY_SCORE FROM

(SELECT /*+parallel(p,16)*/ R375_CHARGINGPARTYNUMBER MSISDN, R373_MAINOFFERINGID, R385_OFFERINGID, MAX(R377_CYCLEBEGINTIME_KEY) LPD, COUNT(*) LQC FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY IN (SELECT DATE_KEY FROM DATE_DIM WHERE MONTH_KEY IN ('202004','202005','202006') )
                                  
GROUP BY R375_CHARGINGPARTYNUMBER, R373_MAINOFFERINGID, R385_OFFERINGID), DATE_DIM, PRODUCT_DIM, OFFER_DIM
WHERE R373_MAINOFFERINGID=PRODUCT_ID
AND R385_OFFERINGID=OFFERING_ID
AND LPD=DATE_KEY
)
;
             
             
             
      COMMIT;
END;
/

