--
-- R_SUBSCRIBER_USAGE_ANALYSIS_DEMO1  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_SUBSCRIBER_USAGE_ANALYSIS_DEMO1 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE,'RRRRMMDD');

    
INSERT INTO SUBSCRIBER_USAGE_ANALYSIS_FINAL

SELECT/*+PARALLEL(P,15)*/MSISDN, PRODUCT_ID, DATE_KEY, VOICE_PAYG_REVENUE, VOICE_RECURRING_REVENUE, VOICE_REVENUE, MO_DURATION_MINS,
 MT_DURATION_MINS, MO_CALL_COUNT, MT_CALL_COUNT, DATA_PAYG_REVENUE, DATA_BUNDLE_REVENUE, DATA_REVENUE, DATA_USAGE_MB, SMS_PAYG_REVENUE,
 SMS_BUNDLE_REVENUE, SMS_REVENUE, MO_SMS_COUNT, MT_SMS_COUNT, COMBO_BUNDLE_REVENUE, 
 RECHARGE_AMOUNT, PDR_DATE_KEY  
 FROM DWH_USER.SUBSCRIBER_USAGE_ANALYSIS P

WHERE  DATE_KEY BETWEEN '2376' AND '2537'
;
    COMMIT;
END;
/

