--
-- R_ZONE_WISE_SUBSCRIBERS_USAGE_ANALYSIS_DEMO2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_ZONE_WISE_SUBSCRIBERS_USAGE_ANALYSIS_DEMO2 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE,'RRRRMMDD');

    
INSERT INTO ZONE_WISE_SUBSCRIBERS_USAGE_ANALYSIS


SELECT G379_CALLINGCELLID CGI,G372_CALLINGPARTYNUMBER MSISDN,G401_MAINOFFERINGID PRODUCT_KEY,G383_CHARGINGTIME_KEY DATE_KEY,
       SUM(NVL(DATA_VOLUME_MB,0)) DATA_VOLUME_MB,SUM(NVL(DATA_PPU_REVENUE,0))DATA_PPU_REVENUE,SUM(NVL(MOC_DURATION_MINS,0))MOC_DURATION_MINS,SUM(NVL(VOICE_PPU_REVENUE,0))VOICE_PPU_REVENUE,
      SUM(NVL(MO_CALL_COUNT,0))MO_CALL_COUNT,SUM(NVL(MT_DURATION_MINS,0))MT_DURATION_MINS,SUM(NVL(MT_CALL_COUNT,0))MT_CALL_COUNT,VDATE_KEY
FROM
(
(SELECT G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID,G383_CHARGINGTIME_KEY,SUM(G384_TOTALFLUX)/1048576 DATA_VOLUME_MB ,
         SUM(G41_DEBIT_AMOUNT) DATA_PPU_REVENUE, NULL AS MOC_DURATION_MINS, NULL AS VOICE_PPU_REVENUE,NULL AS MO_CALL_COUNT,
         NULL AS MT_DURATION_MINS, NULL AS MT_CALL_COUNT
FROM
(SELECT /*+PARALLEL(P,15)*/ G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID,G383_CHARGINGTIME_KEY,
       

CASE 
WHEN LENGTH(G379_CALLINGCELLID)=15
THEN G379_CALLINGCELLID
WHEN LENGTH(G379_CALLINGCELLID)=30
THEN SUBSTR(G379_CALLINGCELLID,16,15)
END G379_CALLINGCELLID,
G384_TOTALFLUX,G41_DEBIT_AMOUNT
FROM L3_DATA P
WHERE (G383_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('20/12/2020','DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('20/12/2020','DD/MM/RRRR')))


)
GROUP BY  G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID,G383_CHARGINGTIME_KEY,G379_CALLINGCELLID

)
UNION ALL

(SELECT /*+PARALLEL(P,15)*/  V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID,V387_CHARGINGTIME_KEY, 
           NULL AS  DATA_VOLUME_MB , NULL AS  DATA_PPU_REVENUE,  SUM( V35_RATE_USAGE)/60 MOC_DURATION_MINS , SUM(V41_DEBIT_AMOUNT)VOICE_PPU_REVENUE, 
           COUNT(*) MO_CALL_COUNT,NULL AS MT_DURATION_MINS, NULL AS MT_CALL_COUNT
  
FROM  L3_VOICE  P
WHERE (V387_CHARGINGTIME_KEY BETWEEN (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('20/12/2020','DD/MM/RRRR'))
AND (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('20/12/2020','DD/MM/RRRR')))
AND V378_SERVICEFLOW=1

                                                    
GROUP BY V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID,V387_CHARGINGTIME_KEY,V381_CALLINGCELLID
)

)
GROUP BY G379_CALLINGCELLID ,G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID ,G383_CHARGINGTIME_KEY 

;
    COMMIT;
END;
/

