--
-- R_ZONE_WISE_SUBSCRIBERS_USAGE_ANALYSIS_JAN3  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_ZONE_WISE_SUBSCRIBERS_USAGE_ANALYSIS_JAN3 IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE,'RRRRMMDD');

    
INSERT INTO ZONE_WISE_SUBSCRIBERS_USAGE_ANALYSIS


SELECT G379_CALLINGCELLID CGI,G372_CALLINGPARTYNUMBER MSISDN,G401_MAINOFFERINGID PRODUCT_KEY,G383_CHARGINGTIME_KEY DATE_KEY,
       SUM(NVL(DATA_VOLUME_MB,0)) DATA_VOLUME_MB,SUM(NVL(DATA_PPU_REVENUE,0))DATA_PPU_REVENUE,SUM(NVL(MOC_DURATION_MINS,0))MOC_DURATION_MINS,SUM(NVL(VOICE_PPU_REVENUE,0))VOICE_PPU_REVENUE,
      SUM(NVL(MO_CALL_COUNT,0))MO_CALL_COUNT,SUM(NVL(MT_DURATION_MINS,0))MT_DURATION_MINS,SUM(NVL(MT_CALL_COUNT,0))MT_CALL_COUNT,VDATE_KEY
FROM
(
(SELECT G379_CALLINGCELLID,G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID,G383_CHARGINGTIME_KEY,SUM(G384_TOTALFLUX)/1048576 DATA_VOLUME_MB ,
         SUM(G41_DEBIT_AMOUNT) DATA_PPU_REVENUE, NULL AS MOC_DURATION_MINS, NULL AS VOICE_PPU_REVENUE,NULL AS MO_CALL_COUNT,
         NULL AS MT_DURATION_MINS, NULL AS MT_CALL_COUNT
FROM
(SELECT /*+PARALLEL(P,15)*/ G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID,G383_CHARGINGTIME_KEY,
       

CASE 
WHEN LENGTH(G379_CALLINGCELLID)=15
THEN G379_CALLINGCELLID
WHEN LENGTH(G379_CALLINGCELLID)=30
THEN SUBSTR(G379_CALLINGCELLID,16,15)
END G379_CALLINGCELLID,
G384_TOTALFLUX,G41_DEBIT_AMOUNT
FROM L3_DATA P
WHERE G383_CHARGINGTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('03/01/2021','DD/MM/RRRR'))



)
GROUP BY  G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID,G383_CHARGINGTIME_KEY,G379_CALLINGCELLID

)
UNION ALL

(SELECT /*+PARALLEL(P,15)*/  V381_CALLINGCELLID,V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID,V387_CHARGINGTIME_KEY, 
           NULL AS  DATA_VOLUME_MB , NULL AS  DATA_PPU_REVENUE,  SUM( V35_RATE_USAGE)/60 MOC_DURATION_MINS , SUM(V41_DEBIT_AMOUNT)VOICE_PPU_REVENUE, 
           COUNT(*) MO_CALL_COUNT,NULL AS MT_DURATION_MINS, NULL AS MT_CALL_COUNT
  
FROM  L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE DATE_VALUE = TO_DATE('03/01/2021','DD/MM/RRRR'))
AND V378_SERVICEFLOW=1

                                                    
GROUP BY V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID,V387_CHARGINGTIME_KEY,V381_CALLINGCELLID
)
UNION ALL
(SELECT M09_LOCATION,M04_MSISDNAPARTY,TO_NUMBER(LU_PRODUCT_KEY)LU_PRODUCT_KEY ,M07_ANSWERTIMESTAMP_KEY,
        NULL AS  DATA_VOLUME_MB , NULL AS  DATA_PPU_REVENUE,NULL AS MOC_DURATION_MINS , NULL AS VOICE_PPU_REVENUE, 
        NULL AS MO_CALL_COUNT,MT_DURATION_MINS,MT_CALL_COUNT
FROM LAST_ACTIVITY_FCT_LD,
(SELECT /*+PARALLEL(P,15)*/ M09_LOCATION,M04_MSISDNAPARTY,M07_ANSWERTIMESTAMP_KEY,
            SUM(M08_CALLDUR)/60 MT_DURATION_MINS, COUNT(*) MT_CALL_COUNT
FROM L1_MSC@DWH05TODWH03 P
WHERE (PROCESSED_DATE between TO_DATE('03/01/2021','DD/MM/RRRR') and TO_DATE('08/01/2021','DD/MM/RRRR'))
AND   M07_ANSWERTIMESTAMP_KEY=((SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE('03/01/2021','DD/MM/RRRR')))
                        
AND M01_CALLTYPE='MTC'
AND M08_CALLDUR !=0
GROUP BY M09_LOCATION,M04_MSISDNAPARTY,M07_ANSWERTIMESTAMP_KEY
)
WHERE M04_MSISDNAPARTY=MSISDN 
)
)
GROUP BY G379_CALLINGCELLID ,G372_CALLINGPARTYNUMBER,G401_MAINOFFERINGID ,G383_CHARGINGTIME_KEY 

;
    COMMIT;
END;
/

