--
-- SP_AGEONNETWROK_NEW  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_AGEONNETWROK_NEW IS
    VDATE_KEY    NUMBER;
BEGIN   
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_VALUE = TO_DATE(SYSDATE,'DD/MM/RRRR');
        
        
    INSERT INTO AGEONNETWROK_NEW(MSISDIN_NO,FIRST_ACTIVE_DATE_KEY)
    SELECT A.SERVICE_NUMBER,
    B.DATE_KEY
    FROM SUBSCRIPTION_DIM_LD A, DATE_DIM B 
    WHERE A.SERVICE_NUMBER NOT IN (SELECT MSISDIN_NO FROM AGEONNETWROK_NEW)
    AND B.DATE_VALUE = TO_DATE(A.START_DATE,'DD/MM/RRRR');
    COMMIT;

    MERGE INTO AGEONNETWROK_NEW A
    USING (SELECT MSISDN,LU_DATE_KEY FROM  LAST_ACTIVITY_FCT_LD) H
    ON (A.MSISDIN_NO = H.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LAST_ACTIVITY_DATE_KEY = H.LU_DATE_KEY;
    COMMIT;
    
    UPDATE AGEONNETWROK_NEW SET ETL_DATE_KEY = VDATE_KEY;
    COMMIT;
END;
/

