--
-- SP_CLEAR_FOR_LIFECYCLE_KPI  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_CLEAR_FOR_LIFECYCLE_KPI (P_PROCESS_DATE VARCHAR2) IS
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
    VDATE_KEY   NUMBER;
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
    DELETE LIFECYCLE_KPI_FCT WHERE DATE_KEY=VDATE_KEY
    AND KPI_KEY NOT IN (599,614,664);
    COMMIT;
    
    DELETE LIFECYCLE_LOG WHERE DATE_KEY=VDATE_KEY
    AND KPI_KEY NOT IN (599,614,664);
    COMMIT;

EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

