--
-- SP_LAYER3_COUNT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_LAYER3_COUNT IS
PDATE  DATE := TRUNC(SYSDATE-1);
ACOUNT NUMBER;
CCOUNT NUMBER;
DCOUNT NUMBER;
MCOUNT NUMBER;
RCOUNT NUMBER;
RECOUNT NUMBER;
SCOUNT NUMBER;
TCOUNT NUMBER;
VCOUNT NUMBER;
BEGIN
SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO ACOUNT
FROM L3_ADJUSTMENT V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

INSERT INTO LAYER3_COUNT(PROCESSED_DATE,L3_ADJUSTMENT)
VALUES (PDATE,ACOUNT);
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO CCOUNT
FROM L3_CONTENT V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER3_COUNT SET L3_CONTENT=CCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO DCOUNT
FROM L3_DATA V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER3_COUNT SET L3_DATA=DCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO MCOUNT 
FROM L3_MANAGEMENT V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER3_COUNT SET L3_MANAGEMENT=MCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO RCOUNT 
FROM L3_RECHARGE V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER3_COUNT SET L3_RECHARGE=RCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO RECOUNT
FROM L3_RECURRING V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER3_COUNT SET L3_RECURRING=RECOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO SCOUNT
FROM L3_SMS V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER3_COUNT SET L3_SMS=SCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/COUNT(*) INTO TCOUNT
FROM L3_TRANSFER V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER3_COUNT SET L3_TRANSFER=TCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO VCOUNT
FROM L3_VOICE V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER3_COUNT SET L3_VOICE=VCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

END;
/

