--
-- SP_LIFECYCLE_RECHARGE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_LIFECYCLE_RECHARGE (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY                   VARCHAR2(4);
    DAILY_RECHARGE_AMOUNT       NUMBER;
    DAILY_RECHARGE_AMOUNT_PRE   NUMBER;
    DAILY_RECHARGE_AMOUNT_POST  NUMBER;
    DAILY_RECHARGE_SUBS         NUMBER;
    TELECHARGE                  NUMBER;
    OTHERCHARGE                 NUMBER;
    VDATE                       DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
    ---------KPI_LOG STATUS----------
    VSTATUS511                  NUMBER;
    VSTATUS512                  NUMBER;
    VSTATUS617                  NUMBER;
    VSTATUS526                  NUMBER;
    VSTATUS619                  NUMBER;
    VSTATUS620                  NUMBER;

BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
    ---------511 Daily Recharge Amount------------------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS511
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 511;

    IF VSTATUS511 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',511,'L3_RECHARGE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        SELECT /*+ PARALLEL(L3_RECHARGE,16) */ SUM(RE3_RECHARGE_AMT) INTO DAILY_RECHARGE_AMOUNT
        FROM L3_RECHARGE
        WHERE RE30_ENTRY_DATE_KEY = VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 511,DAILY_RECHARGE_AMOUNT); 
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 511;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',511,'L3_RECHARGE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    --------------617 Recharge Amount (Prepaid)------------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS617
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 617;

    IF VSTATUS617 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',617,'L3_RECHARGE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_RECHARGE,16) */ SUM(RE3_RECHARGE_AMT) INTO DAILY_RECHARGE_AMOUNT_PRE
        FROM L3_RECHARGE
        WHERE RE490_PAYTYPE=0
        AND RE30_ENTRY_DATE_KEY = VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 617,DAILY_RECHARGE_AMOUNT_PRE);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 617;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',617,'L3_RECHARGE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    --------------526 Post-paid bill pay Amount------------ 
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS526
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 526;

    IF VSTATUS526 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',526,'L3_RECHARGE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;   
        SELECT /*+ PARALLEL(L3_RECHARGE,16) */ SUM(RE3_RECHARGE_AMT) INTO DAILY_RECHARGE_AMOUNT_POST
        FROM L3_RECHARGE
        WHERE RE490_PAYTYPE=1
        AND RE30_ENTRY_DATE_KEY = VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 526,DAILY_RECHARGE_AMOUNT_POST);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 526;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',526,'L3_RECHARGE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    --------------512 Recharge Subs-------------------------    
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS512
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 512;

    IF VSTATUS512 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',512,'L3_RECHARGE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        SELECT /*+ PARALLEL(L3_RECHARGE,16) */ COUNT(RE6_PRI_IDENTITY) INTO DAILY_RECHARGE_SUBS
        FROM L3_RECHARGE
        WHERE RE30_ENTRY_DATE_KEY = VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 512,DAILY_RECHARGE_SUBS);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 512;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',512,'L3_RECHARGE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    -------------619 Top-Up Payment----------- 
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS619
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 619;

    IF VSTATUS619 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',619,'L3_RECHARGE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
          
        SELECT /*+ PARALLEL(L3_RECHARGE,16) */ SUM(RE3_RECHARGE_AMT) INTO TELECHARGE
        FROM L3_RECHARGE
        WHERE RE490_PAYTYPE=1
        and   RE18_PAYMENT_TYPE = 'L'
        AND RE30_ENTRY_DATE_KEY = VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 619,TELECHARGE);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 619;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',619,'L3_RECHARGE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
        -------------620 Bank and Others Payment-----------    
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS620
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 620;

    IF VSTATUS620 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',620,'L3_RECHARGE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_RECHARGE,16) */ SUM(RE3_RECHARGE_AMT) INTO OTHERCHARGE
        FROM L3_RECHARGE
        WHERE RE490_PAYTYPE=1
        and   RE18_PAYMENT_TYPE <> 'L'
        AND RE30_ENTRY_DATE_KEY = VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 620,OTHERCHARGE);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 620;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECHARGE',620,'L3_RECHARGE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
END;
/

