--
-- SP_LIFECYCLE_VOICE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_LIFECYCLE_VOICE (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY                   VARCHAR2(4);
    DAILY_VOICE_SUBS_COUNT      NUMBER;
    MOC_DURATION                NUMBER;
    MOC_DURATION_ONNET          NUMBER;
    MOC_DURATION_OFFNET         NUMBER;
    MTC_DURATION                NUMBER;
    MTC_DURATION_ONNET          NUMBER;
    MTC_DURATION_OFFNET         NUMBER;
    MOC_DURATION_GP             NUMBER;
    MOC_DURATION_ROBI           NUMBER;
    MOC_DURATION_BL             NUMBER;
    MOC_DURATION_OTHERS         NUMBER;
    MTC_DURATION_GP             NUMBER;
    MTC_DURATION_ROBI           NUMBER;
    MTC_DURATION_BL             NUMBER;
    MTC_DURATION_OTHERS         NUMBER;
    FREE_MOC_DURATION           NUMBER;
    PREPAID_REVENUE_MOC         NUMBER;
    PREPAID_REVENUE_MOC_ONNET   NUMBER;
    PREPAID_REVENUE_MOC_OTHER   NUMBER;
    PREPAID_REVENUE_NON_MOC     NUMBER;
    VDATE                       DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');    
    ----------KPI_LOG STATUS----------
    --VSTATUS520                  NUMBER;
    VSTATUS693                  NUMBER;
    VSTATUS515                  NUMBER;
    VSTATUS543                  NUMBER;
    VSTATUS544                  NUMBER;
    VSTATUS516                  NUMBER;
    VSTATUS546                  NUMBER;
    VSTATUS547                  NUMBER;
    VSTATUS591                  NUMBER;
    VSTATUS592                  NUMBER;
    VSTATUS593                  NUMBER;
    VSTATUS594                  NUMBER;
    VSTATUS595                  NUMBER;
    VSTATUS596                  NUMBER;
    VSTATUS597                  NUMBER;
    VSTATUS598                  NUMBER;
    VSTATUS530                  NUMBER;
    VSTATUS621                  NUMBER;
    VSTATUS644                  NUMBER;
    VSTATUS645                  NUMBER;
    VSTATUS622                  NUMBER;

BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
   
    ----------693 VOICE SUBS---------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS693
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 693;
    
    
    IF VSTATUS693 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',693,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;    
    
        SELECT /*+ PARALLEL(L3_VOICE,16) */ COUNT(V372_CALLINGPARTYNUMBER) INTO DAILY_VOICE_SUBS_COUNT
        FROM L3_VOICE
        WHERE  V387_CHARGINGTIME_KEY =VDATE_KEY
        AND V378_SERVICEFLOW=1;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 693,DAILY_VOICE_SUBS_COUNT);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 693;        
        COMMIT;
        
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',693,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;

    ---------515 DAILY MOC DURATION--------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS515
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 515;
    
    IF VSTATUS515 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',515,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;               
    
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MOC_DURATION
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=1
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 515,MOC_DURATION);
        COMMIT;

        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 515;        
        COMMIT;
        
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',515,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    --------543 Charged On-net MOC Duration (min)-----
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS543
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 543;
    
    IF VSTATUS543 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',543,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;  
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MOC_DURATION_ONNET
        FROM L3_VOICE
        WHERE V387_CHARGINGTIME_KEY =VDATE_KEY
        and V403_ROAMSTATE !=3
        AND V378_SERVICEFLOW=1
        AND V25_USAGE_SERVICE_TYPE=10;
         

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 543,MOC_DURATION_ONNET);
        COMMIT;

        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 543;        
        COMMIT;
        
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',543,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;


    ----------544 Charged Off-net MOC Duration (min)------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS544
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 544;

    IF VSTATUS544 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',544,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT; 
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO  MOC_DURATION_OFFNET
        FROM L3_VOICE
        WHERE V387_CHARGINGTIME_KEY =VDATE_KEY
        AND V403_ROAMSTATE !=3
        AND V378_SERVICEFLOW=1
        AND V25_USAGE_SERVICE_TYPE=11;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 544,MOC_DURATION_OFFNET);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 544;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',544,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;

    -------------516 Daily MTC Duration (min)------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS516
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 516;

    IF VSTATUS516 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',516,'L1_MSC',VDATE_KEY,30,SYSDATE,'A');
        COMMIT; 
        /*
        SELECT SUM(V35_RATE_USAGE)/60 INTO MTC_DURATION
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=2
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;
        */
        SELECT SUM(M08_CALLDUR)/60 INTO MTC_DURATION
        FROM MTC_CALL_DURATION@DWH05TODWH03;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 516,MTC_DURATION);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 516;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',516,'L1_MSC',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    ------- 546 On-net MTC Duration (min)----------
    
     SELECT  COUNT(STATUS) AS STATUS INTO  VSTATUS546
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 546;

    IF VSTATUS546 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',546,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MTC_DURATION_ONNET
        FROM L3_VOICE
        WHERE V387_CHARGINGTIME_KEY =VDATE_KEY
        AND V403_ROAMSTATE !=3
        AND V378_SERVICEFLOW=2
        AND V25_USAGE_SERVICE_TYPE=10;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 546,MTC_DURATION_ONNET);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 546;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',546,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    ----------------547 Off-net MTC Duration (min)------------
     SELECT  COUNT(STATUS) AS STATUS INTO  VSTATUS547
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 547;

    IF VSTATUS547 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',547,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MTC_DURATION_OFFNET
        FROM L3_VOICE
        WHERE V387_CHARGINGTIME_KEY =VDATE_KEY
        AND V403_ROAMSTATE !=3
        AND V378_SERVICEFLOW=2
        AND V25_USAGE_SERVICE_TYPE=11;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 547,MTC_DURATION_OFFNET);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 547;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',547,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    -------591 Charged MOC Duration (min) to GP-----
     SELECT  COUNT(STATUS) AS STATUS INTO  VSTATUS591
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 591;

    IF VSTATUS591 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',591,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MOC_DURATION_GP
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=1
        AND  SUBSTR(V373_CALLEDPARTYNUMBER,3,3) IN ('017','013')
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 591,MOC_DURATION_GP);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 591;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',591,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    --------------592  Charged MOC Duration (min) to Robi----
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS592
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 592;

    IF VSTATUS592 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',592,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MOC_DURATION_ROBI
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=1
        AND  SUBSTR(V373_CALLEDPARTYNUMBER,3,3) IN ('018','016')
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 592,MOC_DURATION_ROBI);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 592;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',592,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    --------------593  Charged MOC Duration (min) to Banglalink----
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS593
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 593;

    IF VSTATUS593 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',593,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MOC_DURATION_BL
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=1
        AND  SUBSTR(V373_CALLEDPARTYNUMBER,3,3) IN ('019','014')
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 593,MOC_DURATION_BL);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 593;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',593,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    --------------594 Charged MOC Duration (min) to Others----
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS594
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 594;

    IF VSTATUS594 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',594,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MOC_DURATION_OTHERS
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=1
        AND  SUBSTR(V373_CALLEDPARTYNUMBER,3,3) NOT IN ('019','014','013','016','017','018')
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 594,MOC_DURATION_OTHERS);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 594;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',594,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    ---------------------------DURATION-------------------------------
    
    -------595 Charged MTC Duration (min) to GP-----
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS595
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 595;

    IF VSTATUS595 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',595,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
    
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MTC_DURATION_GP
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=2
        AND  SUBSTR(V372_CALLINGPARTYNUMBER,3,3) IN ('017','013')
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 595,MTC_DURATION_GP);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 595;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',595,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    --------------596 Charged MTC Duration (min) to Robi----
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS596
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 596;

    IF VSTATUS596 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',596,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;    
    
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MTC_DURATION_ROBI
        FROM L3_VOICE
        WHERE  V387_CHARGINGTIME_KEY =VDATE_KEY
        AND V403_ROAMSTATE !=3 
        AND V378_SERVICEFLOW=2
        AND  SUBSTR(V372_CALLINGPARTYNUMBER,3,3) IN ('018','016')
        ;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 596,MTC_DURATION_ROBI);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 596;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',596,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    --------------597 Charged MTC Duration (min) to Banglalink----
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS597
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 597;

    IF VSTATUS596 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',597,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT; 
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MTC_DURATION_BL
        FROM L3_VOICE
        WHERE V387_CHARGINGTIME_KEY =VDATE_KEY
        AND V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=2
        AND  SUBSTR(V372_CALLINGPARTYNUMBER,3,3) IN ('019','014')
        ;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 597,MTC_DURATION_BL);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 597;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',597,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    --------------598 Charged MTC Duration (min) to Others----
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS598
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 598;

    IF VSTATUS598 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',598,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT; 
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V35_RATE_USAGE)/60 INTO MTC_DURATION_OTHERS
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=2
        AND  SUBSTR(V372_CALLINGPARTYNUMBER,3,3) NOT IN ('019','014','013','016','017','018')
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 598,MTC_DURATION_OTHERS);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 598;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',598,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    -----530  Free MOC (min)-----------------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS530
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 530;

    IF VSTATUS598 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',530,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */SUM(V50_PAY_FREE_UNIT_DURATION)/60 INTO FREE_MOC_DURATION
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3 AND V378_SERVICEFLOW=1
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 530,FREE_MOC_DURATION);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 530;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',530,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;

    ----------621 PREPAID REVENUE MOC---------------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS621
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 621;

    IF VSTATUS621 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',621,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V41_DEBIT_AMOUNT) INTO PREPAID_REVENUE_MOC
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3
        AND V378_SERVICEFLOW=1
        AND V400_PAYTYPE=0
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 621,PREPAID_REVENUE_MOC);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 621;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',621,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    ------644 PREPAID REVENUE MOC ON-NET------------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS644
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 644;

    IF VSTATUS644 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',644,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
         
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V41_DEBIT_AMOUNT) INTO PREPAID_REVENUE_MOC_ONNET
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3
        AND V378_SERVICEFLOW=1
        AND V400_PAYTYPE=0
        AND V25_USAGE_SERVICE_TYPE=10
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 644,PREPAID_REVENUE_MOC_ONNET);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 644;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',644,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    
    ------------645 PREPAID REVENUE MOC OTHER-------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS645
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 645;

    IF VSTATUS645 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',645,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V41_DEBIT_AMOUNT) INTO PREPAID_REVENUE_MOC_OTHER
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3
        AND V378_SERVICEFLOW=1
        AND V400_PAYTYPE=0
        AND V25_USAGE_SERVICE_TYPE !=10
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 645,PREPAID_REVENUE_MOC_OTHER);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 645;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',645,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
    ---------622 PREPAID REVENUE NON MOC------------
     SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS622
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 622;

    IF VSTATUS622 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',622,'L3_VOICE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V41_DEBIT_AMOUNT) INTO PREPAID_REVENUE_NON_MOC
        FROM L3_VOICE
        WHERE V403_ROAMSTATE !=3
        AND V378_SERVICEFLOW !=1
        AND V400_PAYTYPE=0 
        AND  V387_CHARGINGTIME_KEY =VDATE_KEY;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 622,PREPAID_REVENUE_NON_MOC);
        COMMIT;
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 622;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_VOICE',622,'L3_VOICE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
END;
/

