--
-- SP_L3_MIGRATION_BASE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_L3_MIGRATION_BASE(P_DATE VARCHAR2) AS
VDATE_KEY VARCHAR2(4);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM 
WHERE TRUNC(DATE_VALUE)=TRUNC(TO_DATE(P_DATE,'RRRR/MM/DD'));

INSERT INTO L3_MIGRATION_BASE(MSISDN,DATE_KEY)
SELECT DISTINCT MSISDN, VDATE_KEY
FROM L1_MIGRATION_BASE@DWH05TODWH01
WHERE TRUNC(PROCESSED_DATE)BETWEEN TRUNC(SYSDATE-3) AND TRUNC(SYSDATE)
AND SUBSTR(FILE_NAME,14,8)=P_DATE
AND MSISDN NOT IN(SELECT MSISDN FROM L3_MIGRATION_BASE);
COMMIT;
END;
/

