--
-- SP_LIFECYCLE_DATA  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_LIFECYCLE_DATA (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY                 VARCHAR2(4);
    DATA_USAGE_GB             NUMBER;
    DATA_4G_USAGE_GB          NUMBER;
    DATA_3G_USAGE_GB          NUMBER;
    DATA_2G_USAGE_GB          NUMBER;
    FREE_DATA_4G_USAGE_GB     NUMBER;
    FREE_DATA_3G_USAGE_GB     NUMBER;
    FREE_DATA_2G_USAGE_GB     NUMBER;
    TOTAL_PAYG_REV            NUMBER;
    PAYG_REV_4G               NUMBER;
    PAYG_REV_3G               NUMBER;
    PAYG_REV_2G               NUMBER;
    VDATE                     DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
  --------KPI_LOG STATUS----------
    VSTATUS566                NUMBER;
    VSTATUS670                NUMBER;
    VSTATUS567                NUMBER;
    VSTATUS568                NUMBER;
    VSTATUS671                NUMBER;
    VSTATUS610                NUMBER;
    VSTATUS611                NUMBER;
    VSTATUS569                NUMBER;
    VSTATUS672                NUMBER;
    VSTATUS585                NUMBER;
    VSTATUS586                NUMBER;
BEGIN
  SELECT DATE_KEY INTO VDATE_KEY 
  FROM DATE_DIM
  WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
  
   ---------------566 Daily 2G / 3G / 4G :: Data Usage (GB)-----
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS566
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 566;

    IF VSTATUS566 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',566,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G384_TOTALFLUX)/1073741824  INTO DATA_USAGE_GB
        FROM L3_DATA
        WHERE G383_CHARGINGTIME_KEY =VDATE_KEY;
          
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 566,DATA_USAGE_GB);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 566;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',566,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;        
    
    --------------670  Daily 4G :: Data Usage (GB)-----------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS670
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 670;

    IF VSTATUS670 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',670,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G384_TOTALFLUX)/1073741824  INTO DATA_4G_USAGE_GB
        FROM L3_DATA 
        WHERE G429_RATTYPE = 6
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
                  
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 670,DATA_4G_USAGE_GB);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 670;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',670,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF; 
  ----------567 Daily 3G :: Data Usage (GB)-----------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS567
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 567;

    IF VSTATUS567 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',567,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G384_TOTALFLUX)/1073741824  INTO DATA_3G_USAGE_GB
        FROM L3_DATA 
        WHERE G429_RATTYPE = 1
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
                  
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 567,DATA_3G_USAGE_GB);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 567;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',567,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
  
  ----------568 Daily 2G :: Data Usage (GB)-----
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS568
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 568;

    IF VSTATUS568 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',568,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G384_TOTALFLUX)/1073741824  INTO DATA_2G_USAGE_GB
        FROM L3_DATA 
        WHERE G429_RATTYPE = 2
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
          
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 568,DATA_2G_USAGE_GB);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 568;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',568,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
          
  ---------671  Daily  4G :: Free Data Usage (GB)---
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS671
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 671;

    IF VSTATUS671 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',671,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G51_FREE_UNIT_AMOUNT_OF_FLUX)/1073741824  INTO FREE_DATA_4G_USAGE_GB
        FROM L3_DATA 
        WHERE G429_RATTYPE = 6
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
          
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 671,FREE_DATA_4G_USAGE_GB);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 671;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',671,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
      
  ----------610 Daily 3G :: Free Data Usage (GB)----
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS610
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 610;

    IF VSTATUS610 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',610,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G51_FREE_UNIT_AMOUNT_OF_FLUX)/1073741824  INTO FREE_DATA_3G_USAGE_GB
        FROM L3_DATA 
        WHERE G429_RATTYPE = 1
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
          
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 610,FREE_DATA_3G_USAGE_GB);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 610;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',610,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
  ----------611  Daily   2G :: Free Data Usage (GB)-----
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS611
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 611;

    IF VSTATUS611 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',611,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G51_FREE_UNIT_AMOUNT_OF_FLUX)/1073741824  INTO FREE_DATA_2G_USAGE_GB
        FROM L3_DATA 
        WHERE G429_RATTYPE = 2
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
                  
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 611,FREE_DATA_2G_USAGE_GB);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 611;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',611,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
  
  ----------569  Daily 2G / 3G / 4G :: Total PAYG Revenue-----
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS569
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 569;

    IF VSTATUS569 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',569,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G41_DEBIT_AMOUNT)  INTO TOTAL_PAYG_REV
        FROM L3_DATA
        WHERE G383_CHARGINGTIME_KEY =VDATE_KEY;
          
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 569,TOTAL_PAYG_REV);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 569;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',569,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
  -------672  Daily 4G :: PAYG Revenue----------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS672
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 672;

    IF VSTATUS672 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',672,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G41_DEBIT_AMOUNT)  INTO PAYG_REV_4G
        FROM L3_DATA 
        WHERE G429_RATTYPE = 6
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
          
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 672,PAYG_REV_4G);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 672;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',672,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
  
  
  -------585 Daily  3G :: PAYG Revenue---------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS585
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 585;

    IF VSTATUS585 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',585,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G41_DEBIT_AMOUNT)  INTO PAYG_REV_3G
        FROM L3_DATA 
        WHERE G429_RATTYPE = 1
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
          
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 585,PAYG_REV_3G);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 585;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',585,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;

  --------586  Daily 2G :: PAYG Revenue----------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS586
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 586;

    IF VSTATUS586 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',586,'L3_DATA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
   
        SELECT /*+ PARALLEL(L3_DATA,16) */ SUM (G41_DEBIT_AMOUNT)  INTO PAYG_REV_2G
        FROM L3_DATA 
        WHERE G429_RATTYPE = 2
        AND G383_CHARGINGTIME_KEY =VDATE_KEY;
          
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 586,PAYG_REV_2G);
        COMMIT;
        
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 586;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_DATA',586,'L3_DATA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
END;
/

