--
-- SP_LIFECYCLE_RECURRING  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_LIFECYCLE_RECURRING (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY           VARCHAR2(4);
    DAILY_VAS_REVENUE   NUMBER;
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
    ---------KPI_LOG STATUS----------
    VSTATUS649          NUMBER;
BEGIN
   
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
                     
    -------------------649 Total VAS Revenue----------------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS649
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 649;

    IF VSTATUS649 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECURRING',649,'L3_RECURRING',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        SELECT /*+ PARALLEL(L3_RECURRING,16) */ SUM(R41_DEBIT_AMOUNT) INTO DAILY_VAS_REVENUE
        FROM L3_RECURRING
        WHERE R377_CYCLEBEGINTIME_KEY =VDATE_KEY;
           
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 649,DAILY_VAS_REVENUE);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 649;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_RECURRING',649,'L3_RECURRING',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
END;
/

