--
-- SP_LIFECYCLE_EVCTRA  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_LIFECYCLE_EVCTRA (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY           VARCHAR2(4);
    RETAILER_COUNT      NUMBER;
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
    ---------KPI_LOG STATUS----------
    VSTATUS658          NUMBER;
BEGIN
   
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
                     
    -------------------658 EV Transacting Retailer Count-----------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS658
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 658;

    IF VSTATUS658 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_EVCTRA',658,'L3_EVCTRA',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        SELECT COUNT(A.COUNTS) INTO RETAILER_COUNT
        FROM(SELECT COUNT(ET03_MSISDN_DEALER) COUNTS 
        FROM L3_EVCTRA
        WHERE ET12_TRANSFER_DATE_KEY = VDATE_KEY
        GROUP BY ET03_MSISDN_DEALER)A;
           
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 658,RETAILER_COUNT);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 658;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_EVCTRA',658,'L3_EVCTRA',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
END;
/

