--
-- SP_LIFECYCLE_REVENUE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_LIFECYCLE_REVENUE (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY                   VARCHAR2(4);
    TOTAL_REVENUE               NUMBER;
    PREPAID_REVENUE             NUMBER;
    POSTPAID_REVENUE            NUMBER;
    VDATE                       DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
    ---------KPI_LOG STATUS----------
    VSTATUS565                  NUMBER;
    VSTATUS561                  NUMBER;
    VSTATUS562                  NUMBER;
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);

    ----------565 Total Revenue--------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS565
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 565;

    IF VSTATUS565 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_REVENUE',565,'MULTPLE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
    
        SELECT COALESCE (A.VOICE_REVENUE, 0)
        + COALESCE (B.DATA_REVENUE, 0)
        + COALESCE (C.VAS_REVENUE, 0)
        + COALESCE (D.SMS_REVENUE, 0)
       
        INTO TOTAL_REVENUE 
        FROM
        (SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V41_DEBIT_AMOUNT) VOICE_REVENUE FROM L3_VOICE
        WHERE V387_CHARGINGTIME_KEY =VDATE_KEY) A,
        (SELECT /*+ PARALLEL(L3_DATA,16) */SUM(G41_DEBIT_AMOUNT) DATA_REVENUE FROM L3_DATA
        WHERE G383_CHARGINGTIME_KEY =VDATE_KEY)B,
        (SELECT /*+ PARALLEL(L3_RECURRING,16) */SUM(R41_DEBIT_AMOUNT) VAS_REVENUE FROM L3_RECURRING
        WHERE R377_CYCLEBEGINTIME_KEY =VDATE_KEY)C,
        (SELECT /*+ PARALLEL(L3_SMS,16) */SUM(S41_DEBIT_AMOUNT) SMS_REVENUE FROM L3_SMS
        WHERE S387_CHARGINGTIME_KEY =VDATE_KEY)D
      ;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 565,TOTAL_REVENUE);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 565;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_REVENUE',565,'MULTPLE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;

    ----------561 prepaid Revenue----------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS561
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 561;

    IF VSTATUS561 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_REVENUE',561,'MULTPLE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        
        SELECT COALESCE   (AA.VOICE_REVENUE, 0)
        + COALESCE (BB.DATA_REVENUE, 0)
        + COALESCE (CC.VAS_REVENUE, 0)
        + COALESCE (DD.SMS_REVENUE, 0)
        + COALESCE (EE.ADJUSTMENT_REVENUE, 0)
        + COALESCE (FF.CONTENT_REVENUE, 0)
        INTO PREPAID_REVENUE 
        FROM
        (SELECT /*+ PARALLEL(L3_VOICE,16) */SUM(V41_DEBIT_AMOUNT) VOICE_REVENUE FROM L3_VOICE
        WHERE V400_PAYTYPE=0
        AND V387_CHARGINGTIME_KEY =VDATE_KEY)AA,
        (SELECT /*+ PARALLEL(L3_DATA,16) */SUM(G41_DEBIT_AMOUNT) DATA_REVENUE FROM L3_DATA
        WHERE G403_PAYTYPE=0
        AND G383_CHARGINGTIME_KEY =VDATE_KEY)BB,
        (SELECT /*+ PARALLEL(L3_RECURRING,16) */SUM(R41_DEBIT_AMOUNT) VAS_REVENUE FROM L3_RECURRING
        WHERE R374_PAYTYPE=0
        AND R377_CYCLEBEGINTIME_KEY =VDATE_KEY)CC,
        (SELECT /*+ PARALLEL(L3_SMS,16) */SUM(S41_DEBIT_AMOUNT) SMS_REVENUE FROM L3_SMS
        WHERE S398_PAYTYPE=0
        AND S387_CHARGINGTIME_KEY =VDATE_KEY)DD,
        (SELECT /*+ PARALLEL(L3_ADJUSTMENT,16) */SUM(A30_DEBIT_AMOUNT) ADJUSTMENT_REVENUE FROM L3_ADJUSTMENT
         WHERE A6_PAY_TYPE=0
         AND A22_ENTRY_DATE_KEY=VDATE_KEY)EE,
        (SELECT /*+ PARALLEL(L3_CONTENT,16) */ SUM(CO41_DEBIT_AMOUNT) CONTENT_REVENUE FROM L3_CONTENT
         WHERE CO410_PAYTYPE=0
         AND CO402_STARTTIMEOFBILLCYL_KEY=VDATE_KEY
         )FF
        
        ;

        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 561,PREPAID_REVENUE);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 561;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_REVENUE',561,'MULTPLE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
      
    ----------562 postpaid Revenue----------
    SELECT COUNT(STATUS) AS STATUS INTO  VSTATUS562
    FROM LIFECYCLE_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND  KPI_KEY = 562;

    IF VSTATUS562 = 0 THEN
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_REVENUE',562,'MULTPLE',VDATE_KEY,30,SYSDATE,'A');
        COMMIT;
        SELECT   COALESCE (VOICE_REVENUE, 0)
        + COALESCE (DATA_REVENUE, 0)
        + COALESCE (VAS_REVENUE, 0)
        + COALESCE (SMS_REVENUE, 0)
         + COALESCE (ADJUSTMENT_REVENUE, 0)
        + COALESCE (SMS_REVENUE, 0)
        INTO POSTPAID_REVENUE 
        FROM
        (SELECT /*+ PARALLEL(L3_VOICE,16) */ SUM(V41_DEBIT_AMOUNT) VOICE_REVENUE FROM L3_VOICE
        WHERE V400_PAYTYPE=1
        AND V387_CHARGINGTIME_KEY =VDATE_KEY),
        (SELECT /*+ PARALLEL(L3_DATA,16) */ SUM(G41_DEBIT_AMOUNT) DATA_REVENUE FROM L3_DATA
        WHERE G403_PAYTYPE=1
        AND G383_CHARGINGTIME_KEY =VDATE_KEY),
        (SELECT /*+ PARALLEL(L3_RECURRING,16) */ SUM(R41_DEBIT_AMOUNT) VAS_REVENUE FROM L3_RECURRING
        WHERE R374_PAYTYPE=1
        AND R377_CYCLEBEGINTIME_KEY =VDATE_KEY),
        (SELECT /*+ PARALLEL(L3_SMS,16) */ SUM(S41_DEBIT_AMOUNT) SMS_REVENUE FROM L3_SMS
        WHERE S398_PAYTYPE=1
        AND S387_CHARGINGTIME_KEY =VDATE_KEY),
         (SELECT /*+ PARALLEL(L3_ADJUSTMENT,16) */SUM(A30_DEBIT_AMOUNT) ADJUSTMENT_REVENUE FROM L3_ADJUSTMENT
         WHERE A6_PAY_TYPE=1
         AND A22_ENTRY_DATE_KEY=VDATE_KEY),
        (SELECT /*+ PARALLEL(L3_CONTENT,16) */ SUM(CO41_DEBIT_AMOUNT) CONTENT_REVENUE FROM L3_CONTENT
         WHERE CO410_PAYTYPE=1
         AND CO402_STARTTIMEOFBILLCYL_KEY=VDATE_KEY
         )
        ;
        
        INSERT INTO LIFECYCLE_KPI_FCT(DATE_KEY, KPI_KEY,KPI_VALUE)
        VALUES (VDATE_KEY, 562,POSTPAID_REVENUE);
        COMMIT;
                
        UPDATE LIFECYCLE_LOG SET 
        STATUS = 96
        WHERE DATE_KEY = VDATE_KEY
        AND KPI_KEY = 562;        
        COMMIT;
    ELSE
        INSERT INTO LIFECYCLE_LOG (PROCEDURE_NAME, KPI_KEY, SOURCE, DATE_KEY, STATUS, INSERT_TIME, REMARKS)
        VALUES                    ('SP_LIFECYCLE_REVENUE',562,'MULTPLE',VDATE_KEY,34,SYSDATE,'A');
        COMMIT;
    END IF;
END;
/

