--
-- SP_MIGRATION_CONDITION  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_MIGRATION_CONDITION(P_DATE VARCHAR2) AS
VDATE_KEY VARCHAR2(4);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM 
WHERE TRUNC(DATE_VALUE)=TRUNC(TO_DATE(P_DATE,'RRRR/MM/DD'));
    
    ---------------eligible for migration(yes list)----------------------
    INSERT INTO MIGRATION_CONDITION(DATE_KEY,MSISDN,STATUS)
    SELECT VDATE_KEY,MSISDN,'Y'
    FROM L3_MIGRATION_BASE WHERE  DATE_KEY=VDATE_KEY
    and MSISDN NOT IN (SELECT UNIQUE V372_CALLINGPARTYNUMBER 
                       FROM (SELECT /*+PARALLEL(P,16)*/ V387_CHARGINGTIME_KEY, V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID, COUNT (V372_CALLINGPARTYNUMBER) AS CALL_COUNT,
                            COUNT (DISTINCT V373_CALLEDPARTYNUMBER) AS DIST_COUNT,SUM (V35_RATE_USAGE) / 60 AS DUR,SUM (V35_RATE_USAGE)/ COUNT (V372_CALLINGPARTYNUMBER)AS AVG_DUR,COUNT (DISTINCT V381_CALLINGCELLID)AS CELL_COUNT
                            FROM L3_VOICE P
                            WHERE     V387_CHARGINGTIME_KEY =VDATE_KEY
                            AND V378_SERVICEFLOW = '1'
                            GROUP BY V387_CHARGINGTIME_KEY, V372_CALLINGPARTYNUMBER, V397_MAINOFFERINGID)
                    WHERE  CALL_COUNT > 15
                    AND CELL_COUNT <= 6
                    AND DUR >= 40
                    AND AVG_DUR > 180
                    AND (DIST_COUNT / CALL_COUNT) >= .9);
    COMMIT;


    ---------------not eligible for migration(no list)----------------------
    INSERT INTO MIGRATION_CONDITION
    SELECT V387_CHARGINGTIME_KEY as date_key,V372_CALLINGPARTYNUMBER as msisdn,CALL_COUNT,DIST_COUNT,DUR,AVG_DUR,CELL_COUNT,'N' SYATUS
    FROM
    (SELECT /*+ parallel(P,16)*/ V387_CHARGINGTIME_KEY,V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID,COUNT (V372_CALLINGPARTYNUMBER)AS CALL_COUNT,COUNT (DISTINCT V373_CALLEDPARTYNUMBER) AS DIST_COUNT,
    SUM (V35_RATE_USAGE) / 60 AS DUR,SUM (V35_RATE_USAGE)/ COUNT (V372_CALLINGPARTYNUMBER)AS AVG_DUR,COUNT (DISTINCT V381_CALLINGCELLID)AS CELL_COUNT
    FROM L3_VOICE P, L3_MIGRATION_BASE Q
    WHERE V387_CHARGINGTIME_KEY =VDATE_KEY
    AND Q.DATE_KEY= VDATE_KEY
    AND Q.MSISDN=V372_CALLINGPARTYNUMBER
    AND V378_SERVICEFLOW = '1'
    GROUP BY V387_CHARGINGTIME_KEY,V372_CALLINGPARTYNUMBER,V397_MAINOFFERINGID)
    WHERE   CALL_COUNT > 15
    AND     CELL_COUNT <= 6
    AND     DUR >= 40
    AND     AVG_DUR > 180
    AND     (DIST_COUNT / CALL_COUNT) >= .9;
    COMMIT;
END;
/

